#
# 
#
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

EXTRA_SRCS=${PROD_SRC_ROOT}/include/climod_common.h
PO_OUTPUT_DIR=${PROD_BASE_I18N_ROOT}/src/lib/libcli
MO_OUTPUT_DIR=${LIB_DIR}/libcli/mo

include ${PROD_TREE_ROOT}/src/mk/po.mk

