# Makefile

include ${PROD_TREE_ROOT}/src/mk/common.mk

INSTALL_DIRECTIVES= \
	${SYS_INSTALL_FILE_customer_var_var_version_sh} \
	${SYS_INSTALL_FILE_customer_etc_var_version_sh} \


SYS_INSTALL_FILE_customer_var_var_version_sh="file var_version_tmsexample.sh 0644 root root /var/var_version_tmsexample.sh"
SYS_INSTALL_FILE_customer_etc_var_version_sh="file var_version_tmsexample.sh 0644 root root /etc/var_version_tmsexample.sh"

include ${PROD_TREE_ROOT}/src/mk/files_adv.mk
