#  Makefile
#
# 
#
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

FILES_INSTALL_DIR=/usr/share/zile
PROD_INSTALL_PREFIX=

FILES=                            \
	src/etc/MINIHELP1         \
	src/etc/MINIHELP2         \
	src/etc/MINIHELP3         \
	src/etc/HELP              \
	src/etc/FAQ               \
	src/etc/AUTODOC           \
	src/etc/LATEST_VERSION    \
	src/etc/TUTORIAL          \
	src/etc/zilerc.sample     \


SUBDIRS=        \
	lib     \
	bin     \


include ${PROD_TREE_ROOT}/src/mk/files.mk
