#  Makefile

include ${PROD_TREE_ROOT}/src/mk/common.mk
include ../../Makefile.inc

FILES_INSTALL_DIR=web/cgi-bin

FILES_PERM_MODE=755

FILES= \
	mfllog_analysis.pl	\

include ${PROD_TREE_ROOT}/src/mk/files.mk
