#ifndef _MFP_ERR_H
#define _MFP_ERR_H

/* ERROR CODE FOR GENERIC MFP ERRORS (1-99)*/
#define E_MFP_NO_MEM 1
#define E_MFP_INVALID_FILE 2
#define E_MFP_INVALID_SESS 3
#define E_MFP_INVALID_CONVERSION_REQ 4
#define E_MFP_SOCK_CREATE 5
#define E_MFP_BIND_FAIL 6
#define E_MFP_NO_SPACE 7
#define E_MFP_SESS_TIMEOUT 8
#define E_MFP_OPEN_CFG_FILE 9
#define E_MFP_MULT_CONF 10
#define E_VPE_WRITE_ERR 11
#define E_MFP_SSL_LICENSE_UNAVAIL 12
#define E_MFP_SSL_LICENSE_ERR 13
#define E_MFP_SSL_LICENSE_FAIL 14

/* ERROR CODE FOR PMF HANDLING (1000-1100)*/
#define E_MFP_PMF_INVALID_FILE 1000
#define E_MFP_PMF_NO_MEM 1001
#define E_MFP_PMF_INVALID_TAG 1002
#define E_MFP_PMF_INVALID_ARG 1003
#define E_MFP_PMF_UNSUPPORTED_TYPE 1004
#define E_MFP_PMF_INCOMPLETE_TAG 1005
#define E_MFP_PMF_DOC_PTR_FAILED 1006
#define E_MFP_PMF_XSD_MISMATCH 1007
#define	E_MFP_PMF_XSD_INT_ERROR 1008
#define E_MFP_PMF_INSUFF_MEDIA_TYPE 1009
#define E_MFP_PMF_INCOMPATIBLE_MEDIA_TYPE 1010
#define E_MFP_PMF_INVALID_DELIVERY_URI 1011
#define E_MFP_PMF_INCOMPAT 1012
#define E_MFP_PMF_INVALID_SCHED_TIME 1013
#define E_MFP_PMF_UNSUPPORTED_CTRL_ACTION 1014

/*ERROR CODE FOR ACCUMULATOR (2000-2100)*/
#define E_MFP_ACCUM_INIT	(2000)


/*ERROR CODE FOR TS  FORMATTER (3000-3100)*/
#define E_MFP_PUBL_FORM_KFI_UNEQUAL 3000
#define E_MFP_FRUIT_INIT 3001
#define E_MFP_SL_INIT 3002
#define E_MFP_IV_ERR 3003
#define E_MFP_FRUIT_INVALID_ARG 3004

/* ERROR CODE FOR SAFE IO (3100-3200) */
#define E_MFP_SAFE_IO_ATTACH_FAIL 3100
#define E_MFP_SAFE_IO_NOSPACE 3101
#define E_MFP_SAFE_IO_ERONLY 3102
#define E_MFP_SAFE_IO_ESTAT 3103
#define E_MFP_SAFE_IO_PATH_EXISTS 3104
#define E_MFP_SAFE_IO_EMOUNT_POINT 3105

/* ERROR CODE FOR KMS / ENCRYPTION (3201-3300) */
#define E_MFP_KMS_INVALID_ARG 3201
#define E_MFP_KMS_VMX_SOCK_FAIL 3202
#define E_MFP_KMS_VMX_CONNECT_FAIL 3203
#define E_MFP_KMS_VMX_SEND_FAIL 3204
#define E_MFP_KMS_VMX_RCV_FAIL 3205
#define E_MFP_KMS_VMX_ADDR_FAIL 3206
#define E_MFP_KMS_VMX_INVALID_RESPCODE 3207

#endif
