URL_MAX_SIZE = 512
SIGNATURE = '***END***'
MAX_DICT_SIZE = 25000
LOG_FILE = '/var/log/log_analyzer_dpi.log'
ANALYZER_CONF = 'analyzer.conf'
DEFAULT_CONF_PATH = '/config/nkn/dpi-analyzer/'
OVERRIDE_RULES_XML = '/config/nkn/dpi-analyzer/override_rules.xml'
DPI_ANALYZER_RESULT_FILE = '/var/log/dpi_analyzer_pbr.txt'
MAXLOG_SIZE = 104857600  ##100 MB
LOGBACKP_COUNT = 10
DEST_IP_PICKLE = 'dpi_loganalyzer_destip.pickle'
MFC_LOG_FILE = '/var/log/messages'
DEVICE_MAP_COMMON= '/nkn/device_map/config/'
LOG_ANALYZER_COMMON= '/nkn/log_analyzer/config/'
DEFAULT_GOLDEN_CONFIG='/config/nkn/dpi-analyzer/golden_config.txt'
MFC_CONFIG='/config/nkn/dpi-analyzer/mfc_config.txt'
CLEAR_FILTER_RULES_FILE = '/var/log/clear_filter_rules.txt'
TMP_DEST_IP_PICKLE = 'tmp_dpi_loganalyzer_destip.pickle'
