# Makefile

include ${PROD_TREE_ROOT}/src/mk/common.mk

# The subdir libcli has graft files included from the PROD_TREE_ROOT side of the build.

SUBDIRS=\
	common \
	event_disp \
	dns_pb \
	uint_ctx_cont \
	lfc \
	stored \
	stored/geodb \
	cont_pool \
	de \

include ${PROD_TREE_ROOT}/src/mk/subdir.mk
