#  Makefile
#
#
#
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

LIB=license

SRCS= \
	license_common.c \
	license_lk1.c \
	license_lk2.c \

INCLUDES= \
	-I${PROD_TREE_ROOT}/src/lib/libgcl \

include ${PROD_TREE_ROOT}/src/mk/lib.mk
