# Filename: lib/cr/stored/Makefile

include ${PROD_TREE_ROOT}/src/mk/common.mk

# The subdir libcli has graft files included from the PROD_TREE_ROOT side of the build.

SUBDIRS=\
	proto_pr_bldr \
	geodb \

include ${PROD_TREE_ROOT}/src/mk/subdir.mk
