********************************************************************************
*                                                                              *
*               Welcome to Juniper's Media Flow Controller Platform            *
*                                                                              *
********************************************************************************
Network booting of Media Flow Controller should start shortly ...


