#  Makefile
#
# 
#
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

LIB=tcrypt

SRCS= \
	tcrypt.c \


CFLAGS=

# XXX these should be done in a more compact way
LDADD= \
	${PROD_BUILD_OUTPUT_DIR}/${INSTALL_TREE}/${LIB_DIR}/libcommon/libcommon.a

include ${PROD_TREE_ROOT}/src/mk/lib.mk
