# Makefile

include ${PROD_TREE_ROOT}/src/mk/common.mk

# The subdir libcli has graft files included from the PROD_TREE_ROOT side of the build.

SUBDIRS= \
  nkncnt \
  sslcnt \
  nkncounters \
  nkncnt_client \
  nknlog \
  nvsd \
  mediacodecs \
  mfp \
  cr \
  libcli \
  nkncmm \
  proxyd \
  libmgmtlog \
  ccp \
  ptrie \
  cb \
  proto_http \
  libnet \
  libjmdb \
  nknalog \
  jpsd \

include ${PROD_TREE_ROOT}/src/mk/subdir.mk

