#  Makefile

include ${PROD_TREE_ROOT}/src/mk/common.mk
include ../../Makefile.inc

FILES_INSTALL_DIR=web/html

FILES= \
	mfl-default.css		\
	mfl-utils.js		\
	mfllog-analysis.html	\


SUBDIRS= \
        images \

include ${PROD_TREE_ROOT}/src/mk/files.mk
