#  Makefile
#
# 
#
#

# libtac must be built first

include ${PROD_TREE_ROOT}/src/mk/common.mk

SUBDIRS=\
	libtac \
	lib \


# NOTE: These directories must be built and installed as 'root'

include ${PROD_TREE_ROOT}/src/mk/subdir.mk
