#  Makefile
#
#  Filename:  src/mfl/mflweb/images/Makefile
#  Revision:  $Revision: 1.0
#  Date:      $Date: 2011/03/03$
#  Author:    $Author: 
# 
#

include ${PROD_TREE_ROOT}/src/mk/common.mk
include ../../../Makefile.inc

FILES_INSTALL_DIR=web/html/images

# Note juniper-logo.jpg is reference in src/bin/web/templates/tms-layout.tem

FILES= \
	logo.jpg \
	green_h.gif \
	brown_v.gif \
	purple_v.gif \
	blue_v.gif \
	cyan_v.gif \
	yellow_v.gif \
	orange_v.gif \
	magenda_v.gif \
	green_v.gif \
	la_bg_big.gif \


include ${PROD_TREE_ROOT}/src/mk/files.mk
