#!/bin/sh

#
# (C) Copyright 2013-2015 Juniper Networks, Inc. All Rights reserved.
# (C) Copyright 2002-2006 Tall Maple Systems, Inc.
# All rights reserved.
# The contents of this file are subject to the terms of the MIT License.
# You may not use this file except in compliance with the License.
# See the file License.txt at the top of this source tree.
# You can obtain a copy of the license at https://opensource.org/licenses/MIT
#

# Some layouts may want to use IL_HWNAME_LC, so compute it first
if [ ! -z "${IL_HWNAME}" ]; then
    IL_HWNAME_LC="$(echo "${IL_HWNAME}" | tr '[A-Z]' '[a-z]')"
fi

# ==================================================
#
# Standard two image layout
#
# ==================================================

# These are the standard location names.  They should not be changed
IL_LO_STD_LOCS="BOOTMGR_1 BOOT_1 BOOT_2 ROOT_1 ROOT_2 SWAP_1 CONFIG_1 VAR_1"

# Targets are things like a disk or a flash device
IL_LO_STD_TARGET_NUM_TARGETS=1
IL_LO_STD_TARGETS="DISK1"
IL_LO_STD_TARGET_DISK1_NUM=1

# Configuration option to indicate that the root locations
# should be read-only. It is still necessary to indicate
# 'ro' in the partition option line for root.
IL_LO_STD_ROOT_RDONLY=1

# Set this to use an initrd (initial ramdisk) at kernel boot time.  This
# is relative to the layout's LOC_BOOT_*_DIR , so you probably do not
# want a leading / in this name.
#
# Note, if you are using VPARTs (with a ..._ISROOTFS=1), do not set this
# option, as it may conflict.  
IL_LO_STD_INITRD_PATH=

# If we want the root device mounted by label instead of device name.
# Note that all partitions are mounted by label once the system has
# booted.  This setting is only about what the kernel does on startup.
#
# NOTE: This only makes sense if you have an initrd, as the kernel
# cannot do the label lookup for things like 'LABEL=ROOT_1' .
# initrd's are not currently produced by the build process.
IL_LO_STD_ROOT_MOUNT_BY_LABEL=0

IL_LO_STD_TARGET_DISK1_MINSIZE=4000
IL_LO_STD_TARGET_DISK1_LABELTYPE=

# What partitions get made on the targets
IL_LO_STD_PARTS="BOOTMGR BOOT1 BOOT2 EXT ROOT1 ROOT2 SWAP CONFIG VAR"

IL_LO_STD_IMAGE_1_INSTALL_LOCS="BOOT_1 ROOT_1"
IL_LO_STD_IMAGE_2_INSTALL_LOCS="BOOT_2 ROOT_2"
IL_LO_STD_IMAGE_1_LOCS="ROOT_1 BOOT_1 BOOTMGR_1 CONFIG_1 VAR_1 SWAP_1"
IL_LO_STD_IMAGE_2_LOCS="ROOT_2 BOOT_2 BOOTMGR_1 CONFIG_1 VAR_1 SWAP_1"

IL_LO_STD_OPT_LAST_PART_FILL=1

# Each of these says which PART (partition) below goes with which LOC
#     (standardized location) .  It also says for each LOC which subdirectory
#     under the PART the LOC is in, and what files to extract there


# IL_LO_STD_LOC_BOOT_1_PART=P1
# IL_LO_STD_LOC_BOOT_1_DIR=/bod
# IL_LO_STD_LOC_BOOT_1_IMAGE_EXTRACT="./boot"
# IL_LO_STD_LOC_BOOT_1_IMAGE_EXTRACT_PREFIX="/boot"
#
# tar -C = $TRUE_MP
# extract mount point = $TRUE_MP/$EXTRACT_PREFIX
#
# Possible mappings with these vars (different extract prefixes) :
#
#  ""               ./boot/standard/foo -> TRUE_MP/bod/boot/standard/foo
#  "/boot"          ./boot/standard/foo -> TRUE_MP/bod/standard/foo
#  "/boot/standard" ./boot/standard/foo -> TRUE_MP/bod/foo


IL_LO_STD_LOC_BOOTMGR_1_PART=BOOTMGR
IL_LO_STD_LOC_BOOTMGR_1_DIR=/
IL_LO_STD_LOC_BOOTMGR_1_IMAGE_EXTRACT="./bootmgr"
IL_LO_STD_LOC_BOOTMGR_1_IMAGE_EXTRACT_PREFIX="/bootmgr"

IL_LO_STD_LOC_BOOT_1_PART=BOOT1
IL_LO_STD_LOC_BOOT_1_DIR=/
IL_LO_STD_LOC_BOOT_1_IMAGE_EXTRACT="./boot"
IL_LO_STD_LOC_BOOT_1_IMAGE_EXTRACT_PREFIX="/boot"

IL_LO_STD_LOC_BOOT_2_PART=BOOT2
IL_LO_STD_LOC_BOOT_2_DIR=/
IL_LO_STD_LOC_BOOT_2_IMAGE_EXTRACT="./boot"
IL_LO_STD_LOC_BOOT_2_IMAGE_EXTRACT_PREFIX="/boot"

IL_LO_STD_LOC_ROOT_1_PART=ROOT1
IL_LO_STD_LOC_ROOT_1_DIR=/
IL_LO_STD_LOC_ROOT_1_IMAGE_EXTRACT="./"
IL_LO_STD_LOC_ROOT_1_IMAGE_EXTRACT_EXCLUDE="./bootmgr ./boot ./config ./var"
IL_LO_STD_LOC_ROOT_1_IMAGE_EXTRACT_PREFIX=""

IL_LO_STD_LOC_ROOT_2_PART=ROOT2
IL_LO_STD_LOC_ROOT_2_DIR=/
IL_LO_STD_LOC_ROOT_2_IMAGE_EXTRACT="./"
IL_LO_STD_LOC_ROOT_2_IMAGE_EXTRACT_EXCLUDE="./bootmgr ./boot ./config ./var"
IL_LO_STD_LOC_ROOT_2_IMAGE_EXTRACT_PREFIX=""

IL_LO_STD_LOC_SWAP_1_PART=SWAP
IL_LO_STD_LOC_SWAP_1_DIR=
IL_LO_STD_LOC_SWAP_1_IMAGE_EXTRACT=""
IL_LO_STD_LOC_SWAP_1_IMAGE_EXTRACT_PREFIX=""

IL_LO_STD_LOC_CONFIG_1_PART=CONFIG
IL_LO_STD_LOC_CONFIG_1_DIR=/
IL_LO_STD_LOC_CONFIG_1_IMAGE_EXTRACT="./config"
IL_LO_STD_LOC_CONFIG_1_IMAGE_EXTRACT_PREFIX="/config"

IL_LO_STD_LOC_VAR_1_PART=VAR
IL_LO_STD_LOC_VAR_1_DIR=/
IL_LO_STD_LOC_VAR_1_IMAGE_EXTRACT="./var"
IL_LO_STD_LOC_VAR_1_IMAGE_EXTRACT_PREFIX="/var"


# Each of these says how a partition is named, labled, and sized.

IL_LO_STD_PART_BOOTMGR_TARGET=DISK1
IL_LO_STD_PART_BOOTMGR_PART_NUM=1
IL_LO_STD_PART_BOOTMGR_DEV=${IL_LO_STD_TARGET_DISK1_DEV}${IL_LO_STD_PART_BOOTMGR_PART_NUM}
IL_LO_STD_PART_BOOTMGR_LABEL=BOOTMGR
IL_LO_STD_PART_BOOTMGR_MOUNT=/bootmgr
IL_LO_STD_PART_BOOTMGR_BOOTABLE=1
IL_LO_STD_PART_BOOTMGR_PART_ID=83
IL_LO_STD_PART_BOOTMGR_FSTYPE=ext3
IL_LO_STD_PART_BOOTMGR_SIZE=128
IL_LO_STD_PART_BOOTMGR_GROWTHCAP=
IL_LO_STD_PART_BOOTMGR_GROWTHWEIGHT=
IL_LO_STD_PART_BOOTMGR_OPTIONS="defaults,noatime,ro"

IL_LO_STD_PART_BOOT1_TARGET=DISK1
IL_LO_STD_PART_BOOT1_PART_NUM=2
IL_LO_STD_PART_BOOT1_DEV=${IL_LO_STD_TARGET_DISK1_DEV}${IL_LO_STD_PART_BOOT1_PART_NUM}
IL_LO_STD_PART_BOOT1_LABEL=BOOT_1
IL_LO_STD_PART_BOOT1_MOUNT=/boot
IL_LO_STD_PART_BOOT1_BOOTABLE=
IL_LO_STD_PART_BOOT1_PART_ID=83
IL_LO_STD_PART_BOOT1_FSTYPE=ext3
IL_LO_STD_PART_BOOT1_SIZE=128
IL_LO_STD_PART_BOOT1_GROWTHCAP=
IL_LO_STD_PART_BOOT1_GROWTHWEIGHT=
IL_LO_STD_PART_BOOT1_OPTIONS="defaults,noatime,ro"

IL_LO_STD_PART_BOOT2_TARGET=DISK1
IL_LO_STD_PART_BOOT2_PART_NUM=3
IL_LO_STD_PART_BOOT2_DEV=${IL_LO_STD_TARGET_DISK1_DEV}${IL_LO_STD_PART_BOOT2_PART_NUM}
IL_LO_STD_PART_BOOT2_LABEL=BOOT_2
IL_LO_STD_PART_BOOT2_MOUNT=/boot
IL_LO_STD_PART_BOOT2_BOOTABLE=
IL_LO_STD_PART_BOOT2_PART_ID=83
IL_LO_STD_PART_BOOT2_FSTYPE=ext3
IL_LO_STD_PART_BOOT2_SIZE=128
IL_LO_STD_PART_BOOT2_GROWTHCAP=
IL_LO_STD_PART_BOOT2_GROWTHWEIGHT=
IL_LO_STD_PART_BOOT2_OPTIONS="defaults,noatime,ro"

IL_LO_STD_PART_EXT_TARGET=DISK1
IL_LO_STD_PART_EXT_PART_NUM=4
IL_LO_STD_PART_EXT_DEV=${IL_LO_STD_TARGET_DISK1_DEV}${IL_LO_STD_PART_EXT_PART_NUM}
IL_LO_STD_PART_EXT_LABEL=
IL_LO_STD_PART_EXT_MOUNT=
IL_LO_STD_PART_EXT_BOOTABLE=
IL_LO_STD_PART_EXT_PART_ID=0f
IL_LO_STD_PART_EXT_FSTYPE=
IL_LO_STD_PART_EXT_SIZE=
IL_LO_STD_PART_EXT_GROWTHCAP=
IL_LO_STD_PART_EXT_GROWTHWEIGHT=

IL_LO_STD_PART_ROOT1_TARGET=DISK1
IL_LO_STD_PART_ROOT1_PART_NUM=5
IL_LO_STD_PART_ROOT1_DEV=${IL_LO_STD_TARGET_DISK1_DEV}${IL_LO_STD_PART_ROOT1_PART_NUM}
IL_LO_STD_PART_ROOT1_LABEL=ROOT_1
IL_LO_STD_PART_ROOT1_MOUNT=/
IL_LO_STD_PART_ROOT1_BOOTABLE=
IL_LO_STD_PART_ROOT1_PART_ID=83
IL_LO_STD_PART_ROOT1_FSTYPE=ext3
IL_LO_STD_PART_ROOT1_SIZE=640
IL_LO_STD_PART_ROOT1_GROWTHCAP=
IL_LO_STD_PART_ROOT1_GROWTHWEIGHT=
IL_LO_STD_PART_ROOT1_OPTIONS="defaults,noatime,ro"

IL_LO_STD_PART_ROOT2_TARGET=DISK1
IL_LO_STD_PART_ROOT2_PART_NUM=6
IL_LO_STD_PART_ROOT2_DEV=${IL_LO_STD_TARGET_DISK1_DEV}${IL_LO_STD_PART_ROOT2_PART_NUM}
IL_LO_STD_PART_ROOT2_LABEL=ROOT_2
IL_LO_STD_PART_ROOT2_MOUNT=/
IL_LO_STD_PART_ROOT2_BOOTABLE=
IL_LO_STD_PART_ROOT2_PART_ID=83
IL_LO_STD_PART_ROOT2_FSTYPE=ext3
IL_LO_STD_PART_ROOT2_SIZE=640
IL_LO_STD_PART_ROOT2_GROWTHCAP=
IL_LO_STD_PART_ROOT2_GROWTHWEIGHT=
IL_LO_STD_PART_ROOT2_OPTIONS="defaults,noatime,ro"

IL_LO_STD_PART_SWAP_TARGET=DISK1
IL_LO_STD_PART_SWAP_PART_NUM=7
IL_LO_STD_PART_SWAP_DEV=${IL_LO_STD_TARGET_DISK1_DEV}${IL_LO_STD_PART_SWAP_PART_NUM}
IL_LO_STD_PART_SWAP_LABEL=SWAP_1
IL_LO_STD_PART_SWAP_MOUNT=swap
IL_LO_STD_PART_SWAP_BOOTABLE=
IL_LO_STD_PART_SWAP_PART_ID=82
IL_LO_STD_PART_SWAP_FSTYPE=swap
IL_LO_STD_PART_SWAP_SIZE=1024
IL_LO_STD_PART_SWAP_GROWTHCAP=
IL_LO_STD_PART_SWAP_GROWTHWEIGHT=

IL_LO_STD_PART_CONFIG_TARGET=DISK1
IL_LO_STD_PART_CONFIG_PART_NUM=8
IL_LO_STD_PART_CONFIG_DEV=${IL_LO_STD_TARGET_DISK1_DEV}${IL_LO_STD_PART_CONFIG_PART_NUM}
IL_LO_STD_PART_CONFIG_LABEL=CONFIG
IL_LO_STD_PART_CONFIG_MOUNT=/config
IL_LO_STD_PART_CONFIG_BOOTABLE=
IL_LO_STD_PART_CONFIG_PART_ID=83
IL_LO_STD_PART_CONFIG_FSTYPE=ext3
IL_LO_STD_PART_CONFIG_SIZE=192
IL_LO_STD_PART_CONFIG_GROWTHCAP=
IL_LO_STD_PART_CONFIG_GROWTHWEIGHT=

IL_LO_STD_PART_VAR_TARGET=DISK1
IL_LO_STD_PART_VAR_PART_NUM=9
IL_LO_STD_PART_VAR_DEV=${IL_LO_STD_TARGET_DISK1_DEV}${IL_LO_STD_PART_VAR_PART_NUM}
IL_LO_STD_PART_VAR_LABEL=VAR
IL_LO_STD_PART_VAR_MOUNT=/var
IL_LO_STD_PART_VAR_BOOTABLE=
IL_LO_STD_PART_VAR_PART_ID=83
IL_LO_STD_PART_VAR_FSTYPE=ext3
IL_LO_STD_PART_VAR_SIZE=1024
IL_LO_STD_PART_VAR_GROWTHCAP=
IL_LO_STD_PART_VAR_GROWTHWEIGHT=





# ==================================================
#
# Replicated  two image layout
#
# ==================================================

# These are the standard location names.  They should not be changed
IL_LO_REPL_LOCS="BOOTMGR_1 BOOT_1 BOOT_2 ROOT_1 ROOT_2 SWAP_1 CONFIG_1 VAR_1 \
    REPL_BOOTMGR_1 REPL_BOOT_1 REPL_BOOT_2 REPL_ROOT_1 REPL_ROOT_2 \
    REPL_SWAP_1 REPL_CONFIG_1 REPL_VAR_1"

# Targets are things like a disk or a flash device
IL_LO_REPL_TARGET_NUM_TARGETS=2
IL_LO_REPL_TARGETS="DISK1 DISK2"
IL_LO_REPL_TARGET_DISK1_NUM=1
IL_LO_REPL_TARGET_DISK2_NUM=2

IL_LO_REPL_ROOT_RDONLY=1

IL_LO_REPL_TARGET_DISK1_MINSIZE=4000
IL_LO_REPL_TARGET_DISK2_MINSIZE=4000

# What partitions get made on the targets
IL_LO_REPL_PARTS="BOOTMGR BOOT1 BOOT2 EXT ROOT1 ROOT2 SWAP CONFIG VAR \
    REPL_BOOTMGR REPL_BOOT1 REPL_BOOT2 REPL_EXT REPL_ROOT1 REPL_ROOT2 REPL_SWAP REPL_CONFIG REPL_VAR"

IL_LO_REPL_IMAGE_1_INSTALL_LOCS="BOOT_1 ROOT_1"
IL_LO_REPL_IMAGE_2_INSTALL_LOCS="BOOT_2 ROOT_2"
IL_LO_REPL_IMAGE_1_LOCS="ROOT_1 BOOT_1 BOOTMGR_1 CONFIG_1 VAR_1 SWAP_1"
IL_LO_REPL_IMAGE_2_LOCS="ROOT_2 BOOT_2 BOOTMGR_1 CONFIG_1 VAR_1 SWAP_1"

IL_LO_REPL_OPT_LAST_PART_FILL=1


IL_LO_REPL_LOC_BOOTMGR_1_PART=BOOTMGR
IL_LO_REPL_LOC_BOOTMGR_1_DIR=/
IL_LO_REPL_LOC_BOOTMGR_1_IMAGE_EXTRACT="./bootmgr"
IL_LO_REPL_LOC_BOOTMGR_1_IMAGE_EXTRACT_PREFIX="/bootmgr"

IL_LO_REPL_LOC_BOOT_1_PART=BOOT1
IL_LO_REPL_LOC_BOOT_1_DIR=/
IL_LO_REPL_LOC_BOOT_1_IMAGE_EXTRACT="./boot"
IL_LO_REPL_LOC_BOOT_1_IMAGE_EXTRACT_PREFIX="/boot"

IL_LO_REPL_LOC_BOOT_2_PART=BOOT2
IL_LO_REPL_LOC_BOOT_2_DIR=/
IL_LO_REPL_LOC_BOOT_2_IMAGE_EXTRACT="./boot"
IL_LO_REPL_LOC_BOOT_2_IMAGE_EXTRACT_PREFIX="/boot"

IL_LO_REPL_LOC_ROOT_1_PART=ROOT1
IL_LO_REPL_LOC_ROOT_1_DIR=/
IL_LO_REPL_LOC_ROOT_1_IMAGE_EXTRACT="./"
IL_LO_REPL_LOC_ROOT_1_IMAGE_EXTRACT_EXCLUDE="./bootmgr ./boot ./config ./var"
IL_LO_REPL_LOC_ROOT_1_IMAGE_EXTRACT_PREFIX=""

IL_LO_REPL_LOC_ROOT_2_PART=ROOT2
IL_LO_REPL_LOC_ROOT_2_DIR=/
IL_LO_REPL_LOC_ROOT_2_IMAGE_EXTRACT="./"
IL_LO_REPL_LOC_ROOT_2_IMAGE_EXTRACT_EXCLUDE="./bootmgr ./boot ./config ./var"
IL_LO_REPL_LOC_ROOT_2_IMAGE_EXTRACT_PREFIX=""

IL_LO_REPL_LOC_SWAP_1_PART=SWAP
IL_LO_REPL_LOC_SWAP_1_DIR=
IL_LO_REPL_LOC_SWAP_1_IMAGE_EXTRACT=""
IL_LO_REPL_LOC_SWAP_1_IMAGE_EXTRACT_PREFIX=""

IL_LO_REPL_LOC_VAR_1_PART=VAR
IL_LO_REPL_LOC_VAR_1_DIR=/
IL_LO_REPL_LOC_VAR_1_IMAGE_EXTRACT="./var"
IL_LO_REPL_LOC_VAR_1_IMAGE_EXTRACT_PREFIX="/var"

IL_LO_REPL_LOC_CONFIG_1_PART=CONFIG
IL_LO_REPL_LOC_CONFIG_1_DIR=/
IL_LO_REPL_LOC_CONFIG_1_IMAGE_EXTRACT="./config"
IL_LO_REPL_LOC_CONFIG_1_IMAGE_EXTRACT_PREFIX="/config"



IL_LO_REPL_LOC_REPL_BOOTMGR_1_PART=REPL_BOOTMGR
IL_LO_REPL_LOC_REPL_BOOTMGR_1_DIR=/
IL_LO_REPL_LOC_REPL_BOOTMGR_1_IMAGE_EXTRACT="./bootmgr"
IL_LO_REPL_LOC_REPL_BOOTMGR_1_IMAGE_EXTRACT_PREFIX="/bootmgr"

IL_LO_REPL_LOC_REPL_BOOT_1_PART=REPL_BOOT1
IL_LO_REPL_LOC_REPL_BOOT_1_DIR=/
IL_LO_REPL_LOC_REPL_BOOT_1_IMAGE_EXTRACT="./boot"
IL_LO_REPL_LOC_REPL_BOOT_1_IMAGE_EXTRACT_PREFIX="/boot"

IL_LO_REPL_LOC_REPL_BOOT_2_PART=REPL_BOOT2
IL_LO_REPL_LOC_REPL_BOOT_2_DIR=/
IL_LO_REPL_LOC_REPL_BOOT_2_IMAGE_EXTRACT="./boot"
IL_LO_REPL_LOC_REPL_BOOT_2_IMAGE_EXTRACT_PREFIX="/boot"

IL_LO_REPL_LOC_REPL_ROOT_1_PART=REPL_ROOT1
IL_LO_REPL_LOC_REPL_ROOT_1_DIR=/
IL_LO_REPL_LOC_REPL_ROOT_1_IMAGE_EXTRACT="./"
IL_LO_REPL_LOC_REPL_ROOT_1_IMAGE_EXTRACT_EXCLUDE="./bootmgr ./boot ./var ./config"
IL_LO_REPL_LOC_REPL_ROOT_1_IMAGE_EXTRACT_PREFIX=""

IL_LO_REPL_LOC_REPL_ROOT_2_PART=REPL_ROOT2
IL_LO_REPL_LOC_REPL_ROOT_2_DIR=/
IL_LO_REPL_LOC_REPL_ROOT_2_IMAGE_EXTRACT="./"
IL_LO_REPL_LOC_REPL_ROOT_2_IMAGE_EXTRACT_EXCLUDE="./bootmgr ./boot ./var ./config"
IL_LO_REPL_LOC_REPL_ROOT_2_IMAGE_EXTRACT_PREFIX=""

IL_LO_REPL_LOC_REPL_SWAP_1_PART=REPL_SWAP
IL_LO_REPL_LOC_REPL_SWAP_1_DIR=
IL_LO_REPL_LOC_REPL_SWAP_1_IMAGE_EXTRACT=""
IL_LO_REPL_LOC_REPL_SWAP_1_IMAGE_EXTRACT_PREFIX=""

IL_LO_REPL_LOC_REPL_VAR_1_PART=REPL_VAR
IL_LO_REPL_LOC_REPL_VAR_1_DIR=/
IL_LO_REPL_LOC_REPL_VAR_1_IMAGE_EXTRACT="./var"
IL_LO_REPL_LOC_REPL_VAR_1_IMAGE_EXTRACT_PREFIX="/var"

IL_LO_REPL_LOC_REPL_CONFIG_1_PART=REPL_CONFIG
IL_LO_REPL_LOC_REPL_CONFIG_1_DIR=/
IL_LO_REPL_LOC_REPL_CONFIG_1_IMAGE_EXTRACT="./config"
IL_LO_REPL_LOC_REPL_CONFIG_1_IMAGE_EXTRACT_PREFIX="/config"



# Each of these says how a partition is named, labled, and sized.

IL_LO_REPL_PART_BOOTMGR_TARGET=DISK1
IL_LO_REPL_PART_BOOTMGR_PART_NUM=1
IL_LO_REPL_PART_BOOTMGR_DEV=${IL_LO_REPL_TARGET_DISK1_DEV}${IL_LO_REPL_PART_BOOTMGR_PART_NUM}
IL_LO_REPL_PART_BOOTMGR_LABEL=BOOTMGR
IL_LO_REPL_PART_BOOTMGR_MOUNT=/bootmgr
IL_LO_REPL_PART_BOOTMGR_BOOTABLE=1
IL_LO_REPL_PART_BOOTMGR_PART_ID=83
IL_LO_REPL_PART_BOOTMGR_FSTYPE=ext3
IL_LO_REPL_PART_BOOTMGR_SIZE=128
IL_LO_REPL_PART_BOOTMGR_GROWTHCAP=
IL_LO_REPL_PART_BOOTMGR_GROWTHWEIGHT=
IL_LO_REPL_PART_BOOTMGR_OPTIONS="defaults,noatime,ro"

IL_LO_REPL_PART_BOOT1_TARGET=DISK1
IL_LO_REPL_PART_BOOT1_PART_NUM=2
IL_LO_REPL_PART_BOOT1_DEV=${IL_LO_REPL_TARGET_DISK1_DEV}${IL_LO_REPL_PART_BOOT1_PART_NUM}
IL_LO_REPL_PART_BOOT1_LABEL=BOOT_1
IL_LO_REPL_PART_BOOT1_MOUNT=/boot
IL_LO_REPL_PART_BOOT1_BOOTABLE=
IL_LO_REPL_PART_BOOT1_PART_ID=83
IL_LO_REPL_PART_BOOT1_FSTYPE=ext3
IL_LO_REPL_PART_BOOT1_SIZE=128
IL_LO_REPL_PART_BOOT1_GROWTHCAP=
IL_LO_REPL_PART_BOOT1_GROWTHWEIGHT=
IL_LO_REPL_PART_BOOT1_OPTIONS="defaults,noatime,ro"

IL_LO_REPL_PART_BOOT2_TARGET=DISK1
IL_LO_REPL_PART_BOOT2_PART_NUM=3
IL_LO_REPL_PART_BOOT2_DEV=${IL_LO_REPL_TARGET_DISK1_DEV}${IL_LO_REPL_PART_BOOT2_PART_NUM}
IL_LO_REPL_PART_BOOT2_LABEL=BOOT_2
IL_LO_REPL_PART_BOOT2_MOUNT=/boot
IL_LO_REPL_PART_BOOT2_BOOTABLE=
IL_LO_REPL_PART_BOOT2_PART_ID=83
IL_LO_REPL_PART_BOOT2_FSTYPE=ext3
IL_LO_REPL_PART_BOOT2_SIZE=128
IL_LO_REPL_PART_BOOT2_GROWTHCAP=
IL_LO_REPL_PART_BOOT2_GROWTHWEIGHT=
IL_LO_REPL_PART_BOOT2_OPTIONS="defaults,noatime,ro"

IL_LO_REPL_PART_EXT_TARGET=DISK1
IL_LO_REPL_PART_EXT_PART_NUM=4
IL_LO_REPL_PART_EXT_DEV=${IL_LO_REPL_TARGET_DISK1_DEV}${IL_LO_REPL_PART_EXT_PART_NUM}
IL_LO_REPL_PART_EXT_LABEL=
IL_LO_REPL_PART_EXT_MOUNT=
IL_LO_REPL_PART_EXT_BOOTABLE=
IL_LO_REPL_PART_EXT_PART_ID=0f
IL_LO_REPL_PART_EXT_FSTYPE=
IL_LO_REPL_PART_EXT_SIZE=
IL_LO_REPL_PART_EXT_GROWTHCAP=
IL_LO_REPL_PART_EXT_GROWTHWEIGHT=

IL_LO_REPL_PART_ROOT1_TARGET=DISK1
IL_LO_REPL_PART_ROOT1_PART_NUM=5
IL_LO_REPL_PART_ROOT1_DEV=${IL_LO_REPL_TARGET_DISK1_DEV}${IL_LO_REPL_PART_ROOT1_PART_NUM}
IL_LO_REPL_PART_ROOT1_LABEL=ROOT_1
IL_LO_REPL_PART_ROOT1_MOUNT=/
IL_LO_REPL_PART_ROOT1_BOOTABLE=
IL_LO_REPL_PART_ROOT1_PART_ID=83
IL_LO_REPL_PART_ROOT1_FSTYPE=ext3
IL_LO_REPL_PART_ROOT1_SIZE=384
IL_LO_REPL_PART_ROOT1_GROWTHCAP=
IL_LO_REPL_PART_ROOT1_GROWTHWEIGHT=
IL_LO_REPL_PART_ROOT1_OPTIONS="defaults,noatime,ro"

IL_LO_REPL_PART_ROOT2_TARGET=DISK1
IL_LO_REPL_PART_ROOT2_PART_NUM=6
IL_LO_REPL_PART_ROOT2_DEV=${IL_LO_REPL_TARGET_DISK1_DEV}${IL_LO_REPL_PART_ROOT2_PART_NUM}
IL_LO_REPL_PART_ROOT2_LABEL=ROOT_2
IL_LO_REPL_PART_ROOT2_MOUNT=/
IL_LO_REPL_PART_ROOT2_BOOTABLE=
IL_LO_REPL_PART_ROOT2_PART_ID=83
IL_LO_REPL_PART_ROOT2_FSTYPE=ext3
IL_LO_REPL_PART_ROOT2_SIZE=384
IL_LO_REPL_PART_ROOT2_GROWTHCAP=
IL_LO_REPL_PART_ROOT2_GROWTHWEIGHT=
IL_LO_REPL_PART_ROOT2_OPTIONS="defaults,noatime,ro"

IL_LO_REPL_PART_SWAP_TARGET=DISK1
IL_LO_REPL_PART_SWAP_PART_NUM=7
IL_LO_REPL_PART_SWAP_DEV=${IL_LO_REPL_TARGET_DISK1_DEV}${IL_LO_REPL_PART_SWAP_PART_NUM}
IL_LO_REPL_PART_SWAP_LABEL=SWAP_1
IL_LO_REPL_PART_SWAP_MOUNT=swap
IL_LO_REPL_PART_SWAP_BOOTABLE=
IL_LO_REPL_PART_SWAP_PART_ID=82
IL_LO_REPL_PART_SWAP_FSTYPE=swap
IL_LO_REPL_PART_SWAP_SIZE=1024
IL_LO_REPL_PART_SWAP_GROWTHCAP=
IL_LO_REPL_PART_SWAP_GROWTHWEIGHT=

IL_LO_REPL_PART_CONFIG_TARGET=DISK1
IL_LO_REPL_PART_CONFIG_PART_NUM=8
IL_LO_REPL_PART_CONFIG_DEV=${IL_LO_REPL_TARGET_DISK1_DEV}${IL_LO_REPL_PART_CONFIG_PART_NUM}
IL_LO_REPL_PART_CONFIG_LABEL=CONFIG
IL_LO_REPL_PART_CONFIG_MOUNT=/config
IL_LO_REPL_PART_CONFIG_BOOTABLE=
IL_LO_REPL_PART_CONFIG_PART_ID=83
IL_LO_REPL_PART_CONFIG_FSTYPE=ext3
IL_LO_REPL_PART_CONFIG_SIZE=192
IL_LO_REPL_PART_CONFIG_GROWTHCAP=
IL_LO_REPL_PART_CONFIG_GROWTHWEIGHT=

IL_LO_REPL_PART_VAR_TARGET=DISK1
IL_LO_REPL_PART_VAR_PART_NUM=9
IL_LO_REPL_PART_VAR_DEV=${IL_LO_REPL_TARGET_DISK1_DEV}${IL_LO_REPL_PART_VAR_PART_NUM}
IL_LO_REPL_PART_VAR_LABEL=VAR
IL_LO_REPL_PART_VAR_MOUNT=/var
IL_LO_REPL_PART_VAR_BOOTABLE=
IL_LO_REPL_PART_VAR_PART_ID=83
IL_LO_REPL_PART_VAR_FSTYPE=ext3
IL_LO_REPL_PART_VAR_SIZE=1024
IL_LO_REPL_PART_VAR_GROWTHCAP=
IL_LO_REPL_PART_VAR_GROWTHWEIGHT=


IL_LO_REPL_PART_REPL_BOOTMGR_TARGET=DISK2
IL_LO_REPL_PART_REPL_BOOTMGR_PART_NUM=1
IL_LO_REPL_PART_REPL_BOOTMGR_DEV=${IL_LO_REPL_TARGET_DISK2_DEV}${IL_LO_REPL_PART_REPL_BOOTMGR_PART_NUM}
IL_LO_REPL_PART_REPL_BOOTMGR_LABEL=REPL_BOOTMGR
IL_LO_REPL_PART_REPL_BOOTMGR_MOUNT=/bootmgr
IL_LO_REPL_PART_REPL_BOOTMGR_BOOTABLE=1
IL_LO_REPL_PART_REPL_BOOTMGR_PART_ID=83
IL_LO_REPL_PART_REPL_BOOTMGR_FSTYPE=ext3
IL_LO_REPL_PART_REPL_BOOTMGR_SIZE=128
IL_LO_REPL_PART_REPL_BOOTMGR_GROWTHCAP=
IL_LO_REPL_PART_REPL_BOOTMGR_GROWTHWEIGHT=
IL_LO_REPL_PART_REPL_BOOTMGR_OPTIONS="defaults,noatime,ro"

IL_LO_REPL_PART_REPL_BOOT1_TARGET=DISK2
IL_LO_REPL_PART_REPL_BOOT1_PART_NUM=2
IL_LO_REPL_PART_REPL_BOOT1_DEV=${IL_LO_REPL_TARGET_DISK2_DEV}${IL_LO_REPL_PART_REPL_BOOT1_PART_NUM}
IL_LO_REPL_PART_REPL_BOOT1_LABEL=REPL_BOOT1
IL_LO_REPL_PART_REPL_BOOT1_MOUNT=/boot
IL_LO_REPL_PART_REPL_BOOT1_BOOTABLE=
IL_LO_REPL_PART_REPL_BOOT1_PART_ID=83
IL_LO_REPL_PART_REPL_BOOT1_FSTYPE=ext3
IL_LO_REPL_PART_REPL_BOOT1_SIZE=128
IL_LO_REPL_PART_REPL_BOOT1_GROWTHCAP=
IL_LO_REPL_PART_REPL_BOOT1_GROWTHWEIGHT=
IL_LO_REPL_PART_REPL_BOOT1_OPTIONS="defaults,noatime,ro"

IL_LO_REPL_PART_REPL_BOOT2_TARGET=DISK2
IL_LO_REPL_PART_REPL_BOOT2_PART_NUM=3
IL_LO_REPL_PART_REPL_BOOT2_DEV=${IL_LO_REPL_TARGET_DISK2_DEV}${IL_LO_REPL_PART_REPL_BOOT2_PART_NUM}
IL_LO_REPL_PART_REPL_BOOT2_LABEL=REPL_BOOT2
IL_LO_REPL_PART_REPL_BOOT2_MOUNT=/boot
IL_LO_REPL_PART_REPL_BOOT2_BOOTABLE=
IL_LO_REPL_PART_REPL_BOOT2_PART_ID=83
IL_LO_REPL_PART_REPL_BOOT2_FSTYPE=ext3
IL_LO_REPL_PART_REPL_BOOT2_SIZE=128
IL_LO_REPL_PART_REPL_BOOT2_GROWTHCAP=
IL_LO_REPL_PART_REPL_BOOT2_GROWTHWEIGHT=
IL_LO_REPL_PART_REPL_BOOT2_OPTIONS="defaults,noatime,ro"

IL_LO_REPL_PART_REPL_EXT_TARGET=DISK2
IL_LO_REPL_PART_REPL_EXT_PART_NUM=4
IL_LO_REPL_PART_REPL_EXT_DEV=${IL_LO_REPL_TARGET_DISK2_DEV}${IL_LO_REPL_PART_REPL_EXT_PART_NUM}
IL_LO_REPL_PART_REPL_EXT_LABEL=
IL_LO_REPL_PART_REPL_EXT_MOUNT=
IL_LO_REPL_PART_REPL_EXT_BOOTABLE=
IL_LO_REPL_PART_REPL_EXT_PART_ID=0f
IL_LO_REPL_PART_REPL_EXT_FSTYPE=
IL_LO_REPL_PART_REPL_EXT_SIZE=
IL_LO_REPL_PART_REPL_EXT_GROWTHCAP=
IL_LO_REPL_PART_REPL_EXT_GROWTHWEIGHT=

IL_LO_REPL_PART_REPL_ROOT1_TARGET=DISK2
IL_LO_REPL_PART_REPL_ROOT1_PART_NUM=5
IL_LO_REPL_PART_REPL_ROOT1_DEV=${IL_LO_REPL_TARGET_DISK2_DEV}${IL_LO_REPL_PART_REPL_ROOT1_PART_NUM}
IL_LO_REPL_PART_REPL_ROOT1_LABEL=REPL_ROOT1
IL_LO_REPL_PART_REPL_ROOT1_MOUNT=/
IL_LO_REPL_PART_REPL_ROOT1_BOOTABLE=
IL_LO_REPL_PART_REPL_ROOT1_PART_ID=83
IL_LO_REPL_PART_REPL_ROOT1_FSTYPE=ext3
IL_LO_REPL_PART_REPL_ROOT1_SIZE=384
IL_LO_REPL_PART_REPL_ROOT1_GROWTHCAP=
IL_LO_REPL_PART_REPL_ROOT1_GROWTHWEIGHT=
IL_LO_REPL_PART_REPL_ROOT1_OPTIONS="defaults,noatime,ro"

IL_LO_REPL_PART_REPL_ROOT2_TARGET=DISK2
IL_LO_REPL_PART_REPL_ROOT2_PART_NUM=6
IL_LO_REPL_PART_REPL_ROOT2_DEV=${IL_LO_REPL_TARGET_DISK2_DEV}${IL_LO_REPL_PART_REPL_ROOT2_PART_NUM}
IL_LO_REPL_PART_REPL_ROOT2_LABEL=REPL_ROOT2
IL_LO_REPL_PART_REPL_ROOT2_MOUNT=/
IL_LO_REPL_PART_REPL_ROOT2_BOOTABLE=
IL_LO_REPL_PART_REPL_ROOT2_PART_ID=83
IL_LO_REPL_PART_REPL_ROOT2_FSTYPE=ext3
IL_LO_REPL_PART_REPL_ROOT2_SIZE=384
IL_LO_REPL_PART_REPL_ROOT2_GROWTHCAP=
IL_LO_REPL_PART_REPL_ROOT2_GROWTHWEIGHT=
IL_LO_REPL_PART_REPL_ROOT2_OPTIONS="defaults,noatime,ro"

IL_LO_REPL_PART_REPL_SWAP_TARGET=DISK2
IL_LO_REPL_PART_REPL_SWAP_PART_NUM=7
IL_LO_REPL_PART_REPL_SWAP_DEV=${IL_LO_REPL_TARGET_DISK2_DEV}${IL_LO_REPL_PART_REPL_SWAP_PART_NUM}
IL_LO_REPL_PART_REPL_SWAP_LABEL=REPL_SWAP_1
IL_LO_REPL_PART_REPL_SWAP_MOUNT=swap
IL_LO_REPL_PART_REPL_SWAP_BOOTABLE=
IL_LO_REPL_PART_REPL_SWAP_PART_ID=82
IL_LO_REPL_PART_REPL_SWAP_FSTYPE=swap
IL_LO_REPL_PART_REPL_SWAP_SIZE=1024
IL_LO_REPL_PART_REPL_SWAP_GROWTHCAP=
IL_LO_REPL_PART_REPL_SWAP_GROWTHWEIGHT=

IL_LO_REPL_PART_REPL_CONFIG_TARGET=DISK2
IL_LO_REPL_PART_REPL_CONFIG_PART_NUM=8
IL_LO_REPL_PART_REPL_CONFIG_DEV=${IL_LO_REPL_TARGET_DISK2_DEV}${IL_LO_REPL_PART_REPL_CONFIG_PART_NUM}
IL_LO_REPL_PART_REPL_CONFIG_LABEL=REPL_CONFIG
IL_LO_REPL_PART_REPL_CONFIG_MOUNT=/config
IL_LO_REPL_PART_REPL_CONFIG_BOOTABLE=
IL_LO_REPL_PART_REPL_CONFIG_PART_ID=83
IL_LO_REPL_PART_REPL_CONFIG_FSTYPE=ext3
IL_LO_REPL_PART_REPL_CONFIG_SIZE=192
IL_LO_REPL_PART_REPL_CONFIG_GROWTHCAP=
IL_LO_REPL_PART_REPL_CONFIG_GROWTHWEIGHT=

IL_LO_REPL_PART_REPL_VAR_TARGET=DISK2
IL_LO_REPL_PART_REPL_VAR_PART_NUM=9
IL_LO_REPL_PART_REPL_VAR_DEV=${IL_LO_REPL_TARGET_DISK2_DEV}${IL_LO_REPL_PART_REPL_VAR_PART_NUM}
IL_LO_REPL_PART_REPL_VAR_LABEL=REPL_VAR
IL_LO_REPL_PART_REPL_VAR_MOUNT=/var
IL_LO_REPL_PART_REPL_VAR_BOOTABLE=
IL_LO_REPL_PART_REPL_VAR_PART_ID=83
IL_LO_REPL_PART_REPL_VAR_FSTYPE=ext3
IL_LO_REPL_PART_REPL_VAR_SIZE=1024
IL_LO_REPL_PART_REPL_VAR_GROWTHCAP=
IL_LO_REPL_PART_REPL_VAR_GROWTHWEIGHT=



# ==================================================
#
# Compact image layout
#
# ==================================================

# These are the standard location names.  They should not be changed
IL_LO_COMPACT_LOCS="BOOTMGR_1 BOOT_1 ROOT_1 SWAP_1 CONFIG_1 VAR_1 DATA_1"

# Targets are things like a disk or a flash device
IL_LO_COMPACT_TARGET_NUM_TARGETS=1
IL_LO_COMPACT_TARGETS="DISK1"
IL_LO_COMPACT_TARGET_DISK1_NUM=1

IL_LO_COMPACT_ROOT_RDONLY=1

IL_LO_COMPACT_TARGET_DISK1_MINSIZE=470

# What partitions get made on the targets
IL_LO_COMPACT_PARTS="BOOTMGR COMBINED DATA"

IL_LO_COMPACT_IMAGE_1_INSTALL_LOCS="BOOT_1 ROOT_1"
IL_LO_COMPACT_IMAGE_2_INSTALL_LOCS=
IL_LO_COMPACT_IMAGE_1_LOCS="ROOT_1 BOOT_1 BOOTMGR_1 VAR_1 CONFIG_1 DATA_1 SWAP_1"
IL_LO_COMPACT_IMAGE_2_LOCS=

IL_LO_COMPACT_OPT_LAST_PART_FILL=1


# Each of these says which PART (partition) below goes with which LOC
#     (standardized location) .  It also says for each LOC which subdirectory
#     under the PART the LOC is in, and what files to extract there

IL_LO_COMPACT_LOC_BOOTMGR_1_PART=BOOTMGR
IL_LO_COMPACT_LOC_BOOTMGR_1_DIR=/
IL_LO_COMPACT_LOC_BOOTMGR_1_IMAGE_EXTRACT="./bootmgr"
IL_LO_COMPACT_LOC_BOOTMGR_1_IMAGE_EXTRACT_PREFIX="/bootmgr"

IL_LO_COMPACT_LOC_BOOT_1_PART=COMBINED
IL_LO_COMPACT_LOC_BOOT_1_DIR=/boot/
IL_LO_COMPACT_LOC_BOOT_1_IMAGE_EXTRACT="./boot"
IL_LO_COMPACT_LOC_BOOT_1_IMAGE_EXTRACT_PREFIX=""

IL_LO_COMPACT_LOC_BOOT_2_PART=

IL_LO_COMPACT_LOC_ROOT_1_PART=COMBINED
IL_LO_COMPACT_LOC_ROOT_1_DIR=/
IL_LO_COMPACT_LOC_ROOT_1_IMAGE_EXTRACT="./"
IL_LO_COMPACT_LOC_ROOT_1_IMAGE_EXTRACT_EXCLUDE="./bootmgr ./boot ./var ./config"
IL_LO_COMPACT_LOC_ROOT_1_IMAGE_EXTRACT_PREFIX=""

IL_LO_COMPACT_LOC_ROOT_2_PART=

IL_LO_COMPACT_LOC_SWAP_1_PART=

IL_LO_COMPACT_LOC_VAR_1_PART=COMBINED
IL_LO_COMPACT_LOC_VAR_1_DIR=/var/
IL_LO_COMPACT_LOC_VAR_1_IMAGE_EXTRACT="./var"
IL_LO_COMPACT_LOC_VAR_1_IMAGE_EXTRACT_PREFIX="/"

IL_LO_COMPACT_LOC_CONFIG_1_PART=COMBINED
IL_LO_COMPACT_LOC_CONFIG_1_DIR=/config/
IL_LO_COMPACT_LOC_CONFIG_1_IMAGE_EXTRACT="./config"
IL_LO_COMPACT_LOC_CONFIG_1_IMAGE_EXTRACT_PREFIX="/"

IL_LO_COMPACT_LOC_DATA_1_PART=DATA
IL_LO_COMPACT_LOC_DATA_1_DIR=
IL_LO_COMPACT_LOC_DATA_1_IMAGE_EXTRACT=""
IL_LO_COMPACT_LOC_DATA_1_IMAGE_EXTRACT_PREFIX=""


# Each of these says how a partition is named, labled, and sized.

IL_LO_COMPACT_PART_BOOTMGR_TARGET=DISK1
IL_LO_COMPACT_PART_BOOTMGR_PART_NUM=1
IL_LO_COMPACT_PART_BOOTMGR_DEV=${IL_LO_COMPACT_TARGET_DISK1_DEV}${IL_LO_COMPACT_PART_BOOTMGR_PART_NUM}
IL_LO_COMPACT_PART_BOOTMGR_LABEL=BOOTMGR
IL_LO_COMPACT_PART_BOOTMGR_MOUNT=/bootmgr
IL_LO_COMPACT_PART_BOOTMGR_BOOTABLE=1
IL_LO_COMPACT_PART_BOOTMGR_PART_ID=83
IL_LO_COMPACT_PART_BOOTMGR_FSTYPE=ext3
IL_LO_COMPACT_PART_BOOTMGR_SIZE=17
IL_LO_COMPACT_PART_BOOTMGR_GROWTHCAP=
IL_LO_COMPACT_PART_BOOTMGR_GROWTHWEIGHT=
IL_LO_COMPACT_PART_BOOTMGR_OPTIONS="defaults,noatime,ro"

IL_LO_COMPACT_PART_COMBINED_TARGET=DISK1
IL_LO_COMPACT_PART_COMBINED_PART_NUM=2
IL_LO_COMPACT_PART_COMBINED_DEV=${IL_LO_COMPACT_TARGET_DISK1_DEV}${IL_LO_COMPACT_PART_COMBINED_PART_NUM}
IL_LO_COMPACT_PART_COMBINED_LABEL=COMBINED
IL_LO_COMPACT_PART_COMBINED_MOUNT=/
IL_LO_COMPACT_PART_COMBINED_BOOTABLE=
IL_LO_COMPACT_PART_COMBINED_PART_ID=83
IL_LO_COMPACT_PART_COMBINED_FSTYPE=ext3
IL_LO_COMPACT_PART_COMBINED_SIZE=273
IL_LO_COMPACT_PART_COMBINED_GROWTHCAP=
IL_LO_COMPACT_PART_COMBINED_GROWTHWEIGHT=
IL_LO_COMPACT_PART_COMBINED_OPTIONS="defaults,noatime,ro"

IL_LO_COMPACT_PART_DATA_TARGET=DISK1
IL_LO_COMPACT_PART_DATA_PART_NUM=3
IL_LO_COMPACT_PART_DATA_DEV=${IL_LO_COMPACT_TARGET_DISK1_DEV}${IL_LO_COMPACT_PART_DATA_PART_NUM}
IL_LO_COMPACT_PART_DATA_LABEL=
IL_LO_COMPACT_PART_DATA_MOUNT=
IL_LO_COMPACT_PART_DATA_BOOTABLE=
IL_LO_COMPACT_PART_DATA_PART_ID=da
IL_LO_COMPACT_PART_DATA_FSTYPE=
IL_LO_COMPACT_PART_DATA_SIZE=17
IL_LO_COMPACT_PART_DATA_GROWTHCAP=
IL_LO_COMPACT_PART_DATA_GROWTHWEIGHT=100

# ==================================================
#
# Small test layout: small sizes, may be suitable for usb/flash.  No swap.
#    Requires at least at 1G device.  See the notes above the FLASH layout
#    for why the 8*n+1 size per partition and the 950 MB total size.
#
# ==================================================

# These are the standard location names.  They should not be changed
IL_LO_SMALL_LOCS="BOOTMGR_1 BOOT_1 BOOT_2 ROOT_1 ROOT_2 CONFIG_1 VAR_1"

# Targets are things like a disk or a flash device
IL_LO_SMALL_TARGET_NUM_TARGETS=1
IL_LO_SMALL_TARGETS="DISK1"
IL_LO_SMALL_TARGET_DISK1_NUM=1

IL_LO_SMALL_ROOT_RDONLY=1

IL_LO_SMALL_TARGET_DISK1_MINSIZE=950

# What partitions get made on the targets
IL_LO_SMALL_PARTS="BOOTMGR BOOT1 BOOT2 EXT ROOT1 ROOT2 CONFIG VAR"

IL_LO_SMALL_IMAGE_1_INSTALL_LOCS="BOOT_1 ROOT_1"
IL_LO_SMALL_IMAGE_2_INSTALL_LOCS="BOOT_2 ROOT_2"
IL_LO_SMALL_IMAGE_1_LOCS="ROOT_1 BOOT_1 BOOTMGR_1 CONFIG_1 VAR_1"
IL_LO_SMALL_IMAGE_2_LOCS="ROOT_2 BOOT_2 BOOTMGR_1 CONFIG_1 VAR_1"

IL_LO_SMALL_OPT_LAST_PART_FILL=0

# Each of these says which PART (partition) below goes with which LOC
#     (standardized location) .  It also says for each LOC which subdirectory
#     under the PART the LOC is in, and what files to extract there


IL_LO_SMALL_LOC_BOOTMGR_1_PART=BOOTMGR
IL_LO_SMALL_LOC_BOOTMGR_1_DIR=/
IL_LO_SMALL_LOC_BOOTMGR_1_IMAGE_EXTRACT="./bootmgr"
IL_LO_SMALL_LOC_BOOTMGR_1_IMAGE_EXTRACT_PREFIX="/bootmgr"

IL_LO_SMALL_LOC_BOOT_1_PART=BOOT1
IL_LO_SMALL_LOC_BOOT_1_DIR=/
IL_LO_SMALL_LOC_BOOT_1_IMAGE_EXTRACT="./boot"
IL_LO_SMALL_LOC_BOOT_1_IMAGE_EXTRACT_PREFIX="/boot"

IL_LO_SMALL_LOC_BOOT_2_PART=BOOT2
IL_LO_SMALL_LOC_BOOT_2_DIR=/
IL_LO_SMALL_LOC_BOOT_2_IMAGE_EXTRACT="./boot"
IL_LO_SMALL_LOC_BOOT_2_IMAGE_EXTRACT_PREFIX="/boot"

IL_LO_SMALL_LOC_ROOT_1_PART=ROOT1
IL_LO_SMALL_LOC_ROOT_1_DIR=/
IL_LO_SMALL_LOC_ROOT_1_IMAGE_EXTRACT="./"
IL_LO_SMALL_LOC_ROOT_1_IMAGE_EXTRACT_EXCLUDE="./bootmgr ./boot ./config ./var"
IL_LO_SMALL_LOC_ROOT_1_IMAGE_EXTRACT_PREFIX=""

IL_LO_SMALL_LOC_ROOT_2_PART=ROOT2
IL_LO_SMALL_LOC_ROOT_2_DIR=/
IL_LO_SMALL_LOC_ROOT_2_IMAGE_EXTRACT="./"
IL_LO_SMALL_LOC_ROOT_2_IMAGE_EXTRACT_EXCLUDE="./bootmgr ./boot ./config ./var"
IL_LO_SMALL_LOC_ROOT_2_IMAGE_EXTRACT_PREFIX=""

IL_LO_SMALL_LOC_CONFIG_1_PART=CONFIG
IL_LO_SMALL_LOC_CONFIG_1_DIR=/
IL_LO_SMALL_LOC_CONFIG_1_IMAGE_EXTRACT="./config"
IL_LO_SMALL_LOC_CONFIG_1_IMAGE_EXTRACT_PREFIX="/config"

IL_LO_SMALL_LOC_VAR_1_PART=VAR
IL_LO_SMALL_LOC_VAR_1_DIR=/
IL_LO_SMALL_LOC_VAR_1_IMAGE_EXTRACT="./var"
IL_LO_SMALL_LOC_VAR_1_IMAGE_EXTRACT_PREFIX="/var"


# Each of these says how a partition is named, labled, and sized.

IL_LO_SMALL_PART_BOOTMGR_TARGET=DISK1
IL_LO_SMALL_PART_BOOTMGR_PART_NUM=1
IL_LO_SMALL_PART_BOOTMGR_DEV=${IL_LO_SMALL_TARGET_DISK1_DEV}${IL_LO_SMALL_PART_BOOTMGR_PART_NUM}
IL_LO_SMALL_PART_BOOTMGR_LABEL=BOOTMGR
IL_LO_SMALL_PART_BOOTMGR_MOUNT=/bootmgr
IL_LO_SMALL_PART_BOOTMGR_BOOTABLE=1
IL_LO_SMALL_PART_BOOTMGR_PART_ID=83
IL_LO_SMALL_PART_BOOTMGR_FSTYPE=ext3
IL_LO_SMALL_PART_BOOTMGR_SIZE=17
IL_LO_SMALL_PART_BOOTMGR_GROWTHCAP=
IL_LO_SMALL_PART_BOOTMGR_GROWTHWEIGHT=
IL_LO_SMALL_PART_BOOTMGR_OPTIONS="defaults,noatime,ro"

IL_LO_SMALL_PART_BOOT1_TARGET=DISK1
IL_LO_SMALL_PART_BOOT1_PART_NUM=2
IL_LO_SMALL_PART_BOOT1_DEV=${IL_LO_SMALL_TARGET_DISK1_DEV}${IL_LO_SMALL_PART_BOOT1_PART_NUM}
IL_LO_SMALL_PART_BOOT1_LABEL=BOOT_1
IL_LO_SMALL_PART_BOOT1_MOUNT=/boot
IL_LO_SMALL_PART_BOOT1_BOOTABLE=
IL_LO_SMALL_PART_BOOT1_PART_ID=83
IL_LO_SMALL_PART_BOOT1_FSTYPE=ext3
IL_LO_SMALL_PART_BOOT1_SIZE=17
IL_LO_SMALL_PART_BOOT1_GROWTHCAP=
IL_LO_SMALL_PART_BOOT1_GROWTHWEIGHT=
IL_LO_SMALL_PART_BOOT1_OPTIONS="defaults,noatime,ro"

IL_LO_SMALL_PART_BOOT2_TARGET=DISK1
IL_LO_SMALL_PART_BOOT2_PART_NUM=3
IL_LO_SMALL_PART_BOOT2_DEV=${IL_LO_SMALL_TARGET_DISK1_DEV}${IL_LO_SMALL_PART_BOOT2_PART_NUM}
IL_LO_SMALL_PART_BOOT2_LABEL=BOOT_2
IL_LO_SMALL_PART_BOOT2_MOUNT=/boot
IL_LO_SMALL_PART_BOOT2_BOOTABLE=
IL_LO_SMALL_PART_BOOT2_PART_ID=83
IL_LO_SMALL_PART_BOOT2_FSTYPE=ext3
IL_LO_SMALL_PART_BOOT2_SIZE=17
IL_LO_SMALL_PART_BOOT2_GROWTHCAP=
IL_LO_SMALL_PART_BOOT2_GROWTHWEIGHT=
IL_LO_SMALL_PART_BOOT2_OPTIONS="defaults,noatime,ro"

IL_LO_SMALL_PART_EXT_TARGET=DISK1
IL_LO_SMALL_PART_EXT_PART_NUM=4
IL_LO_SMALL_PART_EXT_DEV=${IL_LO_SMALL_TARGET_DISK1_DEV}${IL_LO_SMALL_PART_EXT_PART_NUM}
IL_LO_SMALL_PART_EXT_LABEL=
IL_LO_SMALL_PART_EXT_MOUNT=
IL_LO_SMALL_PART_EXT_BOOTABLE=
IL_LO_SMALL_PART_EXT_PART_ID=0f
IL_LO_SMALL_PART_EXT_FSTYPE=
IL_LO_SMALL_PART_EXT_SIZE=
IL_LO_SMALL_PART_EXT_GROWTHCAP=
IL_LO_SMALL_PART_EXT_GROWTHWEIGHT=

IL_LO_SMALL_PART_ROOT1_TARGET=DISK1
IL_LO_SMALL_PART_ROOT1_PART_NUM=5
IL_LO_SMALL_PART_ROOT1_DEV=${IL_LO_SMALL_TARGET_DISK1_DEV}${IL_LO_SMALL_PART_ROOT1_PART_NUM}
IL_LO_SMALL_PART_ROOT1_LABEL=ROOT_1
IL_LO_SMALL_PART_ROOT1_MOUNT=/
IL_LO_SMALL_PART_ROOT1_BOOTABLE=
IL_LO_SMALL_PART_ROOT1_PART_ID=83
IL_LO_SMALL_PART_ROOT1_FSTYPE=ext3
IL_LO_SMALL_PART_ROOT1_SIZE=257
IL_LO_SMALL_PART_ROOT1_GROWTHCAP=
IL_LO_SMALL_PART_ROOT1_GROWTHWEIGHT=
IL_LO_SMALL_PART_ROOT1_OPTIONS="defaults,noatime,ro"

IL_LO_SMALL_PART_ROOT2_TARGET=DISK1
IL_LO_SMALL_PART_ROOT2_PART_NUM=6
IL_LO_SMALL_PART_ROOT2_DEV=${IL_LO_SMALL_TARGET_DISK1_DEV}${IL_LO_SMALL_PART_ROOT2_PART_NUM}
IL_LO_SMALL_PART_ROOT2_LABEL=ROOT_2
IL_LO_SMALL_PART_ROOT2_MOUNT=/
IL_LO_SMALL_PART_ROOT2_BOOTABLE=
IL_LO_SMALL_PART_ROOT2_PART_ID=83
IL_LO_SMALL_PART_ROOT2_FSTYPE=ext3
IL_LO_SMALL_PART_ROOT2_SIZE=257
IL_LO_SMALL_PART_ROOT2_GROWTHCAP=
IL_LO_SMALL_PART_ROOT2_GROWTHWEIGHT=
IL_LO_SMALL_PART_ROOT2_OPTIONS="defaults,noatime,ro"

IL_LO_SMALL_PART_CONFIG_TARGET=DISK1
IL_LO_SMALL_PART_CONFIG_PART_NUM=7
IL_LO_SMALL_PART_CONFIG_DEV=${IL_LO_SMALL_TARGET_DISK1_DEV}${IL_LO_SMALL_PART_CONFIG_PART_NUM}
IL_LO_SMALL_PART_CONFIG_LABEL=CONFIG
IL_LO_SMALL_PART_CONFIG_MOUNT=/config
IL_LO_SMALL_PART_CONFIG_BOOTABLE=
IL_LO_SMALL_PART_CONFIG_PART_ID=83
IL_LO_SMALL_PART_CONFIG_FSTYPE=ext3
IL_LO_SMALL_PART_CONFIG_SIZE=17
IL_LO_SMALL_PART_CONFIG_GROWTHCAP=
IL_LO_SMALL_PART_CONFIG_GROWTHWEIGHT=

IL_LO_SMALL_PART_VAR_TARGET=DISK1
IL_LO_SMALL_PART_VAR_PART_NUM=8
IL_LO_SMALL_PART_VAR_DEV=${IL_LO_SMALL_TARGET_DISK1_DEV}${IL_LO_SMALL_PART_VAR_PART_NUM}
IL_LO_SMALL_PART_VAR_LABEL=VAR
IL_LO_SMALL_PART_VAR_MOUNT=/var
IL_LO_SMALL_PART_VAR_BOOTABLE=
IL_LO_SMALL_PART_VAR_PART_ID=83
IL_LO_SMALL_PART_VAR_FSTYPE=ext3
IL_LO_SMALL_PART_VAR_SIZE=337
IL_LO_SMALL_PART_VAR_GROWTHCAP=
IL_LO_SMALL_PART_VAR_GROWTHWEIGHT=

# ==================================================
#
# Standard two image layout, but with an extra shared DATA partition
#
# ==================================================

# These are the standard location names.  They should not be changed
IL_LO_SDATA_LOCS="BOOTMGR_1 BOOT_1 BOOT_2 ROOT_1 ROOT_2 SWAP_1 CONFIG_1 \
    VAR_1 DATA_1"

# Targets are things like a disk or a flash device
IL_LO_SDATA_TARGET_NUM_TARGETS=1
IL_LO_SDATA_TARGETS="DISK1"
IL_LO_SDATA_TARGET_DISK1_NUM=1

IL_LO_SDATA_ROOT_RDONLY=1

IL_LO_SDATA_TARGET_DISK1_MINSIZE=4000

# What partitions get made on the targets
IL_LO_SDATA_PARTS="BOOTMGR BOOT1 BOOT2 EXT ROOT1 ROOT2 SWAP CONFIG VAR DATA"

IL_LO_SDATA_IMAGE_1_INSTALL_LOCS="BOOT_1 ROOT_1"
IL_LO_SDATA_IMAGE_2_INSTALL_LOCS="BOOT_2 ROOT_2"
IL_LO_SDATA_IMAGE_1_LOCS="ROOT_1 BOOT_1 BOOTMGR_1 CONFIG_1 VAR_1 DATA_1 SWAP_1"
IL_LO_SDATA_IMAGE_2_LOCS="ROOT_2 BOOT_2 BOOTMGR_1 CONFIG_1 VAR_1 DATA_1 SWAP_1"

IL_LO_SDATA_OPT_LAST_PART_FILL=1

IL_LO_SDATA_LOC_BOOTMGR_1_PART=BOOTMGR
IL_LO_SDATA_LOC_BOOTMGR_1_DIR=/
IL_LO_SDATA_LOC_BOOTMGR_1_IMAGE_EXTRACT="./bootmgr"
IL_LO_SDATA_LOC_BOOTMGR_1_IMAGE_EXTRACT_PREFIX="/bootmgr"

IL_LO_SDATA_LOC_BOOT_1_PART=BOOT1
IL_LO_SDATA_LOC_BOOT_1_DIR=/
IL_LO_SDATA_LOC_BOOT_1_IMAGE_EXTRACT="./boot"
IL_LO_SDATA_LOC_BOOT_1_IMAGE_EXTRACT_PREFIX="/boot"

IL_LO_SDATA_LOC_BOOT_2_PART=BOOT2
IL_LO_SDATA_LOC_BOOT_2_DIR=/
IL_LO_SDATA_LOC_BOOT_2_IMAGE_EXTRACT="./boot"
IL_LO_SDATA_LOC_BOOT_2_IMAGE_EXTRACT_PREFIX="/boot"

IL_LO_SDATA_LOC_ROOT_1_PART=ROOT1
IL_LO_SDATA_LOC_ROOT_1_DIR=/
IL_LO_SDATA_LOC_ROOT_1_IMAGE_EXTRACT="./"
IL_LO_SDATA_LOC_ROOT_1_IMAGE_EXTRACT_EXCLUDE="./bootmgr ./boot ./config ./var ./data"
IL_LO_SDATA_LOC_ROOT_1_IMAGE_EXTRACT_PREFIX=""

IL_LO_SDATA_LOC_ROOT_2_PART=ROOT2
IL_LO_SDATA_LOC_ROOT_2_DIR=/
IL_LO_SDATA_LOC_ROOT_2_IMAGE_EXTRACT="./"
IL_LO_SDATA_LOC_ROOT_2_IMAGE_EXTRACT_EXCLUDE="./bootmgr ./boot ./config ./var ./data"
IL_LO_SDATA_LOC_ROOT_2_IMAGE_EXTRACT_PREFIX=""

IL_LO_SDATA_LOC_SWAP_1_PART=SWAP
IL_LO_SDATA_LOC_SWAP_1_DIR=
IL_LO_SDATA_LOC_SWAP_1_IMAGE_EXTRACT=""
IL_LO_SDATA_LOC_SWAP_1_IMAGE_EXTRACT_PREFIX=""

IL_LO_SDATA_LOC_CONFIG_1_PART=CONFIG
IL_LO_SDATA_LOC_CONFIG_1_DIR=/
IL_LO_SDATA_LOC_CONFIG_1_IMAGE_EXTRACT="./config"
IL_LO_SDATA_LOC_CONFIG_1_IMAGE_EXTRACT_PREFIX="/config"

IL_LO_SDATA_LOC_VAR_1_PART=VAR
IL_LO_SDATA_LOC_VAR_1_DIR=/
IL_LO_SDATA_LOC_VAR_1_IMAGE_EXTRACT="./var"
IL_LO_SDATA_LOC_VAR_1_IMAGE_EXTRACT_PREFIX="/var"

IL_LO_SDATA_LOC_DATA_1_PART=DATA
IL_LO_SDATA_LOC_DATA_1_DIR=/
IL_LO_SDATA_LOC_DATA_1_IMAGE_EXTRACT="./data"
IL_LO_SDATA_LOC_DATA_1_IMAGE_EXTRACT_PREFIX="/data"


# Each of these says how a partition is named, labled, and sized.

IL_LO_SDATA_PART_BOOTMGR_TARGET=DISK1
IL_LO_SDATA_PART_BOOTMGR_PART_NUM=1
IL_LO_SDATA_PART_BOOTMGR_DEV=${IL_LO_SDATA_TARGET_DISK1_DEV}${IL_LO_SDATA_PART_BOOTMGR_PART_NUM}
IL_LO_SDATA_PART_BOOTMGR_LABEL=BOOTMGR
IL_LO_SDATA_PART_BOOTMGR_MOUNT=/bootmgr
IL_LO_SDATA_PART_BOOTMGR_BOOTABLE=1
IL_LO_SDATA_PART_BOOTMGR_PART_ID=83
IL_LO_SDATA_PART_BOOTMGR_FSTYPE=ext3
IL_LO_SDATA_PART_BOOTMGR_SIZE=128
IL_LO_SDATA_PART_BOOTMGR_GROWTHCAP=
IL_LO_SDATA_PART_BOOTMGR_GROWTHWEIGHT=
IL_LO_SDATA_PART_BOOTMGR_OPTIONS="defaults,noatime,ro"

IL_LO_SDATA_PART_BOOT1_TARGET=DISK1
IL_LO_SDATA_PART_BOOT1_PART_NUM=2
IL_LO_SDATA_PART_BOOT1_DEV=${IL_LO_SDATA_TARGET_DISK1_DEV}${IL_LO_SDATA_PART_BOOT1_PART_NUM}
IL_LO_SDATA_PART_BOOT1_LABEL=BOOT_1
IL_LO_SDATA_PART_BOOT1_MOUNT=/boot
IL_LO_SDATA_PART_BOOT1_BOOTABLE=
IL_LO_SDATA_PART_BOOT1_PART_ID=83
IL_LO_SDATA_PART_BOOT1_FSTYPE=ext3
IL_LO_SDATA_PART_BOOT1_SIZE=128
IL_LO_SDATA_PART_BOOT1_GROWTHCAP=
IL_LO_SDATA_PART_BOOT1_GROWTHWEIGHT=
IL_LO_SDATA_PART_BOOT1_OPTIONS="defaults,noatime,ro"

IL_LO_SDATA_PART_BOOT2_TARGET=DISK1
IL_LO_SDATA_PART_BOOT2_PART_NUM=3
IL_LO_SDATA_PART_BOOT2_DEV=${IL_LO_SDATA_TARGET_DISK1_DEV}${IL_LO_SDATA_PART_BOOT2_PART_NUM}
IL_LO_SDATA_PART_BOOT2_LABEL=BOOT_2
IL_LO_SDATA_PART_BOOT2_MOUNT=/boot
IL_LO_SDATA_PART_BOOT2_BOOTABLE=
IL_LO_SDATA_PART_BOOT2_PART_ID=83
IL_LO_SDATA_PART_BOOT2_FSTYPE=ext3
IL_LO_SDATA_PART_BOOT2_SIZE=128
IL_LO_SDATA_PART_BOOT2_GROWTHCAP=
IL_LO_SDATA_PART_BOOT2_GROWTHWEIGHT=
IL_LO_SDATA_PART_BOOT2_OPTIONS="defaults,noatime,ro"

IL_LO_SDATA_PART_EXT_TARGET=DISK1
IL_LO_SDATA_PART_EXT_PART_NUM=4
IL_LO_SDATA_PART_EXT_DEV=${IL_LO_SDATA_TARGET_DISK1_DEV}${IL_LO_SDATA_PART_EXT_PART_NUM}
IL_LO_SDATA_PART_EXT_LABEL=
IL_LO_SDATA_PART_EXT_MOUNT=
IL_LO_SDATA_PART_EXT_BOOTABLE=
IL_LO_SDATA_PART_EXT_PART_ID=0f
IL_LO_SDATA_PART_EXT_FSTYPE=
IL_LO_SDATA_PART_EXT_SIZE=
IL_LO_SDATA_PART_EXT_GROWTHCAP=
IL_LO_SDATA_PART_EXT_GROWTHWEIGHT=

IL_LO_SDATA_PART_ROOT1_TARGET=DISK1
IL_LO_SDATA_PART_ROOT1_PART_NUM=5
IL_LO_SDATA_PART_ROOT1_DEV=${IL_LO_SDATA_TARGET_DISK1_DEV}${IL_LO_SDATA_PART_ROOT1_PART_NUM}
IL_LO_SDATA_PART_ROOT1_LABEL=ROOT_1
IL_LO_SDATA_PART_ROOT1_MOUNT=/
IL_LO_SDATA_PART_ROOT1_BOOTABLE=
IL_LO_SDATA_PART_ROOT1_PART_ID=83
IL_LO_SDATA_PART_ROOT1_FSTYPE=ext3
IL_LO_SDATA_PART_ROOT1_SIZE=640
IL_LO_SDATA_PART_ROOT1_GROWTHCAP=
IL_LO_SDATA_PART_ROOT1_GROWTHWEIGHT=
IL_LO_SDATA_PART_ROOT1_OPTIONS="defaults,noatime,ro"

IL_LO_SDATA_PART_ROOT2_TARGET=DISK1
IL_LO_SDATA_PART_ROOT2_PART_NUM=6
IL_LO_SDATA_PART_ROOT2_DEV=${IL_LO_SDATA_TARGET_DISK1_DEV}${IL_LO_SDATA_PART_ROOT2_PART_NUM}
IL_LO_SDATA_PART_ROOT2_LABEL=ROOT_2
IL_LO_SDATA_PART_ROOT2_MOUNT=/
IL_LO_SDATA_PART_ROOT2_BOOTABLE=
IL_LO_SDATA_PART_ROOT2_PART_ID=83
IL_LO_SDATA_PART_ROOT2_FSTYPE=ext3
IL_LO_SDATA_PART_ROOT2_SIZE=640
IL_LO_SDATA_PART_ROOT2_GROWTHCAP=
IL_LO_SDATA_PART_ROOT2_GROWTHWEIGHT=
IL_LO_SDATA_PART_ROOT2_OPTIONS="defaults,noatime,ro"

IL_LO_SDATA_PART_SWAP_TARGET=DISK1
IL_LO_SDATA_PART_SWAP_PART_NUM=7
IL_LO_SDATA_PART_SWAP_DEV=${IL_LO_SDATA_TARGET_DISK1_DEV}${IL_LO_SDATA_PART_SWAP_PART_NUM}
IL_LO_SDATA_PART_SWAP_LABEL=SWAP_1
IL_LO_SDATA_PART_SWAP_MOUNT=swap
IL_LO_SDATA_PART_SWAP_BOOTABLE=
IL_LO_SDATA_PART_SWAP_PART_ID=82
IL_LO_SDATA_PART_SWAP_FSTYPE=swap
IL_LO_SDATA_PART_SWAP_SIZE=1024
IL_LO_SDATA_PART_SWAP_GROWTHCAP=
IL_LO_SDATA_PART_SWAP_GROWTHWEIGHT=

IL_LO_SDATA_PART_CONFIG_TARGET=DISK1
IL_LO_SDATA_PART_CONFIG_PART_NUM=8
IL_LO_SDATA_PART_CONFIG_DEV=${IL_LO_SDATA_TARGET_DISK1_DEV}${IL_LO_SDATA_PART_CONFIG_PART_NUM}
IL_LO_SDATA_PART_CONFIG_LABEL=CONFIG
IL_LO_SDATA_PART_CONFIG_MOUNT=/config
IL_LO_SDATA_PART_CONFIG_BOOTABLE=
IL_LO_SDATA_PART_CONFIG_PART_ID=83
IL_LO_SDATA_PART_CONFIG_FSTYPE=ext3
IL_LO_SDATA_PART_CONFIG_SIZE=192
IL_LO_SDATA_PART_CONFIG_GROWTHCAP=
IL_LO_SDATA_PART_CONFIG_GROWTHWEIGHT=

IL_LO_SDATA_PART_VAR_TARGET=DISK1
IL_LO_SDATA_PART_VAR_PART_NUM=9
IL_LO_SDATA_PART_VAR_DEV=${IL_LO_SDATA_TARGET_DISK1_DEV}${IL_LO_SDATA_PART_VAR_PART_NUM}
IL_LO_SDATA_PART_VAR_LABEL=VAR
IL_LO_SDATA_PART_VAR_MOUNT=/var
IL_LO_SDATA_PART_VAR_BOOTABLE=
IL_LO_SDATA_PART_VAR_PART_ID=83
IL_LO_SDATA_PART_VAR_FSTYPE=ext3
IL_LO_SDATA_PART_VAR_SIZE=1024
IL_LO_SDATA_PART_VAR_GROWTHCAP=8192
IL_LO_SDATA_PART_VAR_GROWTHWEIGHT=

IL_LO_SDATA_PART_DATA_TARGET=DISK1
IL_LO_SDATA_PART_DATA_PART_NUM=10
IL_LO_SDATA_PART_DATA_DEV=${IL_LO_SDATA_TARGET_DISK1_DEV}${IL_LO_SDATA_PART_DATA_PART_NUM}
IL_LO_SDATA_PART_DATA_LABEL=DATA
IL_LO_SDATA_PART_DATA_MOUNT=/data
IL_LO_SDATA_PART_DATA_BOOTABLE=
IL_LO_SDATA_PART_DATA_PART_ID=83
IL_LO_SDATA_PART_DATA_FSTYPE=ext3
IL_LO_SDATA_PART_DATA_SIZE=1024
IL_LO_SDATA_PART_DATA_GROWTHCAP=
IL_LO_SDATA_PART_DATA_GROWTHWEIGHT=

# ==================================================
#
# Flash only (with virtual root fs) image layout
#
# ***********************************************************
# *** CAUTION: THIS LAYOUT IS NOT WORKING -- DO NOT USE!! ***
# ***********************************************************
#
# ==================================================

# These are the standard location names.  They should not be changed
IL_LO_VFLASH_LOCS="BOOTMGR_1 BOOT_1 BOOT_2 ROOT_1 ROOT_2 CONFIG_1 VAR_1 \
    VIMAGES_1"

# Targets are things like a disk or a flash device
IL_LO_VFLASH_TARGET_NUM_TARGETS=1
IL_LO_VFLASH_TARGETS="VFLASH1"
IL_LO_VFLASH_TARGET_VFLASH1_NUM=1

# Special arguments for kernel grub line to deal with possible
# flash device issues
IL_LO_VFLASH_EXTRA_KERNEL_PARAMS="ide=nodma"

# Configuration option to indicate that the root locations
# should be read-only. It is still necessary to indicate
# 'ro' in the partition option line for root.
IL_LO_VFLASH_ROOT_RDONLY=1

# XXX Would really like this to be smaller, but need root fs image
# to be compressed
IL_LO_VFLASH_TARGET_VFLASH1_MINSIZE=512

# What partitions get made on the targets
IL_LO_VFLASH_PARTS="BOOTMGR BOOT1 BOOT2 EXT CONFIG VPARTIMAGES"
# What virtual partitions are created into a tmpfs and backed
# by a physical partition
IL_LO_VFLASH_VPARTS="ROOT1 ROOT2 VAR"

IL_LO_VFLASH_IMAGE_1_INSTALL_LOCS="BOOT_1 ROOT_1"
IL_LO_VFLASH_IMAGE_2_INSTALL_LOCS="BOOT_2 ROOT_2"
IL_LO_VFLASH_IMAGE_1_LOCS="ROOT_1 BOOT_1 BOOTMGR_1 CONFIG_1 VAR_1 VIMAGES_1"
IL_LO_VFLASH_IMAGE_2_LOCS="ROOT_2 BOOT_2 BOOTMGR_1 CONFIG_1 VAR_1 VIMAGES_1"

# XXX In two disk case how can we fill each 'last' partition?
IL_LO_VFLASH_OPT_LAST_PART_FILL=0


# Each of these says which PART (partition) or VPART (virtual partition)
#     below goes with which LOC (standardized location) .  It also says for
#     each LOC which subdirectory under the PART/VPART the LOC is in, and
#     what files to extract there

IL_LO_VFLASH_LOC_BOOTMGR_1_PART=BOOTMGR
IL_LO_VFLASH_LOC_BOOTMGR_1_DIR=/
IL_LO_VFLASH_LOC_BOOTMGR_1_IMAGE_EXTRACT="./bootmgr"
IL_LO_VFLASH_LOC_BOOTMGR_1_IMAGE_EXTRACT_PREFIX="/bootmgr"

IL_LO_VFLASH_LOC_BOOT_1_PART=BOOT1
IL_LO_VFLASH_LOC_BOOT_1_DIR=/
IL_LO_VFLASH_LOC_BOOT_1_IMAGE_EXTRACT="./boot"
IL_LO_VFLASH_LOC_BOOT_1_IMAGE_EXTRACT_PREFIX="/boot"

IL_LO_VFLASH_LOC_BOOT_2_PART=BOOT2
IL_LO_VFLASH_LOC_BOOT_2_DIR=/
IL_LO_VFLASH_LOC_BOOT_2_IMAGE_EXTRACT="./boot"
IL_LO_VFLASH_LOC_BOOT_2_IMAGE_EXTRACT_PREFIX="/boot"

IL_LO_VFLASH_LOC_ROOT_1_VPART=ROOT1
IL_LO_VFLASH_LOC_ROOT_1_DIR=/
IL_LO_VFLASH_LOC_ROOT_1_IMAGE_EXTRACT="./"
IL_LO_VFLASH_LOC_ROOT_1_IMAGE_EXTRACT_EXCLUDE="./bootmgr ./boot ./var ./config"
IL_LO_VFLASH_LOC_ROOT_1_IMAGE_EXTRACT_PREFIX=""
IL_LO_VFLASH_LOC_ROOT_1_IMAGE_EXTRA_MOUNTS="./vpart_images"

IL_LO_VFLASH_LOC_ROOT_2_VPART=ROOT2
IL_LO_VFLASH_LOC_ROOT_2_DIR=/
IL_LO_VFLASH_LOC_ROOT_2_IMAGE_EXTRACT="./"
IL_LO_VFLASH_LOC_ROOT_2_IMAGE_EXTRACT_EXCLUDE="./bootmgr ./boot ./var ./config"
IL_LO_VFLASH_LOC_ROOT_2_IMAGE_EXTRACT_PREFIX=""
IL_LO_VFLASH_LOC_ROOT_2_IMAGE_EXTRA_MOUNTS="./vpart_images"

IL_LO_VFLASH_LOC_VAR_1_VPART=VAR
IL_LO_VFLASH_LOC_VAR_1_DIR=/var/
IL_LO_VFLASH_LOC_VAR_1_IMAGE_EXTRACT="./var"
IL_LO_VFLASH_LOC_VAR_1_IMAGE_EXTRACT_PREFIX="/var"

IL_LO_VFLASH_LOC_CONFIG_1_PART=CONFIG
IL_LO_VFLASH_LOC_CONFIG_1_DIR=/config/
IL_LO_VFLASH_LOC_CONFIG_1_IMAGE_EXTRACT="./config"
IL_LO_VFLASH_LOC_CONFIG_1_IMAGE_EXTRACT_PREFIX="/config"

IL_LO_VFLASH_LOC_VIMAGES_1_PART=VPARTIMAGES
IL_LO_VFLASH_LOC_VIMAGES_1_DIR=/
IL_LO_VFLASH_LOC_VIMAGES_1_IMAGE_EXTRACT=

IL_LO_VFLASH_LOC_SWAP_1_PART=

# XXX If Swap were desired for VFLASH
# IL_LO_VFLASH_LOC_SWAP_1_PART=SWAP
# IL_LO_VFLASH_LOC_SWAP_1_DIR=
# IL_LO_VFLASH_LOC_SWAP_1_IMAGE_EXTRACT=""
# IL_LO_VFLASH_LOC_SWAP_1_IMAGE_EXTRACT_PREFIX=""

# Each of these says how a partition is named, labled, and sized.

IL_LO_VFLASH_PART_BOOTMGR_TARGET=VFLASH1
IL_LO_VFLASH_PART_BOOTMGR_PART_NUM=1
IL_LO_VFLASH_PART_BOOTMGR_DEV=${IL_LO_VFLASH_TARGET_VFLASH1_DEV}${IL_LO_VFLASH_PART_BOOTMGR_PART_NUM}
IL_LO_VFLASH_PART_BOOTMGR_LABEL=BOOTMGR
IL_LO_VFLASH_PART_BOOTMGR_MOUNT=/bootmgr
IL_LO_VFLASH_PART_BOOTMGR_BOOTABLE=1
IL_LO_VFLASH_PART_BOOTMGR_PART_ID=83
IL_LO_VFLASH_PART_BOOTMGR_FSTYPE=ext3
IL_LO_VFLASH_PART_BOOTMGR_SIZE=17
IL_LO_VFLASH_PART_BOOTMGR_GROWTHCAP=
IL_LO_VFLASH_PART_BOOTMGR_GROWTHWEIGHT=
IL_LO_VFLASH_PART_BOOTMGR_OPTIONS="defaults,noatime,ro"

IL_LO_VFLASH_PART_BOOT1_TARGET=VFLASH1
IL_LO_VFLASH_PART_BOOT1_PART_NUM=2
IL_LO_VFLASH_PART_BOOT1_DEV=${IL_LO_VFLASH_TARGET_VFLASH1_DEV}${IL_LO_VFLASH_PART_BOOT1_PART_NUM}
IL_LO_VFLASH_PART_BOOT1_LABEL=BOOT1
IL_LO_VFLASH_PART_BOOT1_MOUNT=/boot
IL_LO_VFLASH_PART_BOOT1_BOOTABLE=
IL_LO_VFLASH_PART_BOOT1_PART_ID=83
IL_LO_VFLASH_PART_BOOT1_FSTYPE=ext3
IL_LO_VFLASH_PART_BOOT1_SIZE=17
IL_LO_VFLASH_PART_BOOT1_GROWTHCAP=
IL_LO_VFLASH_PART_BOOT1_GROWTHWEIGHT=
IL_LO_VFLASH_PART_BOOT1_OPTIONS="defaults,noatime,ro"

IL_LO_VFLASH_PART_BOOT2_TARGET=VFLASH1
IL_LO_VFLASH_PART_BOOT2_PART_NUM=3
IL_LO_VFLASH_PART_BOOT2_DEV=${IL_LO_VFLASH_TARGET_VFLASH1_DEV}${IL_LO_VFLASH_PART_BOOT2_PART_NUM}
IL_LO_VFLASH_PART_BOOT2_LABEL=BOOT2
IL_LO_VFLASH_PART_BOOT2_MOUNT=/boot
IL_LO_VFLASH_PART_BOOT2_BOOTABLE=
IL_LO_VFLASH_PART_BOOT2_PART_ID=83
IL_LO_VFLASH_PART_BOOT2_FSTYPE=ext3
IL_LO_VFLASH_PART_BOOT2_SIZE=17
IL_LO_VFLASH_PART_BOOT2_GROWTHCAP=
IL_LO_VFLASH_PART_BOOT2_GROWTHWEIGHT=
IL_LO_VFLASH_PART_BOOT2_OPTIONS="defaults,noatime,ro"

IL_LO_VFLASH_PART_EXT_TARGET=VFLASH1
IL_LO_VFLASH_PART_EXT_PART_NUM=4
IL_LO_VFLASH_PART_EXT_DEV=${IL_LO_VFLASH_TARGET_VFLASH1_DEV}${IL_LO_VFLASH_PART_EXT_PART_NUM}
IL_LO_VFLASH_PART_EXT_LABEL=
IL_LO_VFLASH_PART_EXT_MOUNT=
IL_LO_VFLASH_PART_EXT_BOOTABLE=
IL_LO_VFLASH_PART_EXT_PART_ID=0f
IL_LO_VFLASH_PART_EXT_FSTYPE=
IL_LO_VFLASH_PART_EXT_SIZE=
IL_LO_VFLASH_PART_EXT_GROWTHCAP=
IL_LO_VFLASH_PART_EXT_GROWTHWEIGHT=

IL_LO_VFLASH_PART_CONFIG_TARGET=VFLASH1
IL_LO_VFLASH_PART_CONFIG_PART_NUM=5
IL_LO_VFLASH_PART_CONFIG_DEV=${IL_LO_VFLASH_TARGET_VFLASH1_DEV}${IL_LO_VFLASH_PART_CONFIG_PART_NUM}
IL_LO_VFLASH_PART_CONFIG_LABEL=CONFIG
IL_LO_VFLASH_PART_CONFIG_MOUNT=/config
IL_LO_VFLASH_PART_CONFIG_BOOTABLE=
IL_LO_VFLASH_PART_CONFIG_PART_ID=83
IL_LO_VFLASH_PART_CONFIG_FSTYPE=ext3
IL_LO_VFLASH_PART_CONFIG_SIZE=17
IL_LO_VFLASH_PART_CONFIG_GROWTHCAP=
IL_LO_VFLASH_PART_CONFIG_GROWTHWEIGHT=

# Physical partition to store virtual filesystem images
IL_LO_VFLASH_PART_VPARTIMAGES_TARGET=VFLASH1
IL_LO_VFLASH_PART_VPARTIMAGES_PART_NUM=6
IL_LO_VFLASH_PART_VPARTIMAGES_DEV=${IL_LO_VFLASH_TARGET_VFLASH1_DEV}${IL_LO_VFLASH_PART_VPARTIMAGES_PART_NUM}
IL_LO_VFLASH_PART_VPARTIMAGES_LABEL=VPARTIMAGES
IL_LO_VFLASH_PART_VPARTIMAGES_MOUNT=/vpart_images
IL_LO_VFLASH_PART_VPARTIMAGES_BOOTABLE=
IL_LO_VFLASH_PART_VPARTIMAGES_PART_ID=83
IL_LO_VFLASH_PART_VPARTIMAGES_FSTYPE=ext3
IL_LO_VFLASH_PART_VPARTIMAGES_SIZE=380
IL_LO_VFLASH_PART_VPARTIMAGES_GROWTHCAP=
IL_LO_VFLASH_PART_VPARTIMAGES_GROWTHWEIGHT=
IL_LO_VFLASH_PART_VPARTIMAGES_OPTIONS="ro,noatime"

# XXX If Swap were desired for VFLASH
# IL_LO_VFLASH_PART_SWAP_TARGET=VFLASH1
# IL_LO_VFLASH_PART_SWAP_PART_NUM=7
# IL_LO_VFLASH_PART_SWAP_DEV=${IL_LO_VFLASH_TARGET_VFLASH1_DEV}${IL_LO_VFLASH_PART_SWAP_PART_NUM}
# IL_LO_VFLASH_PART_SWAP_LABEL=
# IL_LO_VFLASH_PART_SWAP_MOUNT=swap
# IL_LO_VFLASH_PART_SWAP_BOOTABLE=
# IL_LO_VFLASH_PART_SWAP_PART_ID=82
# IL_LO_VFLASH_PART_SWAP_FSTYPE=swap
# IL_LO_VFLASH_PART_SWAP_SIZE=512
# IL_LO_VFLASH_PART_SWAP_GROWTHCAP=
# IL_LO_VFLASH_PART_SWAP_GROWTHWEIGHT=

#
# Description of the virtual partition options
#
# Name of the physical partition that should store the fs image
# from one of the layout's PARTs.
#     IL_LO_<LAYOUT>_VPART_<NAME>_PART_NAME
# Indicates if this virtual partition should be written to the
# backing store on 'vpart writes'. (1, 0, or not set)
#     IL_LO_<LAYOUT>_VPART_<NAME>_DO_WRITEBACK
# List of directories to exclude from the write back
#     IL_LO_<LAYOUT>_VPART_<NAME>_WRITEBACK_EXCLUDE
# Indicate this is an image to be used as a rootfs. This has
# obvious special meaning and is assumed to be loaded only
# during the boot sequence. (1, 0, or not set)
#     IL_LO_<LAYOUT>_VPART_<NAME>_ISROOTFS
# Indicate how the virtual root fs is to be loaded (either
# directly from partition as a 'loop' fs or into a created
# 'tmpfs'. Can either be ('loop', 'tmpfs', or not set)
#     IL_LO_<LAYOUT>_VPART_<NAME>_ROOT_TYPE
# Name of the file to store the virtual partition image
#     IL_LO_<LAYOUT>_VPART_<NAME>_LABEL
# Used for label in mke2fs
#     IL_LO_<LAYOUT>_VPART_<NAME>_FILE_NAME
# How many inodes to create in the loopback fs image
#     IL_LO_<LAYOUT>_VPART_<NAME>_INODE_COUNT
# Size to use for contents on manufacture. XXX probably don't need if
# using compressed images
#     IL_LO_<LAYOUT>_VPART_<NAME>_CONTENT_SIZE
# Size for tmpfs entry in /etc/fstab (specified in megabytes)
#     IL_LO_<LAYOUT>_VPART_<NAME>_FSSIZE
# File system type to make the loopback fs image (recommend ext2)
#     IL_LO_<LAYOUT>_VPART_<NAME>_FSTYPE
# Mount point for the virtual partition in the file system
#     IL_LO_<LAYOUT>_VPART_<NAME>_MOUNT
# Compression type for the file system image. XXX currently not used.
# (none, gzip)
#     IL_LO_<LAYOUT>_VPART_<NAME>_COMPRESSION_TYPE

IL_LO_VFLASH_VPART_VAR_PART_NAME=VPARTIMAGES
IL_LO_VFLASH_VPART_VAR_DO_WRITEBACK=1
IL_LO_VFLASH_VPART_VAR_ISROOTFS=0
IL_LO_VFLASH_VPART_VAR_LABEL=VAR
IL_LO_VFLASH_VPART_VAR_FILE_NAME=var.vfimg
IL_LO_VFLASH_VPART_VAR_INODE_COUNT=1000
IL_LO_VFLASH_VPART_VAR_CONTENT_SIZE=16
IL_LO_VFLASH_VPART_VAR_FSSIZE=128
IL_LO_VFLASH_VPART_VAR_FSTYPE=ext2
IL_LO_VFLASH_VPART_VAR_MOUNT=/var
IL_LO_VFLASH_VPART_VAR_COMPRESSION_TYPE=none

IL_LO_VFLASH_VPART_ROOT1_PART_NAME=VPARTIMAGES
IL_LO_VFLASH_VPART_ROOT1_DO_WRITEBACK=1
IL_LO_VFLASH_VPART_ROOT1_WRITEBACK_EXCLUDE="/bootmgr /boot /var /config /tmp /old-root /proc /sys /dev /vpart_images /mnt"
IL_LO_VFLASH_VPART_ROOT1_ISROOTFS=1
IL_LO_VFLASH_VPART_ROOT1_ROOT_TYPE=tmpfs
IL_LO_VFLASH_VPART_ROOT1_LABEL=ROOT_1
IL_LO_VFLASH_VPART_ROOT1_FILE_NAME=1/rootfs.vfimg
IL_LO_VFLASH_VPART_ROOT1_INODE_COUNT=9000
IL_LO_VFLASH_VPART_ROOT1_CONTENT_SIZE=128
IL_LO_VFLASH_VPART_ROOT1_FSSIZE=192
IL_LO_VFLASH_VPART_ROOT1_RDONLY=1
IL_LO_VFLASH_VPART_ROOT1_FSTYPE=ext2
IL_LO_VFLASH_VPART_ROOT1_MOUNT=/
IL_LO_VFLASH_VPART_ROOT1_COMPRESSION_TYPE=none

IL_LO_VFLASH_VPART_ROOT2_PART_NAME=VPARTIMAGES
IL_LO_VFLASH_VPART_ROOT2_DO_WRITEBACK=1
IL_LO_VFLASH_VPART_ROOT2_WRITEBACK_EXCLUDE="/bootmgr /boot /var /config /tmp /old-root /proc /sys /dev /vpart_images /mnt"
IL_LO_VFLASH_VPART_ROOT2_ISROOTFS=1
IL_LO_VFLASH_VPART_ROOT2_ROOT_TYPE=tmpfs
IL_LO_VFLASH_VPART_ROOT2_LABEL=ROOT_2
IL_LO_VFLASH_VPART_ROOT2_FILE_NAME=2/rootfs.vfimg
IL_LO_VFLASH_VPART_ROOT2_INODE_COUNT=9000
IL_LO_VFLASH_VPART_ROOT2_CONTENT_SIZE=128
IL_LO_VFLASH_VPART_ROOT2_FSSIZE=192
IL_LO_VFLASH_VPART_ROOT2_RDONLY=1
IL_LO_VFLASH_VPART_ROOT2_FSTYPE=ext2
IL_LO_VFLASH_VPART_ROOT2_MOUNT=/
IL_LO_VFLASH_VPART_ROOT2_COMPRESSION_TYPE=none

# ==================================================
#
# Flash only (Direct root) image layout
#
# ==================================================

# These are the standard location names.  They should not be changed
IL_LO_FLASH_LOCS="BOOTMGR_1 BOOT_1 BOOT_2 ROOT_1 ROOT_2 CONFIG_1 VAR_1 \
    VIMAGES_1"

# Targets are things like a disk or a flash device
IL_LO_FLASH_TARGET_NUM_TARGETS=1
IL_LO_FLASH_TARGETS="FLASH1"
IL_LO_FLASH_TARGET_FLASH1_NUM=1

IL_LO_FLASH_ROOT_RDONLY=1

# Special arguments for kernel grub line to deal with possible
# flash device issues
IL_LO_FLASH_EXTRA_KERNEL_PARAMS="ide=nodma"

# XXX Would really like this to be a smaller min, but would need root fs
# image to be compressed 
#
# We're supporting a "1 gig" or "1024" "meg" flash, which may be as small as
# 953 MB due to marketing math: 1000*1000*1000/(1024*1024)=953.674.
IL_LO_FLASH_TARGET_FLASH1_MINSIZE=950

# A note on sizing in space limited layouts: writeimage (via sfdisk) may
# round to cylinder boundaries, which may be as large as a bit less than 8
# Megs each.  One easy way to avoid trouble is to choose sizes that are 
# 8 * n + 1 Megs each, but budget for 8 * (n + 1) Megs each.  So, if you
# need at least 10 megs, you could choose 17 Megs for the _SIZE
# number, but budget for 24 Megs.

# What partitions get made on the targets
IL_LO_FLASH_PARTS="BOOTMGR BOOT1 BOOT2 EXT CONFIG ROOT1 ROOT2 VPARTIMAGES"
# What virtual partitions are created into a tmpfs and backed
# by a physical partition
IL_LO_FLASH_VPARTS="VAR"

IL_LO_FLASH_IMAGE_1_INSTALL_LOCS="BOOT_1 ROOT_1"
IL_LO_FLASH_IMAGE_2_INSTALL_LOCS="BOOT_2 ROOT_2"
IL_LO_FLASH_IMAGE_1_LOCS="ROOT_1 BOOT_1 BOOTMGR_1 CONFIG_1 VAR_1 VIMAGES_1"
IL_LO_FLASH_IMAGE_2_LOCS="ROOT_2 BOOT_2 BOOTMGR_1 CONFIG_1 VAR_1 VIMAGES_1"

# XXX In two disk case how can we fill each 'last' partition?
IL_LO_FLASH_OPT_LAST_PART_FILL=0


# Each of these says which PART (partition) or VPART (virtual partition)
#     below goes with which LOC (standardized location) .  It also says for
#     each LOC which subdirectory under the PART/VPART the LOC is in, and
#     what files to extract there

IL_LO_FLASH_LOC_BOOTMGR_1_PART=BOOTMGR
IL_LO_FLASH_LOC_BOOTMGR_1_DIR=/
IL_LO_FLASH_LOC_BOOTMGR_1_IMAGE_EXTRACT="./bootmgr"
IL_LO_FLASH_LOC_BOOTMGR_1_IMAGE_EXTRACT_PREFIX="/bootmgr"

IL_LO_FLASH_LOC_BOOT_1_PART=BOOT1
IL_LO_FLASH_LOC_BOOT_1_DIR=/
IL_LO_FLASH_LOC_BOOT_1_IMAGE_EXTRACT="./boot"
IL_LO_FLASH_LOC_BOOT_1_IMAGE_EXTRACT_PREFIX="/boot"

IL_LO_FLASH_LOC_BOOT_2_PART=BOOT2
IL_LO_FLASH_LOC_BOOT_2_DIR=/
IL_LO_FLASH_LOC_BOOT_2_IMAGE_EXTRACT="./boot"
IL_LO_FLASH_LOC_BOOT_2_IMAGE_EXTRACT_PREFIX="/boot"

IL_LO_FLASH_LOC_ROOT_1_PART=ROOT1
IL_LO_FLASH_LOC_ROOT_1_DIR=/
IL_LO_FLASH_LOC_ROOT_1_IMAGE_EXTRACT="./"
IL_LO_FLASH_LOC_ROOT_1_IMAGE_EXTRACT_EXCLUDE="./bootmgr ./boot ./var ./config"
IL_LO_FLASH_LOC_ROOT_1_IMAGE_EXTRACT_PREFIX=""
IL_LO_FLASH_LOC_ROOT_1_IMAGE_EXTRA_MOUNTS="./vpart_images"

IL_LO_FLASH_LOC_ROOT_2_PART=ROOT2
IL_LO_FLASH_LOC_ROOT_2_DIR=/
IL_LO_FLASH_LOC_ROOT_2_IMAGE_EXTRACT="./"
IL_LO_FLASH_LOC_ROOT_2_IMAGE_EXTRACT_EXCLUDE="./bootmgr ./boot ./var ./config"
IL_LO_FLASH_LOC_ROOT_2_IMAGE_EXTRACT_PREFIX=""
IL_LO_FLASH_LOC_ROOT_2_IMAGE_EXTRA_MOUNTS="./vpart_images"

IL_LO_FLASH_LOC_VAR_1_VPART=VAR
IL_LO_FLASH_LOC_VAR_1_DIR=/var/
IL_LO_FLASH_LOC_VAR_1_IMAGE_EXTRACT="./var"
IL_LO_FLASH_LOC_VAR_1_IMAGE_EXTRACT_PREFIX="/var"

IL_LO_FLASH_LOC_CONFIG_1_PART=CONFIG
IL_LO_FLASH_LOC_CONFIG_1_DIR=/config/
IL_LO_FLASH_LOC_CONFIG_1_IMAGE_EXTRACT="./config"
IL_LO_FLASH_LOC_CONFIG_1_IMAGE_EXTRACT_PREFIX="/config"

IL_LO_FLASH_LOC_VIMAGES_1_PART=VPARTIMAGES
IL_LO_FLASH_LOC_VIMAGES_1_DIR=/
IL_LO_FLASH_LOC_VIMAGES_1_IMAGE_EXTRACT=

IL_LO_FLASH_LOC_SWAP_1_PART=

# XXX If Swap were desired for FLASH
# IL_LO_FLASH_LOC_SWAP_1_PART=SWAP
# IL_LO_FLASH_LOC_SWAP_1_DIR=
# IL_LO_FLASH_LOC_SWAP_1_IMAGE_EXTRACT=""
# IL_LO_FLASH_LOC_SWAP_1_IMAGE_EXTRACT_PREFIX=""

# Each of these says how a partition is named, labled, and sized.

IL_LO_FLASH_PART_BOOTMGR_TARGET=FLASH1
IL_LO_FLASH_PART_BOOTMGR_PART_NUM=1
IL_LO_FLASH_PART_BOOTMGR_DEV=${IL_LO_FLASH_TARGET_FLASH1_DEV}${IL_LO_FLASH_PART_BOOTMGR_PART_NUM}
IL_LO_FLASH_PART_BOOTMGR_LABEL=BOOTMGR
IL_LO_FLASH_PART_BOOTMGR_MOUNT=/bootmgr
IL_LO_FLASH_PART_BOOTMGR_BOOTABLE=1
IL_LO_FLASH_PART_BOOTMGR_PART_ID=83
IL_LO_FLASH_PART_BOOTMGR_FSTYPE=ext3
IL_LO_FLASH_PART_BOOTMGR_SIZE=17
IL_LO_FLASH_PART_BOOTMGR_GROWTHCAP=
IL_LO_FLASH_PART_BOOTMGR_GROWTHWEIGHT=
IL_LO_FLASH_PART_BOOTMGR_OPTIONS="defaults,noatime,ro"

IL_LO_FLASH_PART_BOOT1_TARGET=FLASH1
IL_LO_FLASH_PART_BOOT1_PART_NUM=2
IL_LO_FLASH_PART_BOOT1_DEV=${IL_LO_FLASH_TARGET_FLASH1_DEV}${IL_LO_FLASH_PART_BOOT1_PART_NUM}
IL_LO_FLASH_PART_BOOT1_LABEL=BOOT1
IL_LO_FLASH_PART_BOOT1_MOUNT=/boot
IL_LO_FLASH_PART_BOOT1_BOOTABLE=
IL_LO_FLASH_PART_BOOT1_PART_ID=83
IL_LO_FLASH_PART_BOOT1_FSTYPE=ext3
IL_LO_FLASH_PART_BOOT1_SIZE=17
IL_LO_FLASH_PART_BOOT1_GROWTHCAP=
IL_LO_FLASH_PART_BOOT1_GROWTHWEIGHT=
IL_LO_FLASH_PART_BOOT1_OPTIONS="defaults,noatime,ro"

IL_LO_FLASH_PART_BOOT2_TARGET=FLASH1
IL_LO_FLASH_PART_BOOT2_PART_NUM=3
IL_LO_FLASH_PART_BOOT2_DEV=${IL_LO_FLASH_TARGET_FLASH1_DEV}${IL_LO_FLASH_PART_BOOT2_PART_NUM}
IL_LO_FLASH_PART_BOOT2_LABEL=BOOT2
IL_LO_FLASH_PART_BOOT2_MOUNT=/boot
IL_LO_FLASH_PART_BOOT2_BOOTABLE=
IL_LO_FLASH_PART_BOOT2_PART_ID=83
IL_LO_FLASH_PART_BOOT2_FSTYPE=ext3
IL_LO_FLASH_PART_BOOT2_SIZE=17
IL_LO_FLASH_PART_BOOT2_GROWTHCAP=
IL_LO_FLASH_PART_BOOT2_GROWTHWEIGHT=
IL_LO_FLASH_PART_BOOT2_OPTIONS="defaults,noatime,ro"

IL_LO_FLASH_PART_EXT_TARGET=FLASH1
IL_LO_FLASH_PART_EXT_PART_NUM=4
IL_LO_FLASH_PART_EXT_DEV=${IL_LO_FLASH_TARGET_FLASH1_DEV}${IL_LO_FLASH_PART_EXT_PART_NUM}
IL_LO_FLASH_PART_EXT_LABEL=
IL_LO_FLASH_PART_EXT_MOUNT=
IL_LO_FLASH_PART_EXT_BOOTABLE=
IL_LO_FLASH_PART_EXT_PART_ID=0f
IL_LO_FLASH_PART_EXT_FSTYPE=
IL_LO_FLASH_PART_EXT_SIZE=
IL_LO_FLASH_PART_EXT_GROWTHCAP=
IL_LO_FLASH_PART_EXT_GROWTHWEIGHT=

IL_LO_FLASH_PART_CONFIG_TARGET=FLASH1
IL_LO_FLASH_PART_CONFIG_PART_NUM=5
IL_LO_FLASH_PART_CONFIG_DEV=${IL_LO_FLASH_TARGET_FLASH1_DEV}${IL_LO_FLASH_PART_CONFIG_PART_NUM}
IL_LO_FLASH_PART_CONFIG_LABEL=CONFIG
IL_LO_FLASH_PART_CONFIG_MOUNT=/config
IL_LO_FLASH_PART_CONFIG_BOOTABLE=
IL_LO_FLASH_PART_CONFIG_PART_ID=83
IL_LO_FLASH_PART_CONFIG_FSTYPE=ext3
IL_LO_FLASH_PART_CONFIG_SIZE=17
IL_LO_FLASH_PART_CONFIG_GROWTHCAP=
IL_LO_FLASH_PART_CONFIG_GROWTHWEIGHT=

IL_LO_FLASH_PART_ROOT1_TARGET=FLASH1
IL_LO_FLASH_PART_ROOT1_PART_NUM=6
IL_LO_FLASH_PART_ROOT1_DEV=${IL_LO_FLASH_TARGET_FLASH1_DEV}${IL_LO_FLASH_PART_ROOT1_PART_NUM}
IL_LO_FLASH_PART_ROOT1_LABEL=ROOT_1
IL_LO_FLASH_PART_ROOT1_MOUNT=/
IL_LO_FLASH_PART_ROOT1_BOOTABLE=
IL_LO_FLASH_PART_ROOT1_PART_ID=83
IL_LO_FLASH_PART_ROOT1_FSTYPE=ext3
IL_LO_FLASH_PART_ROOT1_SIZE=257
IL_LO_FLASH_PART_ROOT1_GROWTHCAP=
IL_LO_FLASH_PART_ROOT1_GROWTHWEIGHT=
IL_LO_FLASH_PART_ROOT1_OPTIONS="defaults,noatime,ro"

IL_LO_FLASH_PART_ROOT2_TARGET=FLASH1
IL_LO_FLASH_PART_ROOT2_PART_NUM=7
IL_LO_FLASH_PART_ROOT2_DEV=${IL_LO_FLASH_TARGET_FLASH1_DEV}${IL_LO_FLASH_PART_ROOT2_PART_NUM}
IL_LO_FLASH_PART_ROOT2_LABEL=ROOT_2
IL_LO_FLASH_PART_ROOT2_MOUNT=/
IL_LO_FLASH_PART_ROOT2_BOOTABLE=
IL_LO_FLASH_PART_ROOT2_PART_ID=83
IL_LO_FLASH_PART_ROOT2_FSTYPE=ext3
IL_LO_FLASH_PART_ROOT2_SIZE=257
IL_LO_FLASH_PART_ROOT2_GROWTHCAP=
IL_LO_FLASH_PART_ROOT2_GROWTHWEIGHT=
IL_LO_FLASH_PART_ROOT2_OPTIONS="defaults,noatime,ro"

# Physical partition to store virtual filesystem images
IL_LO_FLASH_PART_VPARTIMAGES_TARGET=FLASH1
IL_LO_FLASH_PART_VPARTIMAGES_PART_NUM=8
IL_LO_FLASH_PART_VPARTIMAGES_DEV=${IL_LO_FLASH_TARGET_FLASH1_DEV}${IL_LO_FLASH_PART_VPARTIMAGES_PART_NUM}
IL_LO_FLASH_PART_VPARTIMAGES_LABEL=VPARTIMAGES
IL_LO_FLASH_PART_VPARTIMAGES_MOUNT=/vpart_images
IL_LO_FLASH_PART_VPARTIMAGES_BOOTABLE=
IL_LO_FLASH_PART_VPARTIMAGES_PART_ID=83
IL_LO_FLASH_PART_VPARTIMAGES_FSTYPE=ext3
IL_LO_FLASH_PART_VPARTIMAGES_SIZE=337
IL_LO_FLASH_PART_VPARTIMAGES_GROWTHCAP=
IL_LO_FLASH_PART_VPARTIMAGES_GROWTHWEIGHT=
IL_LO_FLASH_PART_VPARTIMAGES_OPTIONS="ro,noatime"

#
# Description of the virtual partition options
#
# Name of the physical partition that should store the fs image
# from one of the layout's PARTs.
#     IL_LO_<LAYOUT>_VPART_<NAME>_PART_NAME
# Indicates if this virtual partition should be written to the
# backing store on 'vpart writes'. (1, 0, or not set)
#     IL_LO_<LAYOUT>_VPART_<NAME>_DO_WRITEBACK
# List of directories to exclude from the write back
#     IL_LO_<LAYOUT>_VPART_<NAME>_WRITEBACK_EXCLUDE
# Indicate this is an image to be used as a rootfs. This has
# obvious special meaning and is assumed to be loaded only
# during the boot sequence. (1, 0, or not set)
#     IL_LO_<LAYOUT>_VPART_<NAME>_ISROOTFS
# Indicate how the virtual root fs is to be loaded (either
# directly from partition as a 'loop' fs or into a created
# 'tmpfs'. Can either be ('loop', 'tmpfs', or not set)
# NB: only 'tmpfs' is implemented at this time
#     IL_LO_<LAYOUT>_VPART_<NAME>_ROOT_TYPE
# Name of the file to store the virtual partition image
#     IL_LO_<LAYOUT>_VPART_<NAME>_LABEL
# Used for label in mke2fs
#     IL_LO_<LAYOUT>_VPART_<NAME>_FILE_NAME
# How many inodes to create in the loopback fs image
#     IL_LO_<LAYOUT>_VPART_<NAME>_INODE_COUNT
# Size to use for contents on manufacture. XXX probably don't need if
# using compressed images
#     IL_LO_<LAYOUT>_VPART_<NAME>_CONTENT_SIZE
# Size for tmpfs entry in /etc/fstab (specified in megabytes)
#     IL_LO_<LAYOUT>_VPART_<NAME>_FSSIZE
# File system type to make the loopback fs image (recommend ext2)
#     IL_LO_<LAYOUT>_VPART_<NAME>_FSTYPE
# Mount point for the virtual partition in the file system
#     IL_LO_<LAYOUT>_VPART_<NAME>_MOUNT
# Compression type for the file system image. XXX currently not used.
# (none, gzip)
#     IL_LO_<LAYOUT>_VPART_<NAME>_COMPRESSION_TYPE

IL_LO_FLASH_VPART_VAR_PART_NAME=VPARTIMAGES
IL_LO_FLASH_VPART_VAR_DO_WRITEBACK=1
IL_LO_FLASH_VPART_VAR_ISROOTFS=0
IL_LO_FLASH_VPART_VAR_LABEL=VAR
IL_LO_FLASH_VPART_VAR_FILE_NAME=var.vfimg
IL_LO_FLASH_VPART_VAR_INODE_COUNT=2000
IL_LO_FLASH_VPART_VAR_CONTENT_SIZE=280
IL_LO_FLASH_VPART_VAR_FSSIZE=280
IL_LO_FLASH_VPART_VAR_FSTYPE=ext2
IL_LO_FLASH_VPART_VAR_MOUNT=/var
IL_LO_FLASH_VPART_VAR_COMPRESSION_TYPE=none

# Define graft functions
if [ -f /etc/customer_rootflop.sh ]; then
    . /etc/customer_rootflop.sh
fi

# Graft point for layouts: append to/reset IL_LO_...
if [ "$HAVE_LAYOUT_SETTINGS_GRAFT_1" = "y" ]; then
    layout_settings_graft_1
fi
