#  Makefile
#
# 
#
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

# The order of these matters, as the packages must be written before *_files
SUBDIRS=\
	image_packages \
	rootflop_packages \

##	image_files \
##	init_files \
##	script_files \
##	rootflop_files \


# NOTE: These directories must be built and installed as 'root'

include ${PROD_TREE_ROOT}/src/mk/subdir.mk
