/*
 * modules.c --- automatically generated by Apache
 * configuration script.  DO NOT HAND EDIT!!!!!
 */

#include "ap_config.h"
#include "httpd.h"
#define CORE_PRIVATE
#include "http_config.h"

/* For TMS graft points */
#include "customer.h"

extern module core_module;
extern module authn_file_module;
extern module authn_default_module;
extern module authz_host_module;
extern module authz_groupfile_module;
extern module authz_user_module;
extern module authz_default_module;
extern module auth_basic_module;
extern module include_module;
extern module filter_module;
extern module deflate_module;
extern module log_config_module;
extern module env_module;
extern module headers_module;
extern module setenvif_module;
extern module version_module;
extern module ssl_module;
extern module mpm_prefork_module;
extern module http_module;
extern module mime_module;
extern module status_module;
extern module autoindex_module;
extern module asis_module;
extern module info_module;
extern module cgi_module;
extern module dir_module;
extern module actions_module;
extern module alias_module;
extern module rewrite_module;
extern module so_module;

/* ========================================================================= */
/* Customer-specific graft point 1: additional module definitions.
 * =========================================================================
 */
#ifdef INC_APACHE_MODULES_INC_GRAFT_POINT
#undef APACHE_MODULES_INC_GRAFT_POINT
#define APACHE_MODULES_INC_GRAFT_POINT 1
#include "../base_os/common/apache/src/modules/modules.inc.c"
#endif /* INC_APACHE_MODULES_INC_GRAFT_POINT */

/*
 *  Modules which implicitly form the
 *  list of activated modules on startup,
 *  i.e. these are the modules which are
 *  initially linked into the Apache processing
 *  [extendable under run-time via AddModule]
 */
module *ap_prelinked_modules[] = {
  &core_module,
  &authn_file_module,
  &authn_default_module,
  &authz_host_module,
  &authz_groupfile_module,
  &authz_user_module,
  &authz_default_module,
  &auth_basic_module,
  &include_module,
  &filter_module,
  &deflate_module,
  &log_config_module,
  &env_module,
  &headers_module,
  &setenvif_module,
  &version_module,
  &ssl_module,
  &mpm_prefork_module,
  &http_module,
  &mime_module,
  &status_module,
  &autoindex_module,
  &asis_module,
  &info_module,
  &cgi_module,
  &dir_module,
  &actions_module,
  &alias_module,
  &rewrite_module,
  &so_module,

/* ========================================================================= */
/* Customer-specific graft point 2: additional prelinked modules.
 * =========================================================================
 */
#ifdef INC_APACHE_MODULES_INC_GRAFT_POINT
#undef APACHE_MODULES_INC_GRAFT_POINT
#define APACHE_MODULES_INC_GRAFT_POINT 2
#include "../base_os/common/apache/src/modules/modules.inc.c"
#endif /* INC_APACHE_MODULES_INC_GRAFT_POINT */

  NULL
};

/*
 *  We need the symbols as strings for <IfModule> containers
 */

ap_module_symbol_t ap_prelinked_module_symbols[] = {
  {"core_module", &core_module},
  {"authn_file_module", &authn_file_module},
  {"authn_default_module", &authn_default_module},
  {"authz_host_module", &authz_host_module},
  {"authz_groupfile_module", &authz_groupfile_module},
  {"authz_user_module", &authz_user_module},
  {"authz_default_module", &authz_default_module},
  {"auth_basic_module", &auth_basic_module},
  {"include_module", &include_module},
  {"filter_module", &filter_module},
  {"deflate_module", &deflate_module},
  {"log_config_module", &log_config_module},
  {"env_module", &env_module},
  {"headers_module", &headers_module},
  {"setenvif_module", &setenvif_module},
  {"version_module", &version_module},
  {"ssl_module", &ssl_module},
  {"mpm_prefork_module", &mpm_prefork_module},
  {"http_module", &http_module},
  {"mime_module", &mime_module},
  {"status_module", &status_module},
  {"autoindex_module", &autoindex_module},
  {"asis_module", &asis_module},
  {"info_module", &info_module},
  {"cgi_module", &cgi_module},
  {"dir_module", &dir_module},
  {"actions_module", &actions_module},
  {"alias_module", &alias_module},
  {"rewrite_module", &rewrite_module},
  {"so_module", &so_module},

/* ========================================================================= */
/* Customer-specific graft point 4: additional prelinked module names.
 * =========================================================================
 */
#ifdef INC_APACHE_MODULES_INC_GRAFT_POINT
#undef APACHE_MODULES_INC_GRAFT_POINT
#define APACHE_MODULES_INC_GRAFT_POINT 4
#include "../base_os/common/apache/src/modules/modules.inc.c"
#endif /* INC_APACHE_MODULES_INC_GRAFT_POINT */

  {NULL, NULL}
};

/*
 *  Modules which initially form the
 *  list of available modules on startup,
 *  i.e. these are the modules which are
 *  initially loaded into the Apache process
 *  [extendable under run-time via LoadModule]
 */
module *ap_preloaded_modules[] = {
  &core_module,
  &authn_file_module,
  &authn_default_module,
  &authz_host_module,
  &authz_groupfile_module,
  &authz_user_module,
  &authz_default_module,
  &auth_basic_module,
  &include_module,
  &filter_module,
  &deflate_module,
  &log_config_module,
  &env_module,
  &headers_module,
  &setenvif_module,
  &version_module,
  &ssl_module,
  &mpm_prefork_module,
  &http_module,
  &mime_module,
  &status_module,
  &autoindex_module,
  &asis_module,
  &info_module,
  &cgi_module,
  &dir_module,
  &actions_module,
  &alias_module,
  &rewrite_module,
  &so_module,

/* ========================================================================= */
/* Customer-specific graft point 3: additional preloaded modules.
 * =========================================================================
 */
#ifdef INC_APACHE_MODULES_INC_GRAFT_POINT
#undef APACHE_MODULES_INC_GRAFT_POINT
#define APACHE_MODULES_INC_GRAFT_POINT 3
#include "../base_os/common/apache/src/modules/modules.inc.c"
#endif /* INC_APACHE_MODULES_INC_GRAFT_POINT */

  NULL
};
