# Makefile

include ${PROD_TREE_ROOT}/src/mk/common.mk

# The order of these matters, as the packages must be written before *_files
SUBDIRS=                  \
	image_packages    \

# XXXX should do the same as we do in fc6
##	arch_${PROD_TARGET_ARCH_LC} \

include ${PROD_TREE_ROOT}/src/mk/subdir.mk
