#  Makefile
#
# 
#
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

LIB=tc_st

SRCS= \
	cond_st.c \
	defines_st.c \
	lock_st.c \
	signals_st.c \
	utils_st.c \
	internal_st.c \

include ${PROD_TREE_ROOT}/src/mk/lib.mk
