# Makefile

include ${PROD_TREE_ROOT}/src/mk/common.mk

# The subdir libcli has graft files included from the PROD_TREE_ROOT side of the build.

SUBDIRS=\
	disp \
	thread_pool \
	safeio \
	sync_serial \
	event_timer \
	io_hdlr \
	kms \
	aligner\
	latm_parser\

include ${PROD_TREE_ROOT}/src/mk/subdir.mk
