# Makefile

include ${PROD_TREE_ROOT}/src/mk/common.mk

SUBDIRS=		\
	common_opt	\
	common		\
	mgmt		\
	mgmta		\
	compression	\
	sched		\
	rtsched		\
	am		\
	nfsm		\
	bufmgr		\
	bufmgr/bufmgropt\
	mediamgr	\
	diskmgr2	\
	omgr		\
	libsocket	\
	pythonlib	\
	parser		\
	vmgr		\
	memalloc	\
	authmgr		\
	pemgr		\
	ssp		\
	encmgr 		\
	cluster		\
	htable		\
	virtcachesvr	\

include ${PROD_TREE_ROOT}/src/mk/subdir.mk
