# Makefile

include ${PROD_TREE_ROOT}/src/mk/common.mk

SRCS_BASE=customer.h customer_libcommon.c
PO_OUTPUT_DIR=${PROD_PRODUCT_I18N_ROOT}/src/include
MO_OUTPUT_DIR=${LIB_DIR}/include

include ${PROD_TREE_ROOT}/src/mk/po.mk
