#ifndef NKN_ERRNO_H
#define NKN_ERRNO_H

/*
 * Error number definitions for NVSD
 * We assign starting from 10000 to avoid conflicts with system error numbers
 * TBD - create nkn_strerror() and perror for diagnostics
 *
 * NKN_FOUND_BUT_NOT_VALID_YET: Internal error, indicating that an object is
 *	in the cache but can not be served yet.  This error should be converted
 *	to other error codes before returning to the client request.
 * NKN_STAT_*: internal errors which should not be seen through external
 *	interfaces
 */

#define NKN_ATTR_OVERFLOW		10001
#define NKN_ATTR_TOOLONG		10002
#define NKN_SERVER_BUSY			10003
#define NKN_FOUND_BUT_NOT_VALID_YET	10004
#define NKN_RESOURCE_TASK_FAILURE	10005

// Statistics errors
#define NKN_STAT_GEN_MISMATCH		19001
#define NKN_STAT_HASH_EINVAL		19002
#define NKN_STAT_TYPE_EINVAL		19003
#define NKN_STAT_CACHE_PIN_ENOSPC	19004
#define NKN_STAT_NAMESPACE_ENOSPC	19005
#define NKN_STAT_NAMESPACE_EINVAL	19006
#define NKN_STAT_NAMESPACE_FREE_FAILED	19007

// Buffer Manager
#define NKN_BUF_INVALID_INPUT	20001
#define NKN_BUF_MMREQ_FAILED	20002
#define NKN_BUF_INVALID_OFFSET	20003
#define NKN_BUF_ORIGIN_EXPIRED	20004	// Got expired data from Origin
#define NKN_BUF_VERSION_EXPIRED	20005	// Vers referred to by COD has expired
#define NKN_BUF_WAIT_FAILED	20006	// Failed to do timed wait
#define NKN_BUF_WAIT_LOOP	20007	// Got repeat timed wait from provider
#define NKN_BUF_NOT_AVAILABLE	20008   // Requested buffer not available locally
#define NKN_BUF_QUEUE_TIMEOUT	20009	// When request queue timeout happens
#define NKN_BUF_TASKFAIL	20010	// TASK create failure
#define NKN_BUF_INV_EOD_OFFSET	20011   // Invalid Eod offset

// COD Manager
#define NKN_COD_INVALID_COD		21001	// Invalid COD entry specified
#define NKN_COD_UNKNOWN_COD		21002	// COD entry has unknown version
#define NKN_COD_VERSION_MISMATCH	21003
#define NKN_COD_EXPIRED			21004   // COD is expired

// NKN SSP Module Error Number Defintions
// NKN SSP reserves Error Numbers from 30000 to 32000
#define NKN_SSP_BAD_URL			30001
#define NKN_SSP_AFR_INSUFF		30003
#define NKN_SSP_CLOSE_CON		30005
#define NKN_SSP_HASHCHECK_FAIL		30011
#define NKN_SSP_HASHEXPIRY_FAILED	30013
#define NKN_SSP_INSUFF_QUERY_PARAM	30021
#define NKN_SSP_MISSING_QUERY_PARAM	30023
#define NKN_SSP_METAFILE_FETCH_FAIL	30031
#define NKN_SSP_METAFILE_NOT_SUPP	30033
#define NKN_SSP_CHUNK_METAFILE_NOT_SUPP	30035
#define NKN_SSP_CONTAINER_FRMT_NOT_SUPP 30037
#define NKN_SSP_DOWNLOAD_NOT_SUPP	30039 // Download is not supported for smoothflow yet
#define NKN_SSP_BAD_QUERY_OFFSET	30041
#define NKN_SSP_PYTHON_PLUGIN_FAILURE	30043
#define NKN_SSP_CLI_PARAM_UNSPECIFIED   30045
#define NKN_SSP_VIDEOID_DISABLED        30050
#define NKN_SSP_BAD_REMAPPED_URL        30051
#define NKN_SSP_FORCE_TUNNEL_PATH	30052

// NKN SSP Smoothflow error codes
#define NKN_SSP_SF_SESSION_ID_NOT_FOUND		30200
#define NKN_SSP_SF_SESSION_ID_EXISTS		30201
#define NKN_SSP_SF_SMOOTHFLOW_NOT_SUPP		30202
#define NKN_SSP_SF_ADAPTATION_QUERY_MISSING	30204
#define NKN_SSP_SF_PROFILE_CHANGE_OUT_OF_BOUND	30206
#define NKN_SSP_SF_METADATA_PARSING_ERR		30208
#define NKN_SSP_SF_STATE_NOT_SUPPORTED		30210
#define NKN_SSP_SF_STATE_QUERY_MISSING		30212
#define NKN_SSP_SF_SESSIONID_QUERY_MISSING	30214
#define NKN_SSP_SF_INVALID_CONTROL_POINT        30216
#define NKN_SSP_SF_INCORRECT_NAMING_CONVENTION  30218
#define NKN_SSP_SF_PUBLISHING_REQ_FAILED        30230

// NKN SSP Smooth Stream error codes (Silverlight)
#define NKN_SSP_SS_TRACK_NOT_FOUND		30400
#define NKN_SSP_SS_SVR_MANIFEST_ISM_NOT_FOUND	30402
#define NKN_SSP_SS_NULL_BUF_INT_FETCH		30404
#define NKN_SSP_SS_ISMV_ISMA_NOT_FOUND		30406
#define NKN_SSP_SS_MFRO_OFF_FAIL		30408
#define NKN_SSP_SS_MEM_ALLOC_HDR_FAIL		30410

// NKN SSP Flash Stream error codes (Zeri)
#define NKN_SSP_FS_URI_FORMAT_ERR               30450
#define NKN_SSP_FS_SEGFRAG_TAG_NOT_FOUND        30452
#define NKN_SSP_FS_F4X_NOT_FOUND		30454
#define NKN_SSP_FS_MEM_ALLOC_HDR_FAIL		30456
#define NKN_SSP_FS_F4X_CONTEXT_FAILURE		30458
#define NKN_SSP_FS_F4F_OFFSET_PARSE_ERROR	30460

/*
 * DiskManager2
 *
 * Most DM2 errors should never be seen through the HTTP interface; however,
 * some like NKN_DM2_BAD_URI might be seen if a malformed URI or unexpected URI
 * is passed to DM2 instead of being caught by a higher layer.
 *
 * Int err: Internal error passed back to calling function.  This error code
 *	should never be passed back to HTTP request.
 * - should not pass thru: A request which was generated by user or a higher
 *	layer has been sent to DM2.  This request should not have been given
 *	to DM2.
 * - malformed request: A request from a higher layer violates the internal API
 *	agreement.
 *
 * Startup: Initialization errors which are never passed back to http interface
 *	but might be seen in a log.
 *
 * NKN_DM2_DISK_ADMIN_ACTION: A previous command has been given to cause the
 *	disk to be in the "cache enabled" state.
 * NKN_DM2_EMPTY_CACHE_TIER: A request was sent to a disk tier which has no
 *	enabled disks.
 * NKN_DM2_EVICTION_SKIPPED: An eviction request was made but the request
 *	had some type of error in it.
 * NKN_DM2_WRONG_CACHE_VERSION: Attempting to enable a cache which has the
 *	wrong version number.  This should never happen because older
 *	older versions should be converted to the current version.  MFD
 *	doesn't downgrade cache versions.
 * NKN_DM2_DISK_CACHE_NOT_FOUND: An unknown disk cache name was given to the
 *	CLI, and MFD returns this error.
 * NKN_DM2_INVALID_MGMT_REQUEST: The command attempted was not valid for the
 *	given state of the disk.  This is a generic error.
 * NKN_DM2_DISK_DEVICE_NOT_FOUND: During a 'status active' command, the system
 *	could not find the requested device.
 * NKN_DM2_CONVERT_FAILED: When MFD is starting or a drive is made 'status
 *	active', a possible format conversion is done.  If that conversion
 *	fails, MFD returns this error.
 * NKN_DM2_MUST_CACHE_DISABLE: If a drive is in the 'cache enabled' state and
 *	a 'status inactive' command is given, we return this error.
 * NKN_DM2_MUST_CLEAR: If a drive is in an error state of any kind and a
 *	'cache enable' command is given, MFD returns this error.
 * NKN_DM2_MUST_STATUS_ACTIVE: If a drive is in the 'status inactive' state
 *	and a 'cache enable' command is given, we return this error.
 */
#define NKN_DM2_DISK_ADMIN_ACTION	40005	// Startup: prev cmd => no cache
#define NKN_DM2_BITMAP_NOT_FOUND	40006	// Startup
#define NKN_DM2_EMPTY_CACHE_TIER	40007	// Int err: returned to MM
#define NKN_DM2_EVICTION_SKIPPED	40010	// Int err: malformed request
#define NKN_DM2_OBJ_NOT_YET_WRITTEN	40011	// Int err: race condition
#define NKN_DM2_MUST_FORMAT		40012	// Not used anymore
#define NKN_DM2_WRONG_CACHE_VERSION	40013	// Startup
#define NKN_DM2_ATTR_TOO_LARGE		40015	// Int err: should not pass thru
#define NKN_DM2_INVALID_ATTR_SIZE	40016	// Int err: should not pass thru
#define NKN_DM2_INVALID_URI_CONT_LEN	40017	// Int err: should not pass thru
#define NKN_DM2_INVALID_URI_OFFSET	40018	// Int err: should not pass thru
#define NKN_DM2_URI_EXPIRED		40019	// Int err: should not pass thru
#define NKN_DM2_BAD_URI			40020	// Int err: should not pass thru
#define NKN_DM2_INTERNAL_ISSUE		40021	// Int err: malformed request
#define NKN_DM2_WRONG_URI_VERSION	40022	// Int err: malformed request
#define NKN_DM2_TOO_MANY_STREAMING_PUTS 40023	// Int err: max streaming puts
#define NKN_DM2_PARTIAL_EXTENT_EEXIST   40024   // The exten is partial and does
                                                // not have 2MB data
#define NKN_DM2_ATTR_DELETED		40025   // attr is already deleted

// DiskManager2 Management errors (should not be seen through HTTP)
#define NKN_DM2_DISK_CACHE_NOT_FOUND	41001
#define NKN_DM2_INVALID_MGMT_REQUEST	41002	// cmd not valid 4 current state
#define NKN_DM2_DISK_DEVICE_NOT_FOUND	41003	// 'status active' failure
#define NKN_DM2_DISK_DEACTIVATE_FAILED	41004	//
#define NKN_DM2_FORMAT_FAILED		41005	//
#define NKN_DM2_DISK_ACTIVATE_FAILED	41006	//
#define NKN_DM2_CONVERT_FAILED		41007	// for 'status active' cmd
#define NKN_DM2_MUST_CACHE_DISABLE	41008	// should issue 'cache disable'
						//	first
#define NKN_DM2_MUST_CLEAR_ERROR	41009	// instructions in admin guide
#define NKN_DM2_MUST_STATUS_ACTIVE	41010	// should issue 'status active'
						//	first


// In-line OriginManager
// In-line OM reserves Error Numbers from 50001 to 51999
#define NKN_OM_SERVER_FETCH_ERROR	50001
#define NKN_OM_NO_RESOURCE		50002
#define NKN_OM_SERVER_DOWN		50003
#define NKN_OM_SVR_RET_NOT_200		50004
//#define NKN_OM_CONNECTION_ERR		50005 // Deprecated
#define NKN_OM_BUILD_REQ_ERR		50006
#define NKN_OM_NO_NAMESPACE		50007
#define NKN_OM_INTERNAL_ERR		50008
#define NKN_OM_ENDOF_TRANS		50009
#define NKN_OM_PARSE_ERR_1		50011
//#define NKN_OM_PARSE_ERR_2		50012 // Deprecated
//#define NKN_OM_PARSE_ERR_3		50013 // Deprecated
//#define NKN_OM_PARSE_ERR_4		50014 // Deprecated
//#define NKN_OM_PARSE_ERR_5		50015 // Deprecated
//#define NKN_OM_PARSE_ERR_6		50016 // Deprecated
//#define NKN_OM_PARSE_ERR_7		50017 // Deprecated
#define NKN_OM_GET_START_ERR		50018
#define NKN_OM_NON_CACHEABLE		50019
//#define NKN_OM_PARSE_ERR_8		50020 // Deprecated
#define NKN_OM_INV_OBJ_VERSION		50021
//#define NKN_OM_PARSE_ERR_9		50022 // Deprecated
#define NKN_OM_SSP_RETURN		50023
//#define NKN_OM_PARSE_ERR_10		50024 // Deprecated
//#define NKN_OM_PARSE_ERR_11		50025 // Deprecated
#define NKN_OM_RTSP_ERR_OPEN_SOCKET	50026
#define NKN_OM_RTSP_ERR_UNKNOWN		50027
#define NKN_OM_SERVICE_UNAVAILABLE	50028
#define NKN_OM_INV_PARTIAL_OBJ		50029
#define NKN_OM_REDIRECT			50030
#define NKN_OM_SOCKET_TIMEOUT		50031
#define NKN_OM_SVR_ERR_CLT_CANCEL	50032
#define NKN_OM_LEAK_DETECT_ERROR	50033
#define NKN_OM_CONF_REFETCH_REQUEST	50034
#define NKN_OM_ORIGIN_FAILOVER_ERROR	50035
#define NKN_OM_WWW_AUTHENTICATE_NTLM	50036
#define NKN_OM_SERVER_NO_DATA		50037	// internal error 
#define NKN_OM_CI_END_OFFSET_RESPONSE   50038
#define NKN_OM_CONNECTION_UPGRADE	50039
// Tunnel Module
// Tunnel Module reserves Error Numbers from 51001 to 51999
#define NKN_TUNNEL_FETCH_ERROR		51001


// HTTP Module
// HTTP Module reserves Error Numbers from 52001 to 52999
//#define NKN_HTTP_TASK_RET		52001 // depreciated
#define NKN_HTTP_MALLOC			52002
#define NKN_HTTP_REQUEST		52003
#define NKN_HTTP_NAMESPACE		52004
#define NKN_HTTP_REQ_RANGE_1		52005
#define NKN_HTTP_REQ_RANGE_2		52006
#define NKN_HTTP_REQ_RANGE_3		52007
#define NKN_HTTP_RES_RANGE_1		52008
#define NKN_HTTP_RES_RANGE_2		52009
#define NKN_HTTP_RES_RANGE_3		52010
#define NKN_HTTP_CONTENT_TYPE		52011
#define NKN_HTTP_URI			52012
#define NKN_HTTP_URI_MORE		52013
#define NKN_HTTP_URI_LESS		52014
#define NKN_HTTP_RES_SEEK		52015
#define NKN_HTTP_CLOSE_CONN		52016
#define NKN_HTTP_GET_CONT_LENGTH	52017
#define NKN_HTTP_NO_HOST_HTTP11		52018
#define NKN_HTTP_PARSER			52019
#define NKN_HTTP_ERR_CHUNKED_REQ	52020
#define NKN_HTTP_BAD_HOST_HEADER	52021
#define NKN_HTTP_BAD_URL_HOST_HEADER	52022
#define NKN_HTTP_UNSUPPORT_VERSION	52023
#define NKN_HTTP_TPROXY_NO_DSTIP	52024
#define NKN_HTTP_TPROXY_OUR_IFIP	52025
#define NKN_HTTP_NS_MAX_CONNS		52026
//#define NKN_HTTP_PE_REJECT		52027 // depreciated
#define NKN_HTTP_METHOD_NOT_SUPPORTED	52028
#define NKN_HTTP_CANCELED_SOCKET	52029
#define NKN_HTTP_CLIENT_CLOSED		52030
//#define NKN_HTTP_REJECT_ON_GEO_IP_FAIL	52031 // depreciated
#define NKN_HTTPS_NAMESPACE		52032
#define NKN_HTTP_CLOSE_CONN_RBCI_REFETCH 52033
#define NKN_HTTP_CLOSE_CONN_NFS_CONFIG	52034
#define NKN_HTTP_NS_BIND_IP_NOMATCH	52035
#define NKN_HTTP_COMPRESS_FAIL		52036
#define NKN_HTTP_AUTHORIZATION_FAIL	52037



// RTSP
/* PE - Parse Error
 * VER - Version
 * URL - URL
 * REQL - Request-Line
 * HDR - Header
 * LT - Buffer boundary limitations
 * PVE - Protocol Validation Error
 */
#define NKN_RTSP_PE_VER_1		53000
#define NKN_RTSP_PE_VER_2		53001
#define NKN_RTSP_PE_VER_3		53002
#define NKN_RTSP_PE_VER_LT1		53003
#define NKN_RTSP_PE_VER_LT2		53004
#define NKN_RTSP_PE_URL_1_PROTOCOL	53005
#define NKN_RTSP_PE_URL_2_HOST		53006
#define NKN_RTSP_PE_URL_3_HOST		53007
#define NKN_RTSP_PE_URL_4_PORT		53008
#define NKN_RTSP_PE_URL_LT1		53009
#define NKN_RTSP_PE_URL_LT2		53010
#define NKN_RTSP_PE_REQL_1_METHOD	53011
#define NKN_RTSP_PE_REQL_LT1		53012
#define NKN_RTSP_PE_REQL_LT2		53013
#define NKN_RTSP_PE_REQL_LT3		53014
#define NKN_RTSP_PE_HDR_1		53015
#define NKN_RTSP_PE_REQ_1		53016
#define NKN_RTSP_PVE_URL_1		53017
#define NKN_RTSP_PVE_REQ_CSEQ		53018
#define NKN_RTSP_PVE_REQ_SESSION	53019
#define NKN_RTSP_PVE_REQ_TRANSPORT	53020
#define NKN_RTSP_PE_REQ_TOO_LARGE	53021
#define NKN_RTSP_PVE_METHOD1		53022


// PE related
// PE Module reserves Error Numbers from 54001 to 54999
#define NKN_PE_REJECT			54001
#define NKN_PE_REDIRECT			54002

// PE with GeoIP codes
#define NKN_PE_REJECT_ON_GEOIP_FAIL	54101
#define NKN_PE_GEOIP_REJECT		54102
#define NKN_PE_GEOIP_REDIRECT		54103

// PE with URL filtering codes
#define NKN_PE_REJECT_ON_UCFLT_FAIL	54201
#define NKN_PE_UCFLT_REJECT		54202
#define NKN_PE_UCFLT_REDIRECT		54203


// Media Manager Module
// MM Module reserves Error Numbers from 70001 to 71999
#define NKN_MM_GET_URI_ERR              70001
#define NKN_MM_STAT_URI_ERR             70002
#define NKN_MM_PROMOTE_PUT_ERR          70003
#define NKN_MM_PROMOTE_GET_ERR          70004
#define NKN_MM_PROMOTE_ATTR_ERR         70005
#define NKN_MM_PROMOTE_GEN_ERR          70006
#define NKN_MM_GET_COD_ERR              70007
#define NKN_MM_STAT_COD_ERR             70008
#define NKN_MM_OBJ_NOT_CACHE_WORTHY	70009
#define NKN_MM_TOKEN_ERR		70010
#define NKN_MM_CONF_RETRY_REQUEST	70020
#define NKN_MM_UNCOND_RETRY_REQUEST	70021
#define NKN_MM_OBJ_NOT_FOUND_IN_CACHE   70022
#define NKN_MM_REDIRECT_REQUEST		70023
#define NKN_MM_CIM_INVALID_URI		70024
#define NKN_MM_CIM_ADD_HDR_ERR		70025
#define NKN_MM_CIM_COD_ALREADY_PRESENT  70026
#define NKN_MM_CIM_NAMESPACE_MATCH	70027
#define NKN_MM_ICCP_MESSAGE_CREAT_FAIL	70028
#define NKN_MM_ICCP_MESSAGE_SND_FAIL	70029
#define NKN_MM_CIM_ABORT		70030
#define NKN_MM_CIM_NO_DISK_AVAIL	70031
#define NKN_MM_CIM_COD_OPEN_FAILURE     70032
#define NKN_MM_CUM_COD_ALREADY_PRESENT  70033
#define NKN_MM_CONF_BIG_ATTRIBUTE	70034
#define NKN_MM_CONF_SMALL_OBJECT_SIZE	70035
#define NKN_MM_CONF_DIRECTORY_DEPTH	70036
#define NKN_MM_CONF_OBJECT_EXPIRED	70037
#define NKN_MM_CIM_DEL_TASK_CR_FAILED	70038
#define NKN_MM_CIM_NVSD_CONN_RESET	70039
#define NKN_MM_CIM_RETRY		70040
#define NKN_MM_PROMOTE_BUFLEFT_PUTERR	70041
#define NKN_MM_PROMOTE_DM2_ATTRCOPY_ERR 70042
#define NKN_MM_PROMOTE_NEGCONTLEN_ERR	70043
#define NKN_MM_PROMOTE_NOBUF_ATTACH_ERR 70044
#define NKN_MM_PROMOTE_MOREPUT_ERR	70045
#define NKN_MM_PROMOTE_GET_ERR1		70046
#define NKN_MM_PROMOTE_GET_ERR2		70047
#define NKN_MM_PROMOTE_RESUME_GETERR	70048
#define NKN_MM_PROMOTE_INVCODCLOSE_ERR	70049
#define NKN_MM_CIM_NO_VALID_TIER	70050
#define NKN_MM_PULL_INGST_OBJ_WITH_HOLE	70051

// Forward Proxy Tunnel Module
// Forward Proxy Tunnel reserves Error Numbers from 71001 to 71999
#define NKN_FP_DNS_ERR			71001
#define NKN_FP_MALLOC			71002
#define NKN_FP_NETWORK			71003
#define NKN_FP_NAMESPACE		71004
#define NKN_FP_SOCKET			71005
#define NKN_FP_ACTIVATE_SOCKET		71006
//#define NKN_FP_CONFLICT			71007
#define NKN_FP_NOT_HTTP_ORIGIN		71008
#define NKN_FP_DNS_QUEUE_FULL		71009

// URL Filtering Module
// URL Filtering reserves Error Numbers form 80001 to 80999
#define NKN_UF_CONN_RESET		80001
#define NKN_UF_CONN_CLOSE		80002
#define NKN_UF_HTTP_403_FORBIDDEN	80003
#define NKN_UF_HTTP_404_NOTFOUND	80004
#define NKN_UF_HTTP_301_REDIRECT_PERM	80005
#define NKN_UF_HTTP_302_REDIRECT	80006
#define NKN_UF_HTTP_200_WITH_BODY	80007
#define NKN_UF_CUSTOM_HTTP_RESPONSE	80008
#define NKN_UF_DROP_PKTS		80009
#define NKN_UF_URI_SIZE_CONN_RESET		80010
#define NKN_UF_URI_SIZE_CONN_CLOSE		80011
#define NKN_UF_URI_SIZE_HTTP_403_FORBIDDEN	80012
#define NKN_UF_URI_SIZE_HTTP_404_NOTFOUND	80013
#define NKN_UF_URI_SIZE_HTTP_301_REDIRECT_PERM	80014
#define NKN_UF_URI_SIZE_HTTP_302_REDIRECT	80015
#define NKN_UF_URI_SIZE_HTTP_200_WITH_BODY	80016
#define NKN_UF_URI_SIZE_CUSTOM_HTTP_RESPONSE	80017
// 
#define NKN_UF_MIN NKN_UF_CONN_RESET
#define NKN_UF_MAX NKN_UF_CUSTOM_HTTP_RESPONSE

// NFS Origin Manager Module
// NFS Module reserves Error Numbers from 90001 to 90999
#define NKN_NFS_STAT_URI_ERR            90001
#define NKN_NFS_GET_URI_ERR             90002
#define NKN_NFS_STAT_INV_OFFSET         90003
#define NKN_NFS_STAT_SERVER_BUSY        90004
#define NKN_NFS_GET_SERVER_BUSY         90005
#define NKN_NFS_AIO_RETURN_SERVER_BUSY  90006
#define NKN_NFS_VERSION_MISMATCH	90007
#define NKN_NFS_MOUNT_ERR		90008
#define NKN_NFS_METHOD_NOT_IMPLEMENTED	90009

// TFM Origin Manager Module
// TFM Module reserves Error Numbers from 91000 to 91999
//#define NKN_TFM_STAT_ERR                91001
//#define NKN_TFM_GET_ERR                 91002
//#define NKN_TFM_GET_LEN_ERR             91003
//#define NKN_TFM_GET_ATTR_ERR            91004
//#define NKN_TFM_GET_NAME_ERR            91005
//#define NKN_TFM_GET_MEM_ERR             91006
//#define NKN_TFM_GET_OBJ_ERR             91007
//#define NKN_TFM_GET_INCOMPLETE_ERR      91008
//#define NKN_TFM_GET_READ_ERR            91009
//#define NKN_TFM_STAT_OFF_ERR            91010

// AM module errors
#define NKN_AM_OBJ_NOT_FOUND		92001

// Cluster L7 (CL7) Module
// CL7 Module reserves Error Numbers from 93000 to 93999
#define NKN_CL7_RESPONSE_ERR		93000
#define NKN_CL7_LOCAL_PROC_ERR		93001
#define NKN_CL7_NO_NODES		93002
#define NKN_CL7_PROXY_ERR		93003

#define NKN_MAX_SUB_ERROR_CODE		100000

#endif
