#ifndef NKN_LOG_STRINGS_H
#define NKN_LOG_STRINGS_H

#define GEN_MSG 0
typedef struct {
  char MSG;
} OFF_GEN_MSG_t;
extern OFF_GEN_MSG_t gGEN_MSG;

#define NVSD_MAX_FD_SET 1
typedef struct {
  char MAX;
} OFF_NVSD_MAX_FD_SET_t;
extern OFF_NVSD_MAX_FD_SET_t gNVSD_MAX_FD_SET;

#define NVSD_SETSOCKOPT_FAILED 10
typedef struct {
  char CODE_LOCN;
} OFF_NVSD_SETSOCKOPT_FAILED_t;
extern OFF_NVSD_SETSOCKOPT_FAILED_t gNVSD_SETSOCKOPT_FAILED;

#define NVSD_BIND_FAILED 11
typedef struct {
  char CODE_LOCN;
} OFF_NVSD_BIND_FAILED_t;
extern OFF_NVSD_BIND_FAILED_t gNVSD_BIND_FAILED;

#define NVSD_ALREADY_RUNNING 12
typedef struct {
  char PID;
} OFF_NVSD_ALREADY_RUNNING_t;
extern OFF_NVSD_ALREADY_RUNNING_t gNVSD_ALREADY_RUNNING;

#define NKNVD_ALREADY_RUNNING 13
typedef struct {
  char PID;
} OFF_NKNVD_ALREADY_RUNNING_t;
extern OFF_NKNVD_ALREADY_RUNNING_t gNKNVD_ALREADY_RUNNING;

#define NVSD_MAX_FD_UNKNOWN 14
typedef struct {
  char REASON;
} OFF_NVSD_MAX_FD_UNKNOWN_t;
extern OFF_NVSD_MAX_FD_UNKNOWN_t gNVSD_MAX_FD_UNKNOWN;

#define NVSD_MAX_FD_NOT_SET 15
typedef struct {
  char REASON;
} OFF_NVSD_MAX_FD_NOT_SET_t;
extern OFF_NVSD_MAX_FD_NOT_SET_t gNVSD_MAX_FD_NOT_SET;

#define NVSD_RLIMIT_UNKNOWN 16
typedef struct {
  char REASON;
} OFF_NVSD_RLIMIT_UNKNOWN_t;
extern OFF_NVSD_RLIMIT_UNKNOWN_t gNVSD_RLIMIT_UNKNOWN;

#define NVSD_SCHEDULER_INIT_FAILED 17
typedef struct {
  char CODE_LOCN;
} OFF_NVSD_SCHEDULER_INIT_FAILED_t;
extern OFF_NVSD_SCHEDULER_INIT_FAILED_t gNVSD_SCHEDULER_INIT_FAILED;

#define NVSD_SHUTTING_DOWN 18
typedef struct {
  char CODE_LOCN;
} OFF_NVSD_SHUTTING_DOWN_t;
extern OFF_NVSD_SHUTTING_DOWN_t gNVSD_SHUTTING_DOWN;

#define NVSD_RATE_LIMIT_REACHED 19
typedef struct {
  char MAX_GET_RATE_LIMIT;
  char CUR_DATESTR;
} OFF_NVSD_RATE_LIMIT_REACHED_t;
extern OFF_NVSD_RATE_LIMIT_REACHED_t gNVSD_RATE_LIMIT_REACHED;

#define NVSD_MAX_FD_REDUCED 2
typedef struct {
  char MAX;
} OFF_NVSD_MAX_FD_REDUCED_t;
extern OFF_NVSD_MAX_FD_REDUCED_t gNVSD_MAX_FD_REDUCED;

#define NVSD_CONN_ARRAY_ALLOC_FAILED 20
typedef struct {
  char CODE_LOCN;
} OFF_NVSD_CONN_ARRAY_ALLOC_FAILED_t;
extern OFF_NVSD_CONN_ARRAY_ALLOC_FAILED_t gNVSD_CONN_ARRAY_ALLOC_FAILED;

#define NVSD_EVENT_STRUCT_ALLOC_FAILED 21
typedef struct {
  char CODE_LOCN;
} OFF_NVSD_EVENT_STRUCT_ALLOC_FAILED_t;
extern OFF_NVSD_EVENT_STRUCT_ALLOC_FAILED_t gNVSD_EVENT_STRUCT_ALLOC_FAILED;

#define NVSD_EPOLL_CREATE_FAILED 22
typedef struct {
  char CODE_LOCN;
} OFF_NVSD_EPOLL_CREATE_FAILED_t;
extern OFF_NVSD_EPOLL_CREATE_FAILED_t gNVSD_EPOLL_CREATE_FAILED;

#define NVSD_EPOLL_CTL_ADD_FAILED 23
typedef struct {
  char CODE_LOCN;
  char ERRNO;
} OFF_NVSD_EPOLL_CTL_ADD_FAILED_t;
extern OFF_NVSD_EPOLL_CTL_ADD_FAILED_t gNVSD_EPOLL_CTL_ADD_FAILED;

#define NVSD_EPOLL_WAIT_FAILED 24
typedef struct {
  char CODE_LOCN;
} OFF_NVSD_EPOLL_WAIT_FAILED_t;
extern OFF_NVSD_EPOLL_WAIT_FAILED_t gNVSD_EPOLL_WAIT_FAILED;

#define NVSD_TIMER_TASK_FAILED 25
typedef struct {
  char CODE_LOCN;
} OFF_NVSD_TIMER_TASK_FAILED_t;
extern OFF_NVSD_TIMER_TASK_FAILED_t gNVSD_TIMER_TASK_FAILED;

#define NVSD_EPOLL_INVAL_SOCK 26
typedef struct {
  char FD;
} OFF_NVSD_EPOLL_INVAL_SOCK_t;
extern OFF_NVSD_EPOLL_INVAL_SOCK_t gNVSD_EPOLL_INVAL_SOCK;

#define CM_URI_CANNOT_STAT 27
typedef struct {
  char URI_FILE_NAME;
} OFF_CM_URI_CANNOT_STAT_t;
extern OFF_CM_URI_CANNOT_STAT_t gCM_URI_CANNOT_STAT;

#define OM_ACCESS_URI 28
typedef struct {
  char URI_NAME;
  char CODE;
} OFF_OM_ACCESS_URI_t;
extern OFF_OM_ACCESS_URI_t gOM_ACCESS_URI;

#define NVSD_OOMGR_REQ_TASK_FAILED 29
typedef struct {
  char CODE_LOCN;
} OFF_NVSD_OOMGR_REQ_TASK_FAILED_t;
extern OFF_NVSD_OOMGR_REQ_TASK_FAILED_t gNVSD_OOMGR_REQ_TASK_FAILED;

#define NVSD_TASK_STILL_ACTIVE 3
typedef struct {
  char TID;
} OFF_NVSD_TASK_STILL_ACTIVE_t;
extern OFF_NVSD_TASK_STILL_ACTIVE_t gNVSD_TASK_STILL_ACTIVE;

#define NVSD_FMGR_REQ_TASK_FAILED 30
typedef struct {
  char CODE_LOCN;
} OFF_NVSD_FMGR_REQ_TASK_FAILED_t;
extern OFF_NVSD_FMGR_REQ_TASK_FAILED_t gNVSD_FMGR_REQ_TASK_FAILED;

#define NVSD_RECV_OVERFLOW 4
typedef struct {
  char CODE_LOCN;
} OFF_NVSD_RECV_OVERFLOW_t;
extern OFF_NVSD_RECV_OVERFLOW_t gNVSD_RECV_OVERFLOW;

#define NVSD_IDLE_TASK_CLOSED 5
typedef struct {
  char TID;
  char SID;
  char TIMEOUT;
} OFF_NVSD_IDLE_TASK_CLOSED_t;
extern OFF_NVSD_IDLE_TASK_CLOSED_t gNVSD_IDLE_TASK_CLOSED;

#define NVSD_MAX_FD_EXCEEDED 6
typedef struct {
  char MAX;
} OFF_NVSD_MAX_FD_EXCEEDED_t;
extern OFF_NVSD_MAX_FD_EXCEEDED_t gNVSD_MAX_FD_EXCEEDED;

#define NVSD_NON_BLOCK_FAILED 7
typedef struct {
  char CODE_LOCN;
} OFF_NVSD_NON_BLOCK_FAILED_t;
extern OFF_NVSD_NON_BLOCK_FAILED_t gNVSD_NON_BLOCK_FAILED;

#define NVSD_NON_IMPL 8
typedef struct {
  char CODE_LOCN;
} OFF_NVSD_NON_IMPL_t;
extern OFF_NVSD_NON_IMPL_t gNVSD_NON_IMPL;

#define NVSD_SOCKFD_FAILED 9
typedef struct {
  char CODE_LOCN;
} OFF_NVSD_SOCKFD_FAILED_t;
extern OFF_NVSD_SOCKFD_FAILED_t gNVSD_SOCKFD_FAILED;


#endif
