/*
 * nkn_mem_object_types.h -- Memory object type definitions
 */

/*
 *******************************************************************************
 * Naming convention: mod_[subsystem]_[object type]
 *******************************************************************************
 */
OBJ_TYPE(mod_unknown)

OBJ_TYPE(mod_nm_interface)

OBJ_TYPE(mod_sched_nkn_task)
OBJ_TYPE(mod_http_con_t)
OBJ_TYPE(mod_http_mgr_output_q_t)
OBJ_TYPE(mod_http_timer_req_q_t)
OBJ_TYPE(mod_http_cache_response_t)
OBJ_TYPE(mod_http_hash_entry_t)
OBJ_TYPE(mod_http_charbuf)
OBJ_TYPE(mod_http_name_value_t)
OBJ_TYPE(mod_http_heap_ext)
OBJ_TYPE(mod_http_hdrbuf)
OBJ_TYPE(mod_http_respbuf)
OBJ_TYPE(mod_http_om_respbuf)
OBJ_TYPE(mod_http_ipstr_table)
OBJ_TYPE(mod_http_ipstr)
OBJ_TYPE(mod_http_mime_header_t)
OBJ_TYPE(mod_http_uri_token_t)
OBJ_TYPE(mod_http_hit_history_t)

OBJ_TYPE(mod_httphdrs_serialbuf)

// MM allocations
OBJ_TYPE(mod_mm_provider_stat_t)
OBJ_TYPE(mod_mm_promote_put_data_t)
OBJ_TYPE(mod_mm_promote_get_data_t)
OBJ_TYPE(mod_mm_promote_put_move_mgr_t)
OBJ_TYPE(mod_mm_promote_get_move_mgr_t)
OBJ_TYPE(mod_mm_promote_cr_alloc)
OBJ_TYPE(mod_mm_promote_get_uri)
OBJ_TYPE(mod_mm_promote_put_uri)
OBJ_TYPE(mod_mm_promote_put_attr)
OBJ_TYPE(mod_mm_promote_get_attr)
OBJ_TYPE(mod_mm_am_obj_t)
OBJ_TYPE(mod_mm_strdup1)
OBJ_TYPE(mod_mm_strdup2)
OBJ_TYPE(mod_mm_strdup3)
OBJ_TYPE(mod_mm_strdup4)
OBJ_TYPE(mod_mm_uri_t)
OBJ_TYPE(mod_mm_put_data_t)
OBJ_TYPE(mod_mm_move_mgr_t)
OBJ_TYPE(mod_mm_cache_response_t)
OBJ_TYPE(mod_mm_posix_memalign)
OBJ_TYPE(mod_mm_promote_cfg_t)
OBJ_TYPE(mod_mm_promote_uri_strdup)
OBJ_TYPE(mod_mm_move_mgr_thrd_t)
OBJ_TYPE(mod_mm_delete_t)

OBJ_TYPE(mod_am_promote_thr_am_obj_t)
OBJ_TYPE(mod_am_tbl_create_am_obj)
OBJ_TYPE(mod_am_origin_tbl_create_am_obj)
OBJ_TYPE(mod_am_tbl_malloc_key)
OBJ_TYPE(mod_am_origin_tbl_malloc_key)
OBJ_TYPE(mod_am_list_malloc_key)
OBJ_TYPE(mod_am_lru_list_malloc_key)
OBJ_TYPE(mod_am_lru_list)
OBJ_TYPE(mod_am_key_string)
OBJ_TYPE(mod_am_strdup1)
OBJ_TYPE(mod_am_strdup2)
OBJ_TYPE(mod_am_strdup3)
OBJ_TYPE(mod_am_strdup4)
OBJ_TYPE(mod_am_strdup5)
OBJ_TYPE(mod_am_strdup6)
OBJ_TYPE(mod_am_strdup7)
OBJ_TYPE(mod_am_strdup8)
OBJ_TYPE(mod_am_test)
OBJ_TYPE(mod_am_object_data)

OBJ_TYPE(mod_nfs_server_map_cfg_file)
OBJ_TYPE(mod_nfs_filestr)
OBJ_TYPE(mod_nfs_mount_obj)
OBJ_TYPE(mod_nfs_mount_rem_obj_t)
OBJ_TYPE(mod_nfs_remotedir)
OBJ_TYPE(mod_nfs_localdir)
OBJ_TYPE(mod_nfs_remotehost)
OBJ_TYPE(mod_nfs_aio_buf)
OBJ_TYPE(mod_nfs_aio_aiocb)
OBJ_TYPE(mod_nfs_strdup1)
OBJ_TYPE(mod_nfs_strdup2)
OBJ_TYPE(mod_nfs_strdup3)
OBJ_TYPE(mod_nfs_strdup4)
OBJ_TYPE(mod_nfs_strdup5)
OBJ_TYPE(mod_nfs_strdup6)
OBJ_TYPE(mod_nfs_strdup7)
OBJ_TYPE(mod_nfs_strdup8)
OBJ_TYPE(mod_nfs_promote_cfg)
OBJ_TYPE(mod_nfs_get_cfg_ptr)
OBJ_TYPE(mod_nfs_test)

//OBJ_TYPE(mod_tfm_br)
//OBJ_TYPE(mod_tfm_attr1)
//OBJ_TYPE(mod_tfm_attr2)
//OBJ_TYPE(mod_tfm_mm_put_data)
//OBJ_TYPE(mod_tfm_mm_delete)
//OBJ_TYPE(mod_tfm_iov)
//OBJ_TYPE(mod_tfm_obj)
//OBJ_TYPE(mod_tfm_strdup1)
//OBJ_TYPE(mod_tfm_strdup2)
//OBJ_TYPE(mod_tfm_strdup3)
//OBJ_TYPE(mod_tfm_strdup4)
//OBJ_TYPE(mod_tfm_strdup5)
//OBJ_TYPE(mod_tfm_strdup6)
//OBJ_TYPE(mod_tfm_strdup7)
//OBJ_TYPE(mod_tfm_strdup8)
//OBJ_TYPE(mod_tfm_copy_nkn_attr_t)
//OBJ_TYPE(nkn_tfm_cht_obj)
//OBJ_TYPE(mod_tfm_promote_cfg)
//OBJ_TYPE(mod_tfm_test)

/* lib/nvsd/diskmgr2 */
OBJ_TYPE(mod_DM2_disk_attr_desc_t)
OBJ_TYPE(mod_DM2_extent_t)
OBJ_TYPE(mod_DM2_physid_head_t)
OBJ_TYPE(mod_DM2_uri_t)
OBJ_TYPE(mod_dm2_attr_read_buf_t)
OBJ_TYPE(mod_dm2_cache_buf_t)
OBJ_TYPE(mod_dm2_evict_node_t)
OBJ_TYPE(mod_dm2_ext_read_buf_t)
OBJ_TYPE(mod_dm2_cache_info_t)
OBJ_TYPE(mod_dm2_container_t)
OBJ_TYPE(mod_dm2_disk_container_t)
OBJ_TYPE(mod_dm2_disk_block_t)
OBJ_TYPE(mod_dm2_container_head_t)
OBJ_TYPE(mod_dm2_freelist_ext_t)
OBJ_TYPE(mod_dm2_ptype_mapper_t)
OBJ_TYPE(mod_dm2_uri_dir_t)
OBJ_TYPE(mod_dm2_uri_name_t)
OBJ_TYPE(mod_dm2_uri_int_evict)
OBJ_TYPE(mod_dm2_MM_stat_resp_t)
OBJ_TYPE(mod_dm2_MM_put_data_t)
OBJ_TYPE(mod_dm2_MM_get_resp_t)
OBJ_TYPE(mod_dm2_uri_t)
OBJ_TYPE(mod_dm2_strbuf)
OBJ_TYPE(mod_dm2_put_cfg_t)
OBJ_TYPE(mod_dm2_strdup)
OBJ_TYPE(mod_dm2_pthread_cond_t)
OBJ_TYPE(mod_dm2_posix_memalign)
OBJ_TYPE(mod_dm2_preread_cont_name)
OBJ_TYPE(mod_dm2_preread_arg_t)
OBJ_TYPE(mod_dm2_preread_hash)
OBJ_TYPE(mod_dm2_uri_lock_t)
OBJ_TYPE(mod_dm2_disk_slot_t)
OBJ_TYPE(mod_dm2_free_blk_map)

OBJ_TYPE(mod_uri_mgr_t)

OBJ_TYPE(mod_bm_cmpriv_t)
OBJ_TYPE(mod_bm_cache_req_t)
OBJ_TYPE(mod_bm_MM_get_resp_t)
OBJ_TYPE(mod_bm_MM_stat_resp_t)
OBJ_TYPE(mod_bm_nkn_reval_t)
OBJ_TYPE(mod_bm_nkn_sync_attr_t)
OBJ_TYPE(mod_bm_cr_uol_uri)
OBJ_TYPE(mod_bm_nkn_page_t)
OBJ_TYPE(mod_bm_page_pool_t)
OBJ_TYPE(mod_bm_nkn_del_t)

OBJ_TYPE(mod_vfs_nkn_cache_t)
OBJ_TYPE(mod_vfs_content_t)
OBJ_TYPE(mod_vfs_cache_response_t)
OBJ_TYPE(mod_vfs_con_t)

OBJ_TYPE(mod_ssp_prepend_data_t)
OBJ_TYPE(mod_ssp_session_t)
OBJ_TYPE(mod_ssp_sf_meta_data)
OBJ_TYPE(mod_ssp_mp4_rebased_seekheader_t)

OBJ_TYPE(mod_chunk_encoding_ctx_t)
OBJ_TYPE(mod_chunk_http_header_t)
OBJ_TYPE(mod_chunk_trailer_data)

OBJ_TYPE(mod_ns_map_t)
OBJ_TYPE(mod_ns_stat_t)
OBJ_TYPE(mod_ns_config_t)
OBJ_TYPE(mod_ns_ssp_config_t)
OBJ_TYPE(mod_ns_descriptor_t)
OBJ_TYPE(mod_ns_prefix_maps_t)
OBJ_TYPE(mod_ns_http_config_t)
OBJ_TYPE(mod_ns_cluster_config_t)
OBJ_TYPE(mod_ns_cl_suffix_node_t)
OBJ_TYPE(mod_ns_origin_server_NFS_t)
OBJ_TYPE(mod_ns_origin_server_HTTP_t)
OBJ_TYPE(mod_ns_origin_server_RTSP_t)
OBJ_TYPE(mod_ns_prefix_to_namespace_map_t)
OBJ_TYPE(mod_ns_nfs_server_map_node_data_t)
OBJ_TYPE(mod_ns_nstoken_to_uol_uri_outbuf)
OBJ_TYPE(mod_ns_comp_del_nfs_entries)
OBJ_TYPE(mod_ns_http_server_map)
OBJ_TYPE(mod_ns_ldn_http_server_map)
OBJ_TYPE(mod_ns_regex_int_hostname)
OBJ_TYPE(mod_ns_hostname_regex)
OBJ_TYPE(mod_ns_hostname)
OBJ_TYPE(mod_ns_uri_prefix)
OBJ_TYPE(mod_ns_query_name)
OBJ_TYPE(mod_ns_query_value)
OBJ_TYPE(mod_ns_namespace)
OBJ_TYPE(mod_ns_uid)
OBJ_TYPE(mod_ns_stat_t_name)
OBJ_TYPE(mod_ns_hash_entry_t)
OBJ_TYPE(mod_ns_hash_table_def_t)
OBJ_TYPE(mod_ns_server_map_name)
OBJ_TYPE(mod_ns_server_map_file_url)
OBJ_TYPE(mod_ns_hostname_path)
OBJ_TYPE(mod_ns_content_type)
OBJ_TYPE(mod_ns_max_age)
OBJ_TYPE(mod_ns_origin_ip_buf)
OBJ_TYPE(mod_ns_header_descriptor_t)
OBJ_TYPE(mod_ns_header_name)
OBJ_TYPE(mod_ns_header_value)
OBJ_TYPE(mod_ns_uri_regex)
OBJ_TYPE(mod_ns_uid_list)
OBJ_TYPE(mod_ns_uid_strdup)
OBJ_TYPE(mod_ns_query_regex)
OBJ_TYPE(mod_ns_header_regex)
OBJ_TYPE(mod_ns_pub_point_config_t)
OBJ_TYPE(mod_ns_pub_point_t)
OBJ_TYPE(mod_ns_node_map_descriptor_t)
OBJ_TYPE(mod_ns_node_map_private_data_descriptor_t)
OBJ_TYPE(mod_ns_cluster_hash_config_t)
OBJ_TYPE(mod_ns_cluster_descriptor_t)
OBJ_TYPE(mod_ns_cluster_desc_nodeid_map_t)
OBJ_TYPE(mod_ns_custom_cache_control)
OBJ_TYPE(mod_ns_cache_pin_config_t)
OBJ_TYPE(mod_ns_cache_pin_header)
OBJ_TYPE(mod_ns_cache_pin_end_header)
OBJ_TYPE(mod_ns_cache_pin_start_header)
OBJ_TYPE(mod_ns_base_redir_path)
OBJ_TYPE(mod_ns_intercept_key)
OBJ_TYPE(mod_ns_stat_entry_t)
OBJ_TYPE(mod_ns_stat_hash)
OBJ_TYPE(mod_ns_physid_hash)
OBJ_TYPE(mod_ns_cp_physid_hash)
OBJ_TYPE(mod_ns_ldn_name_buf)
OBJ_TYPE(mod_ns_reval_header_buf)
OBJ_TYPE(mod_ns_dynamic_uri_regex)
OBJ_TYPE(mod_ns_dynamic_uri_mapping_string)
OBJ_TYPE(mod_ns_dynamic_uri_tokenize_string)
OBJ_TYPE(mod_ns_seek_uri_regex)
OBJ_TYPE(mod_ns_seek_uri_mapping_string)

OBJ_TYPE(mod_nsd_intercept_handler_t)
OBJ_TYPE(mod_ns_tmp_ns_node_data_t)
OBJ_TYPE(mod_ns_node_data_host)
OBJ_TYPE(mod_ns_cl7_ns_name)
OBJ_TYPE(mod_ns_cl7_ns_uid)

/* for nvsd/file_manager.c */
OBJ_TYPE(mod_fm_filename_t)
OBJ_TYPE(mod_fm_posix_memalign)

/* for nvsd/fuse_wrapper.c */
OBJ_TYPE(mod_fuse_context_t)
OBJ_TYPE(mod_fuse_strdup1)

OBJ_TYPE(mod_fq_pseudo_con_t)
OBJ_TYPE(mod_fq_cache_response_t)
OBJ_TYPE(mod_fq_TFM_put_privatedata_t)
OBJ_TYPE(mod_fq_MM_put_data_t)
OBJ_TYPE(mod_fq_strdup1)


OBJ_TYPE(mod_nm_network_mgr_t)
OBJ_TYPE(mod_nm_epoll_event_t)
OBJ_TYPE(mod_nm_trace_t)

OBJ_TYPE(mod_nkn_shmdef_t)
OBJ_TYPE(mod_nkn_sched_threads)
OBJ_TYPE(mod_nkn_obj_t)

OBJ_TYPE(mod_dm_LM_file_t)
OBJ_TYPE(mod_dm_LM_extent_t)
OBJ_TYPE(mod_dm_uri_t)
OBJ_TYPE(mod_dm_iovec_t)
OBJ_TYPE(mod_dm_strbuf)

OBJ_TYPE(mod_trace_rect_t)

OBJ_TYPE(mod_mgmt_dm2_mgmt_db_info_t)
OBJ_TYPE(mod_mgmt_charbuf)
OBJ_TYPE(mod_mgmt_posix_memalign)
OBJ_TYPE(mod_mgmta_charbuf)

OBJ_TYPE(mod_fp_fpevent_q)
OBJ_TYPE(mod_fp_send_req_buf)

OBJ_TYPE(mod_om_network_cb)
OBJ_TYPE(mod_om_fpevent_q)
OBJ_TYPE(mod_om_send_req_buf)
OBJ_TYPE(mod_om_fpcon_t)
OBJ_TYPE(mod_om_cpcon_t)
OBJ_TYPE(mod_om_socket_pool_t)
OBJ_TYPE(mod_om_resp_buf_t)
OBJ_TYPE(mod_om_sceq_q_t)
OBJ_TYPE(mod_om_ocon_t)
OBJ_TYPE(mod_om_ocon_serialbuf)
OBJ_TYPE(mod_om_TFM_put_privatedata_t)
OBJ_TYPE(mod_om_MM_put_data_t)
OBJ_TYPE(mod_om_pending_req_t)
OBJ_TYPE(mod_om_strdup1)
OBJ_TYPE(mod_om_strdup2)
OBJ_TYPE(mod_om_strdup3)
OBJ_TYPE(mod_om_strdup4)
OBJ_TYPE(mod_om_strdup5)
OBJ_TYPE(mod_om_strdup6)
OBJ_TYPE(mod_om_strdup7)
OBJ_TYPE(mod_om_hostname)
OBJ_TYPE(mod_om_oomgr_req)
OBJ_TYPE(mod_om_pending_req_t_uri)

OBJ_TYPE(mod_vpe_nkn_bitstream_t)
OBJ_TYPE(mod_vpe_refcount_t)
OBJ_TYPE(mod_vpe_io_hdlr_t)
OBJ_TYPE(mod_vpe_thread_pool_t)
OBJ_TYPE(mod_vpe_charbuf)
OBJ_TYPE(mod_vpe_http_reader_t)
OBJ_TYPE(mod_vpe_tfhd_t)
OBJ_TYPE(mod_vpe_trun_t)
OBJ_TYPE(mod_vpe_tkhd_t)
OBJ_TYPE(mod_vpe_parser_state)
OBJ_TYPE(mod_vpe_io_funcs)
OBJ_TYPE(mod_vpe_trun_stable_t)
OBJ_TYPE(mod_vpe_asf_header_obj_t)
OBJ_TYPE(mod_vpe_asf_file_prop_obj_t)
OBJ_TYPE(mod_vpe_webm_segment_t)
OBJ_TYPE(mod_vpe_webm_segment_info_t)
OBJ_TYPE(mod_vpe_webm_traks_t)
OBJ_TYPE(mod_vpe_webm_trak_entry)
OBJ_TYPE(mod_vpe_webm_mem)
OBJ_TYPE(mod_vpe_flv_parser_t)
OBJ_TYPE(mod_vpe_flv_meta_tag_modifer_t)
OBJ_TYPE(mod_vpe_flv_avcc_buf)
OBJ_TYPE(mod_vpe_flv_generic_buf)
OBJ_TYPE(mod_vpe_ismc_psi_t)
OBJ_TYPE(mod_vpe_ismc_av_attr_t)
OBJ_TYPE(mod_vpe_ismc_cust_attr_t)
/* handle mp4 with moov box not present in first 32KB */
OBJ_TYPE(mod_vpe_mp4_find_box_parser_t)
OBJ_TYPE(mod_vpe_mp4_box_hd_t)
OBJ_TYPE(mod_vpe_mp4_box_find_list_t)
OBJ_TYPE(mod_vpe_mp4_data_span_t)
OBJ_TYPE(mod_vpe_mp4_box_info_t)
/* end */
OBJ_TYPE(mod_vpe_mp4_udta_buf)
OBJ_TYPE(mod_vpe_mp4_box_data)
OBJ_TYPE(mod_vpe_mp4_moov_t)
OBJ_TYPE(mod_vpe_mp4_moov_buf)
OBJ_TYPE(mod_vpe_mp4_mfra_t)
OBJ_TYPE(mod_vpe_mp4_udta_t)
OBJ_TYPE(mod_vpe_mp4_stbl_t)
OBJ_TYPE(mod_vpe_mp4_trak_t)
OBJ_TYPE(mod_vpe_mp4_mdia_t)
OBJ_TYPE(mod_vpe_mp4_generic_buf)
OBJ_TYPE(mod_vpe_mp4_tfra_t)
OBJ_TYPE(mod_vpe_mp4_tfra_table_t)
OBJ_TYPE(mod_vpe_mp4_mdhd_t)
OBJ_TYPE(mod_vpe_mp4_mvhd_t)
OBJ_TYPE(mod_vpe_mp4_tfhd_t)     
OBJ_TYPE(mod_vpe_mp4_hdlr_t)
OBJ_TYPE(mod_vpe_mp4_hdlr_buf)
OBJ_TYPE(mod_vpe_mp4_stsd_t)
OBJ_TYPE(mod_vpe_mp4_stsz_t)
OBJ_TYPE(mod_vpe_mp4_stsz_entries)
OBJ_TYPE(mod_vpe_mp4_stsc_t)
OBJ_TYPE(mod_vpe_mp4_stsc_entries)
OBJ_TYPE(mod_vpe_mp4_vse_t)
OBJ_TYPE(mod_vpe_mp4_ase_t)
OBJ_TYPE(mod_vpe_mp4_stco_t)
OBJ_TYPE(mod_vpe_mp4_stco_entries)
OBJ_TYPE(mod_vpe_mp4_trun_t)
OBJ_TYPE(mod_vpe_mp4_trun_entries)
OBJ_TYPE(mod_vpe_mp4_tkhd_t)
OBJ_TYPE(mod_vpe_ism_map_t)
OBJ_TYPE(mod_vpe_ism_buf)
OBJ_TYPE(mod_vpe_ism_cust_attr_t)
OBJ_TYPE(mod_vpe_ism_av_attr_t)
OBJ_TYPE(mod_vpe_xml_read_ctx_t)
OBJ_TYPE(mod_vpe_ismv_parser_ctx_t)
OBJ_TYPE(mod_vpe_media_detector_ctx_t)
OBJ_TYPE(mod_vpe_media_props_t)
OBJ_TYPE(mod_vpe_rtp_pkt_buf)
OBJ_TYPE(mod_vpe_mp4_esds_buf)
OBJ_TYPE(mod_vpe_rtp_sdp_buf)
OBJ_TYPE(mod_vpe_rtp_generic_buf)
OBJ_TYPE(mod_vpe_rtp_nal_buf)
OBJ_TYPE(mod_vpe_mpeg4_es_desc_t)
OBJ_TYPE(mod_vpe_mpeg4_decoder_config_t)
OBJ_TYPE(mod_vpe_mpeg4_auh_t)
OBJ_TYPE(mod_vpe_mpeg4_slc_t)
OBJ_TYPE(mod_vpe_mpeg4_generic)
OBJ_TYPE(mod_vpe_m4a_generic)
OBJ_TYPE(mod_vpe_ismv2ts_builder_t)
OBJ_TYPE(mod_vpe_ismv2iphone_convert)
OBJ_TYPE(mod_aud_data_buffer)
OBJ_TYPE(mod_ismv_moof_proc_buf_t)
OBJ_TYPE(mod_vpe_ismv2ts_converter_ctx_t)
OBJ_TYPE(mod_ismv2moof_converter_ctx_t)
OBJ_TYPE(mod_mfu_desc)
OBJ_TYPE(mod_ismv_moof_builder_t)
OBJ_TYPE(mod_vpe_ismv2moof_write_t)
OBJ_TYPE(mod_file_conv_ip_params_t)
OBJ_TYPE(mod_vpe_ismv2moof_write_array_t)
OBJ_TYPE(mod_vpe_moof_array_t)
OBJ_TYPE(mod_vpe_mfu_array_t)
OBJ_TYPE(mod_vpe_moof2mfu_converter_ctx_t)
OBJ_TYPE(mod_vpe_moof2mfu_builder_t)
OBJ_TYPE(mod_vpe_moof2mfu_write_array_t)
OBJ_TYPE(mod_vpe_mfu2ts_converter_ctx_t)
OBJ_TYPE(mod_vpe_mfu2ts_builder_t)
OBJ_TYPE(mod_vpe_unit_desc_t)
OBJ_TYPE(mod_vpe_aud_raw_data)
OBJ_TYPE(mod_vpe_vid_raw_data)
OBJ_TYPE(mod_vpe_enc_data)
OBJ_TYPE(mod_vpe_videofg_buf)
OBJ_TYPE(mod_vpe_audiofg_buf)
OBJ_TYPE(mod_vpe_vid_sample_dur_buf)
OBJ_TYPE(mod_vpe_vid_sam_size_buf)
OBJ_TYPE(mod_vpe_aud_sample_dur_buf)
OBJ_TYPE(mod_vpe_aud_sam_size_buf)
OBJ_TYPE(mod_vpe_file_name_buffer)
OBJ_TYPE(mod_vpe_pat_data_buf)
OBJ_TYPE(mod_vpe_pmt_data_buf)
OBJ_TYPE(mod_vpe_pat_t)
OBJ_TYPE(mod_vpe_pmt_t)
OBJ_TYPE(mod_vpe_stream_t)
OBJ_TYPE(mod_vpe_ts_pkt_t)
OBJ_TYPE(mod_vpe_aud_ts_pkt_list_t)
OBJ_TYPE(mod_vpe_vid_ts_pkt_list_t)
OBJ_TYPE(mod_vpe_aud_ts_pkt_buf)
OBJ_TYPE(mod_vpe_residual_size_aud)
OBJ_TYPE(mod_vpe_pktlist_data_buf)
OBJ_TYPE(mod_vpe_pes_fields_t)
OBJ_TYPE(mod_vpe_pes_data)
OBJ_TYPE(mod_vpe_aac_header_buf)
OBJ_TYPE(mod_vpe_pktlist_vid_data_buf)
OBJ_TYPE(mod_vpe_mfu_AU_t)
OBJ_TYPE(mod_vpe_pld_pkt_t)
OBJ_TYPE(mod_vpe_adapt_field_t)
OBJ_TYPE(mod_vpe_stream_AVC_conf_Record_t)
OBJ_TYPE(mod_vpe_avcC_data)
OBJ_TYPE(mod_vpe_stream_param_sets_t)
OBJ_TYPE(mod_vpe_sps_pps_param_set)
OBJ_TYPE(mod_vpe_moov_data_buf)
OBJ_TYPE(mod_vpe_stsd_buf)
OBJ_TYPE(mod_vpe_videofg_codec_specific_data)
OBJ_TYPE(mod_vpe_tot_NAL_buf)
OBJ_TYPE(mod_vpe_NAL_buf)
OBJ_TYPE(mod_vpe_aud_sync_table)
OBJ_TYPE(mod_vpe_vid_sync_table)
OBJ_TYPE(mod_vpe_chunk_data)
OBJ_TYPE(mod_vpe_aud_sample_prop_table)
OBJ_TYPE(mod_vpe_vid_sample_prop_table)
OBJ_TYPE(mod_vpe_ts2mfu_cont_t)
/*Live Items*/
OBJ_TYPE(mod_vpe_pkt_offsets_t)
OBJ_TYPE(mod_vpe_sess_stream_id_t)
OBJ_TYPE(mod_vpe_mfp_ts2mfu_t1)
OBJ_TYPE(mod_vpe_temp_t)
OBJ_TYPE(mod_vpe_temp1_t)
OBJ_TYPE(mod_vpe_temp2_t)
OBJ_TYPE(mod_vpe_temp_t1)
OBJ_TYPE(mod_vpe_temp_t2)
OBJ_TYPE(mod_vpe_temp_t23)
OBJ_TYPE(mod_vpe_gbl_fruit_ctx_t)
OBJ_TYPE(mod_vpe_fruit_stream_t)
OBJ_TYPE(mod_vpe_ts_desc_t)
OBJ_TYPE(mod_vpe_mfub_t)
OBJ_TYPE(mod_vpe_mfu_data_t)
OBJ_TYPE(mod_vpe_mfu_data_t1)
OBJ_TYPE(mod_vpe_mfu_data_t2)
OBJ_TYPE(mod_vpe_mfu_data_t3)
OBJ_TYPE(mod_vpe_mfu_data_t4)
OBJ_TYPE(mod_vpe_mfu_data_t5)
OBJ_TYPE(mod_vpe_ts2mfu_desc_t)
OBJ_TYPE(mod_mfp_dir_watch_obj_t)
OBJ_TYPE(mod_vpe_mfp_ts2mfu_t)
OBJ_TYPE(mod_vpe_mfp_aligner_t)
OBJ_TYPE(mod_vpe_mfu_data_buf)
OBJ_TYPE(mod_vpe_mfu_rwfg_t)
OBJ_TYPE(mod_vpe_mfu_raw_box_vid_buf)
OBJ_TYPE(mod_vpe_h264_parser_t)
OBJ_TYPE(mod_vpe_mfp_accum_ts)
OBJ_TYPE(mod_vpe_mfp_mfu_parser)
OBJ_TYPE(mod_vpe_mfp_latm_parser)
OBJ_TYPE(mod_vpe_mfp_fruit_fmt_input_t)
OBJ_TYPE(mod_vpe_mfp_fruit_encrypt_props_t)
OBJ_TYPE(mod_vpe_vid_PTS)
OBJ_TYPE(mod_vpe_vdat_buf)
OBJ_TYPE(mod_vpe_mfu_raw_box_aud_buf)
OBJ_TYPE(mod_vpe_aud_PTS)
OBJ_TYPE(mod_vpe_adat_buf)
OBJ_TYPE(mod_vpe_ts_data_buf)
OBJ_TYPE(mod_vpe_moof2mfu_desc_t)
OBJ_TYPE(mod_vpe_adts)
OBJ_TYPE(mod_vpe_mfra_data_buf)
OBJ_TYPE(mod_vpe_moof_temp_buf)
OBJ_TYPE(mod_vpe_moof_temp_buf1)
OBJ_TYPE(mod_vpe_moof_temp_buf2)
OBJ_TYPE(mod_vpe_moof_temp_buf3)
OBJ_TYPE(mod_vpe_moof_temp_buf4)
OBJ_TYPE(mod_vpe_moof_data_vid_buf)
OBJ_TYPE(mod_vpe_moof_data_aud_buf)
OBJ_TYPE(mod_vpe_mdat_desc_t)
OBJ_TYPE(mod_vpe_sam_dur)
OBJ_TYPE(mod_vpe_sam_size)
OBJ_TYPE(mod_vpe_ismv_reader_t)
OBJ_TYPE(mod_vpe_media_buffer)
OBJ_TYPE(mod_vpe_media_buffer1)
OBJ_TYPE(mod_vpe_media_buffer2)
OBJ_TYPE(mod_vpe_ol_t)
OBJ_TYPE(mod_vpe_ts2iphone_converter_ctx_t)
OBJ_TYPE(mod_vpe_ts_segmenter_ctx_t)
OBJ_TYPE(mod_vpe_ts2iphone_builder_t)
OBJ_TYPE(mod_vpe_ts_tplay_parser)
OBJ_TYPE(mod_vpe_ts_segment_writer_t)
OBJ_TYPE(mod_vpe_afra_t)
OBJ_TYPE(mod_vpe_f4v_frag_access_ctx_t)
OBJ_TYPE(mod_vpe_f4v_seg_t)
OBJ_TYPE(mod_mp42anyforamt_converter_ctx_t)
OBJ_TYPE(mod_vpe_discont_t)
OBJ_TYPE(mod_vpe_moov_buf)
OBJ_TYPE(mod_vpe_mp4_parser_ctx_t)
OBJ_TYPE(mod_mp4_mfu_builder_t)
OBJ_TYPE(mod_vpe_vid_chunk_data)
OBJ_TYPE(mod_vpe_aud_chunk_data)
OBJ_TYPE(mod_vpe_sample_detail_t)
OBJ_TYPE(mod_vpe_sample_prop_t)
OBJ_TYPE(mod_vpe_sample_desc_t)
OBJ_TYPE(mod_ts2anyforamt_converter_ctx_t)
OBJ_TYPE(mod_ts_mfu_builder_t)
OBJ_TYPE(mod_ts_data_t)
OBJ_TYPE(mod_chunk_desc_t)
OBJ_TYPE(mod_vpe_offsets_t)
OBJ_TYPE(mod_vpe_chunk_desc_t)
OBJ_TYPE(mod_vpe_mfu_hdr)
OBJ_TYPE(mod_vpe_http_sync_open)
OBJ_TYPE(mod_vpe_mfp_merge_t)
OBJ_TYPE(mod_vpe_mfp_merge_t2)

OBJ_TYPE(mod_slot_mgr)
OBJ_TYPE(mod_slot_item)

OBJ_TYPE(mod_dns_entry)
OBJ_TYPE(mod_dns_ip_entry)
OBJ_TYPE(mod_ip_list_head)
OBJ_TYPE(mod_ns_content_type_max_age_t_list)
OBJ_TYPE(mod_ns_content_type_max_age_t)

OBJ_TYPE(mod_network_cb)
OBJ_TYPE(mod_reg_regex_t)


/* Server Side Player type defn */
OBJ_TYPE(mod_ssp_cli_strdup)
OBJ_TYPE(mod_ssp_sf_avcc_cfg)
OBJ_TYPE(mod_vpe_vpemgr_queue)
OBJ_TYPE(mod_vpe_mp4_meta_parser)
OBJ_TYPE(mod_vpe_flv_meta_parser)
OBJ_TYPE(mod_ssp_smoothstream_pub_t)
OBJ_TYPE(mod_ssp_flashstream_pub_t)

/*Auth Mgr obj types*/
OBJ_TYPE(mod_auth_loc_tbl_t)
OBJ_TYPE(mod_auth_msg_t)
OBJ_TYPE(mod_auth_uchar)
OBJ_TYPE(mod_auth_addrttl)
OBJ_TYPE(mod_auth_addr6ttl)
OBJ_TYPE(mod_kms_info_t)
OBJ_TYPE(mod_dns_pendq)

/*PE Mgr obj types*/
OBJ_TYPE(mod_pe_pendq)
OBJ_TYPE(mod_geo_info_t)
OBJ_TYPE(mod_ucflt_info_t)

/* Enc Mgr obj types */
OBJ_TYPE(mod_enc_msg_t)

/* Publish Point type definitions */
OBJ_TYPE(mod_pub_point_cli_strdup)

OBJ_TYPE(mod_pcon_pcon_t)
OBJ_TYPE(mod_default_pcon_pcon_t)
OBJ_TYPE(mod_normalize_pcon_pcon_t)
OBJ_TYPE(mod_pseudo_con_host_hdr)

OBJ_TYPE(mod_cod_cn)
OBJ_TYPE(mod_cod_entry_t)
OBJ_TYPE(mod_cod_head_t)
OBJ_TYPE(mod_con_hash_t)

OBJ_TYPE(mod_sched_tmout_obj)
OBJ_TYPE(mod_rtsched_nkn_task)
OBJ_TYPE(mod_rtsched_tmout_obj)
OBJ_TYPE(mod_sched_mm_thread_t)


OBJ_TYPE(mod_net_arp_table_t)
OBJ_TYPE(mod_log_al_info)
OBJ_TYPE(mod_log_sl_info)
OBJ_TYPE(mod_log_channel_mgr)
OBJ_TYPE(mod_main)
OBJ_TYPE(mod_test)
OBJ_TYPE(mod_channel_mgr)
OBJ_TYPE(mod_mm_mem_pool_1)
OBJ_TYPE(mod_mm_mem_pool_2)
OBJ_TYPE(mod_tfm_file_id_list)

OBJ_TYPE(mod_rtsp_ls_cfg_pp_strdup)
OBJ_TYPE(mod_rtsp_parser_ah_strdup)
OBJ_TYPE(mod_rtsp_rl_setup_strdup)
OBJ_TYPE(mod_rtsp_rl_urlp_strdup)
OBJ_TYPE(mod_rtsp_ses_nsms_strdup)
OBJ_TYPE(mod_rtsp_ses_gsdp_strdup)
OBJ_TYPE(mod_rtsp_ses_hd_strdup)
OBJ_TYPE(mod_rtsp_ses_hs_strdup)
OBJ_TYPE(mod_rtsp_ses_hp_strdup)
OBJ_TYPE(mod_rtsp_vs_cfg_strdup)
OBJ_TYPE(mod_rtsp_rtcp_nsd_malloc)
OBJ_TYPE(mod_rtsp_rtcp_nri_malloc)
OBJ_TYPE(mod_rtsp_rtcp_ntsr_malloc)
OBJ_TYPE(mod_rtsp_rtcph_aa_malloc)
OBJ_TYPE(mod_rtsp_rtcph_nopb_malloc)
OBJ_TYPE(mod_rtsp_rtcph_armdb_malloc)
OBJ_TYPE(mod_rtsp_rtcph_rcn_malloc)
OBJ_TYPE(mod_rtsp_rtcph_rsrrh_malloc)
OBJ_TYPE(mod_rtsp_ls_cfg_pp_malloc)
OBJ_TYPE(mod_rtsp_parser_prih_malloc)
OBJ_TYPE(mod_rtsp_parser_pth_malloc)
OBJ_TYPE(mod_rtsp_parser_pah_malloc)
OBJ_TYPE(mod_rtsp_rl_rlmr_malloc)
OBJ_TYPE(mod_rtsp_rl_rmd_malloc)
OBJ_TYPE(mod_rtsp_rl_gpc_malloc)
OBJ_TYPE(mod_rtsp_sh_sne_malloc)
OBJ_TYPE(mod_rtsp_ses_ru_malloc)
OBJ_TYPE(mod_rtsp_ses_nsms_malloc)
OBJ_TYPE(mod_rtsp_ses_gsd_malloc)
OBJ_TYPE(mod_rtsp_ses_hs_malloc)
OBJ_TYPE(mod_rtsp_ses_hp_malloc)
OBJ_TYPE(mod_rtsp_ses_np_malloc)
OBJ_TYPE(mod_rtsp_soc_ng_malloc)
OBJ_TYPE(mod_rtsp_soc_ad_malloc)
OBJ_TYPE(mod_rtsp_soc_rsr_malloc)
OBJ_TYPE(mod_rtsp_vs_cfg_malloc)
OBJ_TYPE(mod_rtsp_om_malloc)
OBJ_TYPE(mod_rtsp_om_strdup)
OBJ_TYPE(mod_rtsp_sock_malloc)
OBJ_TYPE(mod_rtsp_rl_sdp_malloc)
OBJ_TYPE(mod_rtsp_type_1)
OBJ_TYPE(mod_rtsp_type_2)
OBJ_TYPE(mod_rtsp_type_3)
OBJ_TYPE(mod_rtsp_type_4)
OBJ_TYPE(mod_rtsp_url_presuffix)
OBJ_TYPE(mod_rtsp_orp_malloc)
OBJ_TYPE(mod_rtsp_outbuf_malloc)
OBJ_TYPE(mod_rtsp_tunnel_cache_name)
OBJ_TYPE(mod_rtsp_ps_list)

OBJ_TYPE(mod_mem_thread_pool)
OBJ_TYPE(mod_net_timer_data)

OBJ_TYPE(mod_cl_node_map_descriptor)
OBJ_TYPE(mod_cl_cluster_map_bin)
OBJ_TYPE(mod_cl_cluster_map_private_t)
OBJ_TYPE(mod_cl_cluster_map_node_t)

OBJ_TYPE(mod_cl_origin_escalation_map_bin)
OBJ_TYPE(mod_cl_origin_escalation_map_private_t)
OBJ_TYPE(mod_cl_origin_escalation_map_node_t)
OBJ_TYPE(mod_cl_origin_escalation_respcodes)

OBJ_TYPE(mod_cl_origin_roundrobin_map_bin)
OBJ_TYPE(mod_cl_origin_roundrobin_map_private_t)
OBJ_TYPE(mod_cl_origin_roundrobin_map_node_t)

OBJ_TYPE(mod_cl_noload_cluster_map_private_t)
OBJ_TYPE(mod_cl_load_cluster_map_private_t)
OBJ_TYPE(mod_cl_load_cluster_map_task_private_t)
OBJ_TYPE(mod_cl_node_handle)

OBJ_TYPE(mod_cl_node_host_port)
OBJ_TYPE(mod_cl_node_heartbeatpath)
OBJ_TYPE(mod_cl_filename)
OBJ_TYPE(mod_cl_cname)
OBJ_TYPE(mod_cl_stat_t)
OBJ_TYPE(mod_cl_stat_t_name)

OBJ_TYPE(mod_cl_cmm_req_t)
OBJ_TYPE(mod_cmm_req_str)

/* MFP mem obj types */
OBJ_TYPE(mod_mfp_pmf_data)
OBJ_TYPE(mod_mfp_file_pump)
OBJ_TYPE(mod_mfp_pmf_ctx)
OBJ_TYPE(mod_mfp_disp)
OBJ_TYPE(mod_mfp_live_thread_pool)
OBJ_TYPE(mpd_mfp_pmf_proc_mgr_t)
OBJ_TYPE(mod_mfp_fconv_tpool_obj_t)
OBJ_TYPE(mod_mfp_sl_fmtr)
OBJ_TYPE(mod_mfp_zeri_fmtr)
OBJ_TYPE(mod_mfp_sync_ser)
OBJ_TYPE(mod_mfp_event_timer)
OBJ_TYPE(mod_mfp_apple_io)
OBJ_TYPE(mod_mfp_io_hdlr)
OBJ_TYPE(mod_mfp_kms)
OBJ_TYPE(mod_mfp_kms_key_resp_t)
OBJ_TYPE(mod_mfp_pmf_resp_data)
OBJ_TYPE(mod_mfp_live_sess_mgr_cont)
OBJ_TYPE(mod_mfp_mgmt_sess_tbl_add)
OBJ_TYPE(mod_mfp_convert_pmf)

/* Policy Engine */
OBJ_TYPE(mod_pe_ns_file_name)
OBJ_TYPE(mod_pe_ns_srvr_list_t)
OBJ_TYPE(mod_pe_ns_srvr_t)
OBJ_TYPE(mod_pe_ns_srvr_name)
OBJ_TYPE(mod_pe_policy_buf)
OBJ_TYPE(mod_pe_ilist_t)
OBJ_TYPE(mod_pe_rules_t)
OBJ_TYPE(mod_pe_co_t)
OBJ_TYPE(mod_pe_co_list_t)
OBJ_TYPE(mod_pe_co_str)
OBJ_TYPE(mod_pe_geo_ip_req_t)
OBJ_TYPE(mod_pe_geo_ip_t)
OBJ_TYPE(mod_pe_req_q_t)
OBJ_TYPE(mod_pe_con_info_t)
OBJ_TYPE(mod_pe_ucflt_req_t)
OBJ_TYPE(mod_pe_transmit_rate_t)


/* Hash table entries */
OBJ_TYPE(mod_om_con_by_uri_t)
OBJ_TYPE(mod_om_con_by_fd_t)

OBJ_TYPE(mod_portmap_table_t)
OBJ_TYPE(mod_pmapper_t)
OBJ_TYPE(mod_portmap_t)
OBJ_TYPE(mod_conn_entry_t)

/* rw queue */
OBJ_TYPE(mod_rw_queue_t)
/*
 * Added for BUG FIX 7092
 * Nvsd to DM2 parameter.Used for passing arguments through thread function.
 * */
OBJ_TYPE(mod_nvsd_dm2_parameters_t)

/* NFS Tunnel */
OBJ_TYPE(mod_nfst_response_t)
OBJ_TYPE(mod_nfst_xfer_buf_t)
OBJ_TYPE(mod_nfst_filename)
OBJ_TYPE(mod_nfst_priv_data)

OBJ_TYPE(mod_acclog_profile)
OBJ_TYPE(mod_ns_accesslog_config)
OBJ_TYPE(mod_ns_access_log)

/* Crawler */
/* CIM */
OBJ_TYPE(mod_cim_cod)
OBJ_TYPE(mod_cim_bufptr)
OBJ_TYPE(mod_cim_statptr)

/* CCP */
OBJ_TYPE(mod_ccp_epoll)
OBJ_TYPE(mod_ccp_client_ctxt)
OBJ_TYPE(mod_ccp_url_st)
OBJ_TYPE(mod_ccp_url)
OBJ_TYPE(mod_ccp_client_domain)
OBJ_TYPE(mod_ccp_crawl_name)
OBJ_TYPE(mod_ccp_etag)
OBJ_TYPE(mod_ccp_module)
OBJ_TYPE(mod_ccp_data)
OBJ_TYPE(mod_ccp_recvbuf)
OBJ_TYPE(mod_ccp_inoutdata)
OBJ_TYPE(mod_ccp_server_ctxt)
OBJ_TYPE(mod_ccp_xml)

/* ICCP */
OBJ_TYPE(mod_iccp_msg)
OBJ_TYPE(mod_iccp_info)
OBJ_TYPE(mod_iccp_tlv)
OBJ_TYPE(mod_iccp_epoll)

/* CSE */
OBJ_TYPE(mod_cse_ctxt)
OBJ_TYPE(mod_cse_url)
OBJ_TYPE(mod_cse_etag)
OBJ_TYPE(mod_ns_host_hdr_buf)

/* virt cache ctrl prot msgs types*/
OBJ_TYPE(mod_vccmp_stat_data_t)

/* virt cache server types*/
OBJ_TYPE(mod_vcs_strdup_t)
OBJ_TYPE(mod_vcs_path_str)
OBJ_TYPE(mod_vcs_stat_req_t)
OBJ_TYPE(mod_vcs_open_req_t)
OBJ_TYPE(mod_vcs_vccmp_query_slot_rsp_msg_t)
OBJ_TYPE(mod_vcs_nkn_vc_slot_t)
OBJ_TYPE(mod_vcs_channel_fmt_str)

OBJ_TYPE(mod_om_md5_context)
/* CR-DNS objects */
OBJ_TYPE(mod_dns_builder_buf)
OBJ_TYPE(mod_dns_parser_buf)
OBJ_TYPE(mod_dns_parser_token_data)
OBJ_TYPE(mod_cr_ds)
OBJ_TYPE(mod_ds_hash_table_mgmt_add)
/* Compression specific */
OBJ_TYPE(mod_ns_compress_config_t)
OBJ_TYPE(mod_compress_msg_t)
OBJ_TYPE(mod_ns_unsuccess_cache_cfg)
/* ST Queue */
OBJ_TYPE(mod_st_queue)

/* AM/MM Push Ingest types */
OBJ_TYPE(mod_am_xfer_data)
OBJ_TYPE(mod_am_xfer_ext_data)
OBJ_TYPE(mod_mm_push_t)

/*
 *******************************************************************************
 * Note: Add new types _before_ this comment
 *******************************************************************************
 */
OBJ_TYPE(mod_socku_t)

/* URL Filter */
OBJ_TYPE(mod_uf_config_t)
OBJ_TYPE(mod_uf_host_str)
OBJ_TYPE(mod_uf_url_str)
OBJ_TYPE(mod_uf_host_str2)
OBJ_TYPE(mod_uf_url_str2)
OBJ_TYPE(mod_uf_body)


/* URL Filter data */
OBJ_TYPE(mod_uf_trie)

/* NFQUEUE/DPI */
OBJ_TYPE(mod_nf_dpi_xfer_t)
OBJ_TYPE(mod_dpi_sesn_data_t)

OBJ_TYPE(mod_diameter_t)

/* Always last item */
OBJ_TYPE(max_mem_types)

/*
 * End of nkn_mem_object_types.h
 */
