#  Makefile
#
# 
#
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

SUBDIRS=\
	lib \
	pam_disabled \
	pam_radius \
	pam_tacplus \
	pam_ldap \
	pam_tallybyname \


# NOTE: These directories must be built and installed as 'root'

include ${PROD_TREE_ROOT}/src/mk/subdir.mk
