#! /bin/bash
#
# fuse: init functions for FUSE module
# Note: The file src/base_os/common/script_files/customer.sh
# runs "chkconfig --add" for this in the "firstboot_graft_2()" function
#
# chkconfig: 3 21 75
# description: load the Fuse kernel module

# Source function library.
. /etc/init.d/functions

MY_LOG_FILE=/log/varlog/nkn/startup/fuse.log

RETVAL=0

start() {
        echo $"Running fuse lkm loader"
        modprobe  fuse >> ${MY_LOG_FILE} 2>&1
        RETVAL=$?
        if [ $RETVAL = 1 ]; then
            echo "Failed to load fuse module `date`" >> ${MY_LOG_FILE}
            echo "Failed to load fuse module."
        fi
        return $RETVAL
}

stop() {
        rmmod fuse >> /dev/null 2>&1
        RETVAL=$?
        return $RETVAL
}

restart() {
        stop
        start
}

reload() {
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  reload)
        reload
        ;;
  status)
        lsmod
        ;;
  *)
        echo $"Usage: $0 {start|stop|status|reload|restart}"
        exit 1
        ;;
esac

exit $?

