# Makefile for  eng/src/am directory
# Modified on : 2008-09-05
# Copyright (c) Nokeena Inc., 2008

# Include Macros
include ../Makefile.inc

# Local Macros
LIB_AM = $(PROJECTLIB)/libnkn_am.a
CFLAGS += -fPIC -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include

SRCS = nkn_am.c nkn_am_list.c nkn_am_tbl.c nkn_am_api.c 
OBJS = $(SRCS:.c=.o)
DEPS = $(SRCS:.c=.dep)


# Rules 
.PHONY: clean clean_self

all: lib

lib: include $(LIB_AM)
	@echo
	@echo "----------AM Library Build Completed----------"
	@echo

$(PROJECTINC):
	@echo
	mkdir -p $(PROJECTINC)

$(PROJECTLIB):
	@echo
	mkdir -p $(PROJECTLIB)

include: $(PROJECTINC)/nkn_am_api.h

$(PROJECTINC)/nkn_am_api.h: nkn_am_api.h $(PROJECTINC)
	$(CP) nkn_am_api.h $(PROJECTINC)

$(LIB_AM): $(PROJECTLIB) $(OBJS)
	$(AR) rv $@ $(OBJS)
	ranlib $@

%.o : %.c
	$(CC) -MD -c $(CFLAGS) -o $@ $<
	$(DOTP_FROM_DOTD)

clean: clean_self

clean_self: 
	$(RM) *.o *.d *.P *.~
	$(RM) $(LIB_AM)
	-rmdir --ignore-fail-on-non-empty $(PROJECTLIB)
	$(RM) $(PROJECTINC)/nkn_am_api.h
	-rmdir --ignore-fail-on-non-empty $(PROJECTINC)

# Include the dependency files 
-include $(SRCS:.c=.P)

# End of Makefile
