#  Makefile
#
# 
#
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

LIB=graph

SRCS= \
	lg_autoscale.c \
	lg_color.c \
	lg_data.c \
	lg_fonts.c \
	lg_formatting.c \
	lg_layout.c \
	lg_rendering.c \
	lg_stats.c \
	lg_structs.c \
	lg_utils.c \

INCLUDES+=-I../libgd

include ${PROD_TREE_ROOT}/src/mk/lib.mk
