#  Makefile
#
# 
#
#

include ${PROD_TREE_ROOT}/src/mk/common.mk

FILES_INSTALL_DIR=/lib/fonts

# XXX/EMT: would be nice to control which of these are installed
# from customer.mk...

FILES= \
	luximr.ttf \
	luxirr.ttf \
	luxisr.ttf \
	luxisb.ttf \
	Vera.ttf \
	VeraSe.ttf \

include ${PROD_TREE_ROOT}/src/mk/files.mk
